### ISSUE TITLE
Android sample: cannot login without Dropbox app installed

### ISSUE THREAD

**Issue by gregko** [dropbox/dropbox-sdk-java#101]
UPDATE: SOLVED: the problem cleared after rebooting the device. Probably I should still test if it will maybe return, if I install the main Dropbox app, start sample, then remove it again... Nope, still works fine after install/uninstall the main Dropbox app. Please close the issue.

The Android sample works beautifully for me when the main Dropbox app is installed on the device (Android 5.1.1 in this case). I did create my own app in Dropbox dev console, obtained my own app key and inserted it both into the AndroidManifest.xml <data android:scheme="db-......" /> and itno the strings.xml. As soon as I uninstall the main Dropbox app, I gen an error message when trying to login and after clicking on "Allow" access:

This stie cant be reached

The webpage at db-yvs......://1/connect?oauth_token=oauth2%3A&oauth_token_secret=.....&state=oauth2....&uid=46381343 might be temporarily down or it may have moved permanently to a new web address.
ERR_UNKNOWN_URL_SCHEME

Also, what I don't understand, is that Dropbox developer site also gives me "app secret" for each app I register, but I don't see any place to enter my own "secret" into the sample. 

Additional info: I'm working with "Permission type: App folder", as this is what I need for my main app. Would appreciate any pointers on how to solve this issue.

Greg

**Comment by greg-db** [comment]
Thanks for the report Greg! I'm glad to hear this is working for you now, and I'll close the issue accordingly. It sounds like it was just a hiccup with the operating system's handling of URL schemes.

Also, for reference, when using client-side apps like with with Dropbox API v2, the app secret is indeed not necessary. (Dropbox API v2 uses OAuth 2, and in this case uses the "implicit" a.k.a. "token" flow in particular, which doesn't need the app secret.)

**Comment by gregko** [comment]
Thank you for your kind answer and explanation, Greg! My experience with other developers was that they would just click "Close" without a word, so I really appreciate your kindness and I'm happy to learn more about these issues.

BTW, this is a long shot, so just silently ignore if you don't have any hint. I'm in need of a good folder sync code through Dropbox SDK (for Android app), similar to what Dropbox desktop app does. If you have ever seen something like this, please share. Thank you again!

Greg

**Comment by greg-db** [comment]
No problem, I'm happy to help.

I'm afraid I don't have any good sync code like that to share. I'll file it as a feature request with the team, but I can't make any promises of course.

**Comment by gregko** [comment]
Thank you again. Little hope for a positive response from the team - there used to be Dropbox folder sync SDK component, but it was depreciated and then killed well before even before SDK 1 was depreciated. Such sync code is very difficult to write. I have something almost working right for most users in my app, that I wrote with SDK 1, now I face a horror of rewriting this to SDK 2 and maybe? improving it a little bit...
