### ISSUE TITLE
FileMetadata in official 3.0.1 binary does not have content_hash

### ISSUE THREAD

**Issue by tdtran** [dropbox/dropbox-sdk-java#106]
[ChangeLog.txt](https://github.com/dropbox/dropbox-sdk-java/blob/master/ChangeLog.txt) section for 3.0.0 says

>   - Added Sha256HexHash alias.
>   - Added content_hash to FileMetadata.

But they are not present in the official 3.0.1 binary for gradle. I think that's because someone forgot to update git submodule `src/main/stone` before making the build. `src/main/stone` stays at very old changeset fee0a62

**Comment by jiuyangzhao** [comment]
Hi @tdtran thank you for letting me know. I will release 3.0.2 early next week with all new specs.

**Comment by jiuyangzhao** [comment]
Hi @tdtran it should be there now.
