### ISSUE TITLE
Warning message in OAuth2 authentication page

### ISSUE THREAD

**Issue by atarsdnh** [dropbox/dropbox-sdk-java#108]
I use Auth.startOAuth2Authentication(context, appKey) to get OAuth2 token, but in the user approve page show that "The old version of the Dropbox platform is being retired on June 28, 2017. The developer of this app has yet to acknowledge the change, so this app may not continue to work in the future.", but I already update sdk to the latest version 3.0.3.

How should I do so that the user page do not show this message?

**Comment by scobbe** [comment]
@atarsdnh: Thanks for reaching out. If you go to https://www.dropbox.com/developers, and you are logged in to the Dropbox account that owns your app, you will see a yellow banner informing you of the API v1 deprecation. Simply click "Acknowledge" on the yellow banner, and then this OAuth warning message will disappear. Let us know if you have any issues doing that.

**Comment by atarsdnh** [comment]
The problem is solved, thank you for your help.
