### ISSUE TITLE
Streaming Audio file

### ISSUE THREAD

**Issue by zakirhussain49** [dropbox/dropbox-sdk-java#112]
Hi All,

How I stream audio file from Dropbox.
I trying a lot to get the Audio file URL or trying to get the mediainfo but I didn't got success , please help me how i achieve this task.

**Comment by greg-db** [comment]
You can use [`getTemporaryLink`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#getTemporaryLink-java.lang.String-) to get a temporary URL for a file. 

If that's not working as expected for you, I'll be happy to help, but I'll need some more information. Please reply with:

    - the version number of the SDK you have installed.
    - the full text of the error/any output.
    - the relevant code snippet(s).

**Comment by zakirhussain49** [comment]
Hi Greg,

I am getting null when I use  getTemporaryLink.

version number - com.dropbox.core:dropbox-core-sdk:3.0.3.
I am not getting any error.

**Comment by greg-db** [comment]
Please share the code that isn't working as expected for you, and indicate what specifically is `null`. Thanks in advance!

**Comment by zakirhussain49** [comment]
private void downloadFile(FileMetadata file) {

        System.out.println("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"+file.getPathDisplay());

        final ProgressDialog dialog = new ProgressDialog(this);
        dialog.setProgressStyle(ProgressDialog.STYLE_SPINNER);
        dialog.setCancelable(false);
        dialog.setMessage("Downloading");
        dialog.show();

        new DownloadFileTask(FilesActivity.this, DropboxClientFactory.getClient(), new DownloadFileTask.Callback() {
            @Override
            public void onDownloadComplete(File result) {
                dialog.dismiss();

                if (result != null) {

                    try {
                        mediaPlayer.setDataSource(result.getPath());
                        callMediaPlayer();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    //viewFileInExternalApp(result);
                }
            }

            @Override
            public void onError(Exception e) {
                dialog.dismiss();

                Log.e(TAG, "Failed to download file.", e);
                Toast.makeText(FilesActivity.this,
                        "An error has occurred",
                        Toast.LENGTH_SHORT)
                        .show();
            }
        }).execute(file);

    }

In the above method I got the file that I have clicked , but I don't want to download the file I just want to  stream in MediaPlayer and for that we need path or URL.

In the above code I tried 
System.out.println("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"+file.getPathDisplay());

it give me only " /filename". I need the complete path 

How I achieve

**Comment by greg-db** [comment]
It looks like this code is [copied from the Android example app](https://github.com/dropbox/dropbox-sdk-java/blob/7ecc15cf0f51d6ae2ba5cdb334aac2c2f3474b87/examples/android/src/main/java/com/dropbox/core/examples/android/FilesActivity.java#L204). That sample just downloads the file though, and it doesn't sound like that's what you're looking for.

If you want to get a URL for the file, you should instead use [`getTemporaryLink`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#getTemporaryLink-java.lang.String-) as previously discussed. I don't see that in your code here though. Have you tried calling that? It would look something like this:

    client.files().getTemporaryLink(filePath).getLink()

**Comment by zakirhussain49** [comment]
thanks greg , I got your point and I completed my task
