### ISSUE TITLE
Invalid Access Token exception

### ISSUE THREAD

**Issue by guidedways** [dropbox/dropbox-sdk-java#113]
After updating to the new v2 SDK, a lot of our users begin to see an invalid_access_token error after a good few days. Once this happens, they're unable to continue using the app unless they re-link. The following, for example, is the error a user suddenly began seeing (in their console logs) after a few days. I could see in the logs that they've been linked and have been using our app successfully when suddenly this started happening:

```
Invalid token exception: 
{"error_summary": "invalid_access_token/...", "error": {".tag": "invalid_access_token"}}  
Error: com.dropbox.core.InvalidAccessTokenException:
 {"error_summary": "invalid_access_token/...", "error": {".tag": "invalid_access_token"}}
```

Any ideas what's going on? This isn't a coincidence as we've got a small number of users reporting these after about 2 weeks or so suddenly.

**Comment by greg-db** [comment]
@guidedways I'm not aware of any issues that should cause unexpected invalid/revoked tokens like this. Have you been able to reproduce this issue yourself? Can you check if your app is accidentally calling [`tokenRevoke`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/auth/DbxUserAuthRequests.html#tokenRevoke--) anywhere?

**Comment by alexeyvasilyev** [comment]
I have the same issue after upgrading to v2 SDK a couple months ago. Currently I use 3.0.3 SDK and it has this problem.
After a couple days users failed to upload files to Dropbox and they need to relink account.

**Comment by guidedways** [comment]
No it's not calling tokenRevoke anywhere - these are new users with newly setup devices (i.e. they've installed our app and setup sync and everything was working till it wasn't). I've got more and more users frequently emailing us with their logs showing they're syncing just fine till all of a sudden we see:

`DROPBOX WARN: Invalid token exception: {"error_summary": "invalid_access_token/...", "error": {".tag": "invalid_access_token"}}  Error: com.dropbox.core.InvalidAccessTokenException: {"error_summary": "invalid_access_token/...", "error": {".tag": "invalid_access_token"}}`

And that's it. From then on, they are no longer linked and we need to get them to sync all over again and merge changes. It's happening quite frequently :(

**Comment by guidedways** [comment]
We've been logging aggressively recently and I can clearly see that the device seemingly is linked just fine, and we're even logging the access token like so:

`DROPBOX DEBUG: Found access token: ckyOt3bmPuEAAAAAAAAFzC5T5JY6dxwnUlFsKmSkvuX37h1m8W0Woh4EPDvPOUsi`

Immediately after this, when we try and connect to Dropbox, it throws the above mentioned exception and from then on the user seems to not be linked anymore. They need to re-link.

I'm not seeing this on iOS yet (using the latest SDK) so it looks like a bug somewhere in the latest Java library.

**Comment by greg-db** [comment]
Thanks for the additional information! For reference, there are a few ways for an access token to be disabled, some of which the user may not have done intentionally:

- the user can revoke all access tokens for an app by unlinking it on https://www.dropbox.com/account/security 
- if the app uses the "app folder" permission, the token can be revoked by deleting the app folder itself in the Dropbox account, either via the Dropbox Web site or any client 
- the app can revoke an access token by calling /2/auth/token/revoke or /1/disable_access_token

If none of these apply, the access token shouldn't be disabled though. I haven't been able to track this down unfortunately, so in lieu of this issue, can you both file API tickets with some more information at:

https://www.dropbox.com/developers/contact

Please include:
- the version number of the SDK you have installed
- the app key for your app
- several samples of unexpectedly revoked access tokens, along with how quickly each became invalid, to the best of your knowledge

Thanks in advance!

**Comment by cherbin** [comment]
Has any progress been made on this ?

**Comment by greg-db** [comment]
@cherbin I see you opened your own issue, so I'll follow up with you there: https://github.com/dropbox/dropbox-sdk-java/issues/210
