### ISSUE TITLE
"This app is not valid!" when using web auth on Andorid API level 20+

### ISSUE THREAD

**Issue by hexise** [dropbox/dropbox-sdk-java#115]
I found a bug when using web auth on Android API level 20+, this will lead to "This app is not valid!" error when auth in Android browser, but the app actually is valid.

In AuthActivity class, startWebAuth(String state) method, it will compose the auth url using Local.getDefault().toString(). Before Android API level 20, this is fine. But after it, the Locale.toString() contains script segment, the toString() result will be similar as "zh_CN_#Hans" instead of "zh_CN". The auth url will become as following:

https://www.dropbox.com/1/connect?locale=zh_CN_#Hans&...

This url will lead to "This app is not valid!" error. If use following url, the error won't happen and the auth can be processed:

https://www.dropbox.com/1/connect?locale=zh_CN&...

The fix might be remove the script part from default locale, or just compose local string in another way.

For instance, using following code to remove script part before locale.toString():

        if (Build.VERSION.SDK_INT >= 21) {
            if (!TextUtils.isEmpty(locale.getScript()))
                locale = new Locale.Builder().setLanguage(locale.getLanguage()).setRegion(locale.getCountry()).setScript(null).build();
        }

I just tested this scenario in Chinese locale, but maybe this also happens on other locales.

Thanks.

**Comment by greg-db** [comment]
Thanks for the report! This is a known issue, but I don't have a timeline for a fix right now.

**Comment by greg-db** [comment]
This should be fixed by [v3.0.4](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v3.0.4).
