### ISSUE TITLE
change prepRequest from private to protected

### ISSUE THREAD

**Issue by cheyrico2** [dropbox/dropbox-sdk-java#118]
Some device use Bouncy Castle to provide URLStreamHandler making it difficult to create a connection with the Default `StandardHttpRequestor`. To resolve this issue, I need to modify the `prepRequest(String url, Iterable<Header> headers)` by changing:
`URL urlObject = new URL(url);`
to 
`URL urlObject = new URL(null, url , new sun.net.www.protocol.https.Handler());`

but because that method is private I can not create an anonymous class but force to copy the whole class just to make change

**Comment by greg-db** [comment]
@cheyrico2 I see you just closed this issue. To clarify, did you find a different solution?

**Comment by cheyrico2** [comment]
I'll leave it open

**Comment by handstandsam** [comment]
I'm cleaning up tickets and have no problem addressing this.  Fixed in https://github.com/dropbox/dropbox-sdk-java/pull/448. Will be in `5.4.0` to be released next week.
