### ISSUE TITLE
skipWhenEmpty not working in stone.gradle

### ISSUE THREAD

**Issue by bcr** [dropbox/dropbox-sdk-java#120]
Building via `./gradlew build`, line 128 in stone.gradle causes the build to stop due to missing property `skipWhenEmpty`:

```
Blakes-MBP:dropbox-sdk-java blake$ ./gradlew build
Set JDK6_HOME environment to disable boot classpath warnings.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/blake/Source/OpenSource/dropbox-sdk-java/stone.gradle' line: 128

* What went wrong:
A problem occurred evaluating script.
> No such property: skipWhenEmpty for class: org.gradle.api.internal.tasks.DefaultTaskInputs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.44 secs
```

Commenting out this line works fine:

```
// inputs.dir(getSpecFiles).skipWhenEmpty = true
```

I am using commit 5b3ee2867f63cd2ccc4b2ed550633449fb570ec1

**Comment by bcr** [comment]
Note that this change was introduced in that merge.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by handstandsam** [comment]
It's now 5 years in the future, but we are using Java 11 to do all of our builds at this point in time to create a Java 1.8 compatible JAR.  Going to close this due to inactivity.
