### ISSUE TITLE
minSdkVersion 19?

### ISSUE THREAD

**Issue by isabsent** [dropbox/dropbox-sdk-java#121]
Why do you claim minSdkVersion 19 in java API V2 for Android? I am able to use Dropbox service (Full Dropbox) in my app with

    minSdkVersion 14
and

    compile 'com.dropbox.core:dropbox-core-sdk:3.0.3'
on Android emulator (Genimotion Custom Phone - **4.1.1 - API 16**)

**Comment by greg-db** [comment]
I don't know off hand why the SDK level is set to 19, but I'll send this along to the team to see if we can officially lower that.

**Comment by isabsent** [comment]
It seems you are using `try(with resources)/catch` block instead of simple `try/catch` block in your code which is supported starting with API 19 only. If so it would be better to do not use it and provide us a support from API 14 at least.

**Comment by greg-db** [comment]
Thanks for the information!

**Comment by devPalacio** [comment]
Closed as stale. SDK 14 is over 10 years old.
