### ISSUE TITLE
Endpoint for Range request.

### ISSUE THREAD

**Issue by isabsent** [dropbox/dropbox-sdk-java#122]
To get some bytes from file on Dropbox API V1 (**Range Request** or a **partial content request**) I use endpoint

    String rangeRequestEndpoint  = "https://api-content.dropbox.com/1/files/dropbox";
with the code below:

    String downloadUrl = rangeRequestEndpoint + Uri.encode(metadata.getPathLower());
    URL url = new URL(downloadUrl); 
    HttpURLConnection con = (HttpURLConnection) url.openConnection();
    con.setRequestMethod("GET");
    con.setRequestProperty("Authorization", "Bearer " + accessToken);
    con.setRequestProperty("Range", "bytes=" + position + "-" + (position + length - 1));
    int responseCode = con.getResponseCode();
    InputStream is = con.getInputStream();  
Which endpoint should I use for this purpose in Dropbox API V2? It seems 

    https://content.dropboxapi.com/2/files/download
**does not support Range Request**.

**Comment by greg-db** [comment]
The API v2 [content-download](https://www.dropbox.com/developers/documentation/http/documentation#formats) endpoints, such as [/2/files/download](https://www.dropbox.com/developers/documentation/http/documentation#files-download), do support Range Requests. 

To use the Dropbox API v2 Java SDK to download portions of a file, you should use [`DbxUserFilesRequests.downloadBuilder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#downloadBuilder-java.lang.String-) to get a [`DownloadBuilder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DownloadBuilder.html) where you can use the [`DbxDownloadStyleBuilder.range`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/DbxDownloadStyleBuilder.html#range-long-long-) methods to specify a range.

**Comment by isabsent** [comment]
Thanks! It works with direct Range Request like:

                URL url = new URL("https://content.dropboxapi.com/2/files/download"); 
                HttpURLConnection con = (HttpURLConnection) url.openConnection();
                con.setRequestMethod("GET");
                con.setRequestProperty("Authorization", "Bearer " + accessToken);
                con.setRequestProperty("Range", "bytes=" + position + "-" + (position + length - 1));
                con.setRequestProperty("Dropbox-API-Arg", "{\"path\": \"" + fileMetadata.getPathLower()  + "\"}");
                int responseCode = con.getResponseCode();
                InputStream is = con.getInputStream();
in V2 API. But how to get `DbxUserFilesRequest`? It needs `DbxRawClientV2` in the constructor. How to get it?

**Comment by greg-db** [comment]
@isabsent Yes, that looks right. Let us know if you run in to any issues.
