### ISSUE TITLE
cancel chunks file upload

### ISSUE THREAD

**Issue by nzala** [dropbox/dropbox-sdk-java#123]
cancel Uploading a file in chunks using multiple requests

**Comment by isabsent** [comment]
It would be nice...

**Comment by greg-db** [comment]
If you get an [`UploadUploader`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/files/UploadUploader.html), e.g., as returned by [`UploadBuilder.start`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/files/UploadBuilder.html#start--), you can call [`DbxUploader.abort`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/DbxUploader.html#abort--) to cancel the upload.

If you're using upload sessions, you control when each chunk is uploaded, so you can stop the process in between any two chunks. You can also still `abort` an individual chunk upload, the same as above, e.g., on [`UploadSessionAppendV2Uploader`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/files/UploadSessionAppendV2Uploader.html).

**Comment by nzala** [comment]
can you give an e.g

**Comment by greg-db** [comment]
I don't have a example of this available, but it would be similar to the upload example here:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/upload-file/src/main/java/com/dropbox/core/examples/upload_file/Main.java#L122

Instead of calling `uploadAndFinish` directly on the result of `uploadSessionAppendV2`, you would save the result and call `uploadAndFinish` on it separately, and then also call `abort` on it if/when desired.

Please give that a try and let us know if you run in to any issues.

**Comment by nzala** [comment]
i have done this before i added this
and using AsyncTask file is Uploaded in chunks and cancelling Upload in separate AsyncTask in dbxUploader.abort wrks in serialized way

**Comment by nzala** [comment]
cde

```
try (InputStream in = new FileInputStream(file))
                {
                    // if this is a retry, make sure seek to the correct offset
                    in.skip(uploaded);

                    // (1) Start
                    if (sessionId == null) {
                        UploadSessionStartUploader uploadSessionStartUploader = dbxClient.files().uploadSessionStart();
                        dbxUploader = uploadSessionStartUploader;
                        sessionId = uploadSessionStartUploader.uploadAndFinish(in, CHUNKED_UPLOAD_CHUNK_SIZE)
                                .getSessionId();
                        uploaded += CHUNKED_UPLOAD_CHUNK_SIZE;
                        //printProgress(uploaded, size);
                        Log.d("Start", String.valueOf(uploaded + " " + size));
                    }

                    UploadSessionCursor cursor = new UploadSessionCursor(sessionId, uploaded);

                    // (2) Append
                    while ((size - uploaded) > CHUNKED_UPLOAD_CHUNK_SIZE) {
                        uploadSessionAppendV2Uploader = dbxClient.files().uploadSessionAppendV2(cursor);
                        dbxUploader = uploadSessionAppendV2Uploader;
                        uploadSessionAppendV2Uploader.uploadAndFinish(in, CHUNKED_UPLOAD_CHUNK_SIZE);
                        uploaded += CHUNKED_UPLOAD_CHUNK_SIZE;
                        //printProgress(uploaded, size);
                        Log.d("Upload", String.valueOf(uploaded + " " + size));
                        cursor = new UploadSessionCursor(sessionId, uploaded);
                    }

                    // (3) Finish
                    long remaining = size - uploaded;
                    CommitInfo commitInfo = CommitInfo.newBuilder("/" + file.getName())
                            .withMode(WriteMode.ADD)
                            .build();
                    uploadSessionFinishUploader = dbxClient.files().uploadSessionFinish(cursor, commitInfo);
                    dbxUploader = uploadSessionFinishUploader;
                    FileMetadata metadata = uploadSessionFinishUploader.uploadAndFinish(in, remaining);

                    System.out.println(metadata.toStringMultiline());
                    return metadata;
                }
```

```
task = new cancel();
task.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);
```

```
public class cancel extends AsyncTask {

    public cancelUpload {

    }
    @Override
    protected Object doInBackground(Object[] params) {
        try {
            if(uploadUploader != null) {
                uploadUploader.abort();
            }

            if(dbxUploader != null) {
                dbxUploader.abort();
            }
            return true;
        } catch(Exception e) {
            e.printStackTrace();
        }

        return null;
    }

    @Override
    protected void onPostExecute(Object o) {
        super.onPostExecute(o);
    }
}
```

**Comment by isabsent** [comment]
Depending on file size and internet connection speed it may take a long time to upload file, It would be better to use IntentService instead of AsyncTask for such operation, because AsyncTask is suitable for short operation like file deletion for example.

**Comment by nzala** [comment]
i made in paralell but after dbxUploader.abort(); file is uploaded

**Comment by nzala** [comment]
IntentService works in queue
