### ISSUE TITLE
Partial changing of the existing file.

### ISSUE THREAD

**Issue by isabsent** [dropbox/dropbox-sdk-java#124]
Is it possible to **change some part of already existing file** with the API V2? It is necessary for an editing  of encrypted containers without downloading them.

**Comment by greg-db** [comment]
No, unfortunately the Dropbox API does't offer the ability to upload only a changed portion like this, but I'll pass this along as a feature request.

**Comment by handstandsam** [comment]
Closing as an answer was provided, and this ticket has been inactive.
