### ISSUE TITLE
class file for okhttp3.OkHttpClient not found

### ISSUE THREAD

**Issue by nickhma** [dropbox/dropbox-sdk-java#126]
Gradle build error when creating DbxClientV2 (like in DropboxClientFactory):
```
Error:(13, 93) error: cannot access OkHttpClient
class file for okhttp3.OkHttpClient not found
```
I know this is solved by including OkHttp inside dependencies, but I just wanted to raise this issue because this is not clear from the Setup section on your README.

**Comment by bazimogmbh** [comment]
You should add the dependency of OkHttp, only if you explicitly want to use it. 
The dropbox cleint can be created wittout external dependency as following 

        StandardHttpRequestor requestor = new StandardHttpRequestor(config);
        DbxRequestConfig requestConfig = DbxRequestConfig.newBuilder(clientUserAgentId)
            .withHttpRequestor(requestor)
            .build();
        new DbxClientV2(requestConfig, auth.getAccessToken(), auth.getHost());

**Comment by greg-db** [comment]
That's correct, use of OkHttp is optional. I'll ask the team to clarify this in the README.

**Comment by nickhma** [comment]
Thank you!

**Comment by AbandonedCart** [comment]
You may want to update the samples, too. As of today (Oct 2, 2018), I landed here searching for a solution to the same issue when working with the sample code.

**Comment by greg-db** [comment]
@AbandonedCart Thanks! I'll make a note of that with the team as well.
