### ISSUE TITLE
Use a different PipedInputStream implementation to workaround NPE on Android < 7.0

### ISSUE THREAD

**Issue by yukuku** [dropbox/dropbox-sdk-java#127]
Regarding issue #107, it was closed without a solution.

The bug was in Android implementation of PipedInputStream, which is used by OkHttpUtil.java.
The bug is fixed only in Android 7.0, leaving a lot of users affected by this bug.

Is it possible for the Dropbox SDK to use its own implementation of PipedInputStream
instead of relying on java.io.PipedInputStream, at least on Android < 7.0?

**Comment by greg-db** [comment]
Thanks for writing this up! I can't make any promises, but I'll ask the team to consider implementing a workaround like this.
