### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by sameerthigale** [dropbox/dropbox-sdk-java#131]
I'm getting the following exception in some of the cases when downloading a file from Dropbox.

Details:

```
Exception com.a.a.p: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Caused by javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Caused by java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

**Comment by greg-db** [comment]
What version of the SDK are you using? This should have been fixed in [v2.0.5](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v2.0.5), for issue #57. 

If you're not already using the latest version (currently v3.0.3), please update and let me know if you're still seeing this issue.

**Comment by sameerthigale** [comment]
I'm using Dropbox version 3.0.3 on Android

On 01-Aug-2017 6:59 PM, "Greg K" <notifications@github.com> wrote:

What version of the SDK are you using? This should have been fixed in v2.0.5
<https://github.com/dropbox/dropbox-sdk-java/releases/tag/v2.0.5>, for
issue #57 <https://github.com/dropbox/dropbox-sdk-java/issues/57>.

If you're not already using the latest version (currently v3.0.3), please
update and let me know if you're still seeing this issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dropbox/dropbox-sdk-java/issues/131#issuecomment-319370056>,
or mute the thread

**Comment by greg-db** [comment]
Thanks! Can you share the code to reproduce it? Please include how you're setting up the HTTP requestor as well.

Also, it looks like this may be specific to the version of JRE. What version are you using?

**Comment by sameerthigale** [comment]
I'm using the following code to download file:

public DropBox(@NonNull final String ACCESS_TOKEN) {
        DbxRequestConfig config = new DbxRequestConfig("");
        mClient = new DbxClientV2(config, ACCESS_TOKEN);
    }

private void downloadFile(@NonNull final String inPath, @NonNull final OutputStream outputStream) throws IOException, DbxException {
        mClient.files().downloadBuilder(inPath).download(outputStream);
    }


Please include how you're setting up the HTTP requestor as well.
>> Can you please elaborate this.

Yes, this is reproducible only on some devices. 

Also, it looks like this may be specific to the version of JRE. What version are you using?
>> I don't know the exact JRE version, but its Android 6.0.1.

**Comment by greg-db** [comment]
Thanks! I was referring to setting the [`HttpRequestor`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/http/HttpRequestor.html), e.g., [as shown here](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/DropboxClientFactory.java#L18). The code you included covers that though. You're not explicitly setting one, so you're using [`StandardHttpRequestor`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/http/StandardHttpRequestor.html) by default.

Also, you mentioned this only happens on certain devices. To clarify:
- Which devices? Does it consistently occur on these specific types of devices?
- Do the same types of devices work if they aren't running 6.0.1?

**Comment by sameerthigale** [comment]
Which devices?
>> Currently I've data only for 1 device: LGE Nexus 5x running on Android OS 6.0.1

Does it consistently occur on these specific types of devices?
Do the same types of devices work if they aren't running 6.0.1?
>> Sorry, no information

You're not explicitly setting one, so you're using StandardHttpRequestor by default.
>> Do I need to change this? Has this anything to do with this bug?

Stack here, in case it helps you:
com.android.org.conscrypt.TrustManagerImpl.checkTrusted (TrustManagerImpl.java:324)
com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted (TrustManagerImpl.java:225)
com.android.org.conscrypt.Platform.checkServerTrusted (Platform.java:115)
com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain (OpenSSLSocketImpl.java:556)
com.android.org.conscrypt.NativeCrypto.SSL_do_handshake (NativeCrypto.java)
com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake (OpenSSLSocketImpl.java:324)
com.android.okhttp.internal.http.SocketConnector.connectTls (SocketConnector.java:103)
com.android.okhttp.Connection.connect (Connection.java:143)
com.android.okhttp.Connection.connectAndSetOwner (Connection.java:185)
com.android.okhttp.OkHttpClient$1.connectAndSetOwner (OkHttpClient.java:128)
com.android.okhttp.internal.http.HttpEngine.nextConnection (HttpEngine.java:341)
com.android.okhttp.internal.http.HttpEngine.connect (HttpEngine.java:330)
com.android.okhttp.internal.http.HttpEngine.sendRequest (HttpEngine.java:248)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute (HttpURLConnectionImpl.java:437)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect (HttpURLConnectionImpl.java:114)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream (HttpURLConnectionImpl.java:245)
com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream (DelegatingHttpsURLConnection.java:218)
com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream (HttpsURLConnectionImpl.java)

**Comment by greg-db** [comment]
Thanks! And no, you're not required to explicitly set an HttpRequestor.

We'll look into it.

**Comment by sameerthigale** [comment]
Greg, this issue looks like intermittent and no consistent repro on the same model but other device.

**Comment by greg-db** [comment]
Thanks for the information! We'll look into it and let you know when we have an update for you.

**Comment by RuchiDhore** [comment]
I'm also facing the same error:
Exception com.dropbox.core.NetworkIOException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
 Caused by java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Device: Samsung SM-N910W8 Android OS 4.4.4 (19) 
Got repro twice.

Please help.

**Comment by RuchiDhore** [comment]
@greg-db , is it possible to disable SSL/HTTPS when connecting to dropbox using Java SDK. Since I don't require my users to SSL when connecting.

**Comment by greg-db** [comment]
Thanks for the information @RuchiDhore ! We're looking into it.

And no, as a matter of security for our users, we require the use of SSL/TLS for all API calls.

**Comment by sameerthigale** [comment]
Greg, could reproduce this on Samsung device as well.

Android OS: 7.0 (24)
Model: Samsung SM-G928V

**Comment by greg-db** [comment]
Thanks for the additional information Sameer!

**Comment by sameerthigale** [comment]
Repro with OnePlus A3000, Android OS: 7.1.1 (25), Locale: en-AU.

Greg, do you what is the possible cause for this? Since, many of my users are facing this issue, I want to provide them with some troubleshooting information. Can you please suggest any?
Is this due to date / time mismatch?

Stack trace:
Exception com.dropbox.core.NetworkIOException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Caused by javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Caused by java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Caused by java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by greg-db** [comment]
Thanks! I don't have an update on this yet, but I'll follow up here once I do.

**Comment by sameerthigale** [comment]
@greg-db, I see a commit done by Kannan for this request (https://github.com/dropbox/dropbox-sdk-java/pull/135)

When can we expect this change to be available to us?

BTW, do you know if there is any workaround to this where we can "approve" the certificate and by-pass this issue?

**Comment by greg-db** [comment]
@sameerthigale I don't have a timeline on that right now unfortunately, or a workaround to offer. I'll follow up here once I have any news on this.

**Comment by cakoose** [comment]
@sameerthigale: The patch just adds a little more information to the exception message.  If you are able to reproduce the issue with the patched SDK, that extra information might us figure out what's going wrong.

To build a patched SDK:

```
# Clone the repo if you haven't already.
git clone git@github.com:dropbox/dropbox-sdk-java.git
cd dropbox-sdk-java

# Check out a branch with PR 135
git fetch origin pull/135/head:pr-135
git checkout pr-135
./update-submodules

# Get the dependencies for the Python-based code generator
sudo -H python -m easy_install pip
sudo -H python -m pip install virtualenv
sudo -H python -m virtualenv env
source env/bin/activate
pip install 'ply >= 3.4' 'six >= 1.3.0'

# Run the build
./gradlew build
```

If your project can use a JAR directly:
1. Get the JAR from `build/libs/dropbox-core-sdk-0-SNAPSHOT.jar`
2. Drop the JAR into your project.

If your project needs to pull everything from a Maven repository.
1. Run `./gradlew install` to install the JAR to the local Maven repository.
2. Change your project's Dropbox SDK dependency to reference newly-installed version, "0-SNAPSHOT".  For example, in a Maven "pom.xml" file, this would look like:

```
<dependency>
    <groupId>com.dropbox.core</groupId>
    <artifactId>dropbox-core-sdk</artifactId>
    <version>0-SNAPSHOT</version>
</dependency>
```

**Comment by sameerthigale** [comment]
@cakoose 
Is using Gradle to include DropBox:

dependencies {
    // ...
    compile 'com.dropbox.core:dropbox-core-sdk:3.0.3'
}

Any easier way for me to do it using this?

**Comment by cakoose** [comment]
Just change "3.0.3" to "0-SNAPSHOT".  (You still have to do the full build and `./gradlew install` first.)

**Comment by sameerthigale** [comment]
I was unable to build Dropbox, but I've added changes similar to what you've done. This will help you get the cert path. Once our release is done and we start getting stack trace, I will update with relevant info.

Thanks :)

**Comment by greg-db** [comment]
The latest release, currently [v3.0.4](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v3.0.4), should now output more specific error information for this. Anyone seeing this issue, please update to that and share the new output. Thanks in advance!
