### ISSUE TITLE
File Attributes, for example size.

### ISSUE THREAD

**Issue by dannychase2004** [dropbox/dropbox-sdk-java#132]
If I call the /2/files/list_folder API call, I get a JSON which includes many properties, including:
 {
      ".tag": "file",
      "name": "Release_2_0.zip",
      "path_lower": "/release_2_0.zip",
      "path_display": "/Release_2_0.zip",
      "id": "id:fc6oJrlxgqAAAAAAAAAABA",
      "client_modified": "2015-04-06T01:27:14Z",
      "server_modified": "2015-04-29T23:31:12Z",
      "rev": "333ebf601",
      "size": 48990990,
      "content_hash": "b99962744734a5010bfd2550674fd1b1699468e675a939b007b889afc33f9c0f"
    }

However, if I try to use ListFolderResult result = client.files().listFolder(path) in the JAVA API, I can't seem to get to these attributes. For example, the Metadata class only seems to support a few of the members. What am I doing wrong?

I basically need the file size, then some way to tell if it's a directory, or a file.

Thank you for your time,
Dan Chase

**Comment by cakoose** [comment]
`Metadata` is the base class.  You need to do an `instanceof` check and then a cast to get the more specific subclass.

**Comment by dannychase2004** [comment]
Wow! I didn't even see the FileMetaData class in there. After your answer, I had to highlight Metadata and hit "Type Heiarchy", and there it was! thanks!
