### ISSUE TITLE
Specifying any clientIdentifier works when creating DbxRequestConfig?

### ISSUE THREAD

**Issue by sameerthigale** [dropbox/dropbox-sdk-java#133]
Following documentation https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/DbxRequestConfig.html#DbxRequestConfig-java.lang.String-

states that

`clientIdentifier - client identifier typically in the form "Name/Version" to be used in the User-Agent header (see getClientIdentifier()).`

Specifying anything here works. Even empty string works. Then what is the use of the parameter?
Can you please update the Javadoc to explain the meaning of clientIdentifier?

Thanks

**Comment by bazimogmbh** [comment]
Please read a bit more about the sole purpose of User Agents. It is up to you to set it the way you want, you can even leave it empty.

14.43 User-Agent

The User-Agent request-header field contains information about the user agent originating the request. This is for statistical purposes, the tracing of protocol violations, and automated recognition of user agents for the sake of tailoring responses to avoid particular user
agent limitations. User agents SHOULD include this field with
requests. The field can contain multiple product tokens (section 3.8) and comments identifying the agent and any subproducts which form a
significant part of the user agent. By convention, the product tokens are listed in order of their significance for identifying the
application.

**Comment by greg-db** [comment]
Thanks for sharing that information Abhishek! Sameer, Abhishek is correct, this identifier is used in the `User-Agent`, which is detailed in the resources he included.
