### ISSUE TITLE
How to create file AAA.txt if folder already contains file aaa.txt?

### ISSUE THREAD

**Issue by isabsent** [dropbox/dropbox-sdk-java#134]
I am creating a new empty file `aaa.txt` by means of:

    api.files().upload(/path/to/folder/aaa.txt).uploadAndFinish(new ByteArrayInputStream(new byte[]{}));
How can I create a new file `AAA.txt` containing some text in the same folder!?

    upload("/path/to/folder/AAA.txt").uploadAndFinish(new ByteArrayInputStream("some text".getBytes()));
gives me an exception with conflict message!

**Comment by varenc** [comment]
I'm just a nobody, but Dropbox is case insensitive so "aaa.txt" and "AAA.txt" are the same file to Dropbox and the conflict message you're getting is exactly what you should be seeing.  That wonderfully informative "path/conflict/file/.." error summary is just telling you there's already a file at that path.

(on that note, time to unsubscribe from notifications for this repo!)

**Comment by greg-db** [comment]
That's correct, thanks Chris!
