### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by RuchiDhore** [dropbox/dropbox-sdk-java#136]
Hello everyone, 

My Android app users face the following error when downloading a file through Dropbox:

[Sample Stack trace]
```
Exception com.dropbox.core.NetworkIOException: **Handshake failed**
Caused by javax.net.ssl.SSLHandshakeException: Handshake failed
Caused by javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xae6c7680: Failure in SSL library, usually a protocol error error:100c543e:SSL routines:ssl3_read_bytes:TLSV1_ALERT_INAPPROPRIATE_FALLBACK (external/boringssl/src/ssl/s3_pkt.c:972 0xa34f97c0:0x00000001)
```

1. Instance 1:
Device: LG-D850
OS: 6.0

2. Instance 2:
Device: LGE VS985 4G
OS: 6.0

3. Instance 3:
Device: TECNO-Y2
OS: 4.4.2

4. Instance 4:
Device: Samsung SM-J200G
OS: 5.1.1

**Dropbox version: 3.0.3**

Here is my code to download the file:

```
public DropBox(@NonNull final String ACCESS_TOKEN) {
        DbxRequestConfig config = new DbxRequestConfig("");
        mClient = new DbxClientV2(config, ACCESS_TOKEN);
    }

private void downloadFile(@NonNull final String inPath, @NonNull final OutputStream outputStream) throws IOException, DbxException {
        mClient.files().downloadBuilder(inPath).download(outputStream);
    }
```

Thank you for your time.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by greg-db** [comment]
We're investigating, but we could use some more information:

1) Is that the full code you're using to construct your `DbxRequestConfig` and `DbxClientV2`? I don't see it in your code, but just to check, are you using okhttp?

2) For the devices where you see this issue, does it occur on every download call, or only sometimes? If it only occurs sometimes, is there anything that may be interrupting the network connection, e.g., like switching from WiFi to cellular?

**Comment by RuchiDhore** [comment]
Is that the full code you're using to construct your DbxRequestConfig and DbxClientV2?
Yes

are you using okhttp?
No

For the devices where you see this issue, does it occur on every download call, or only sometimes? 
For one of the devices, I saw it multiple times

**Comment by cakoose** [comment]
I searched around a bit and found reports of similar issues in other projects.  Some people have noticed that it sometimes has to do with the network.

Are you able to reproduce this issue both on WiFi and on cellular data?  If you switch to a different WiFi network, does the issue go away?

**Comment by RuchiDhore** [comment]
@cakoose I doubt this has to do with network.
Since, my users are also facing "SSL Handshake timeout" exceptions which has to do with network but not this one.

Are you able to reproduce this issue both on WiFi and on cellular data?
>> Yes

If you switch to a different WiFi network, does the issue go away?
>> This is end-user reported issue. I will ask them to try out and get back.

**Comment by AntJahja** [comment]
Are there any updates on this issue?

**Comment by greg-db** [comment]
@AntJahja It looks like we never reached a resolution here. I'll close this issue out as it's old and inactive.

Note that if you only recently (such as within the last week) began seeing an SSL/TLS issue, that may be due to a recent change to our TLS configuration. Dropbox recently retired support for older versions of the TLS protocol, specifically 1.0 and 1.1. You'll need to make sure your app uses TLS 1.2. If you're using this Dropbox Java SDK, make sure you're using at least v3.1.1 (or preferably the latest version, which is v5.2.0) to support that.

Otherwise, feel free to [open a new issue](https://github.com/dropbox/dropbox-sdk-java/issues/new) with the details of the issue you're seeing.

**Comment by AntJahja** [comment]
@greg-db Thank you very much for your response and support!
Since I was working on some legacy code, it turned that updating the Dropbox Java SDK to v3.1.1 (or later) solved the problem.

**Comment by isabsent** [comment]
> @greg-db Thank you very much for your response and support! Since I was working on some legacy code, it turned that updating the Dropbox Java SDK to v3.1.1 (or later) solved the problem.

The same for me: 3.0.3 -> 5.2.0
By the way - 3.0.3 was working fine couple months before...
