### ISSUE TITLE
com.dropbox.core.ServerException with no explanation

### ISSUE THREAD

**Issue by RuchiDhore** [dropbox/dropbox-sdk-java#137]
I see some of users are getting this exception:
StackTrace:
 Exception com.dropbox.core.ServerException:
com.myapp.XXX$1.run (XXX.java)
java.lang.Thread.run (Thread.java:818)

There is no explanation to why this exception has occurred.

Using Dropbox: 3.0.3
Device:  Acer B3-A20 
Android OS: 5.1

Any direction would be helpful here:

**Comment by greg-db** [comment]
@RuchiDhore This error indicates an issue on the Dropbox API servers. Please [open an API ticket here](https://www.dropbox.com/developers/contact) with the following details so we can look into it specifically for you:

- the affected user ID(s)
- the app name
- the relevant code snippet(s)

Thanks in advance!
