### ISSUE TITLE
com.dropbox.core.NetworkIOException: Hostname content.dropboxapi.com not verified

### ISSUE THREAD

**Issue by sameerthigale** [dropbox/dropbox-sdk-java#139]
I'm getting the following error for one of my app user when downloading a file:
[Stacktrace]
Exception com.dropbox.core.NetworkIOException: Hostname content.dropboxapi.com not verified: certificate: sha256/khJFoaQQA9Ekdp6Dpj1x/y4NzXevYXgYDdSk1Z2CEJw= DN: CN=securelogin.hughes.net subjectAltNames: [securelogin.hughes.net]
Caused by javax.net.ssl.SSLPeerUnverifiedException: Hostname content.dropboxapi.com not verified: certificate: sha256/khJFoaQQA9Ekdp6Dpj1x/y4NzXevYXgYDdSk1Z2CEJw= DN: CN=securelogin.hughes.net subjectAltNames: [securelogin.hughes.net]

Dropbox: 3.0.3
Android OS: 5.1.1
Model: SAMSUNG-SM-N910A

Code:
public DropBox(@NonNull final String ACCESS_TOKEN) {
        final OkHttpClient okHttpClient = OkHttp3Requestor.defaultOkHttpClientBuilder()
                .connectTimeout(60, TimeUnit.SECONDS)
                .writeTimeout(60, TimeUnit.SECONDS)
                .readTimeout(60, TimeUnit.SECONDS)
                .build();
        final DbxRequestConfig config =
                DbxRequestConfig
                        .newBuilder("")
                        .withHttpRequestor(new OkHttp3Requestor(okHttpClient))
                        .build();
        mClient = new DbxClientV2(config, ACCESS_TOKEN);
    }

private void downloadFile(@NonNull final String inPath, @NonNull final OutputStream outputStream) throws IOException, DbxException {
            mClient.files().downloadBuilder(inPath).download(outputStream);
    }

Please help. Thanks :)

**Comment by cakoose** [comment]
The server you're connecting returns a TLS certificate that says it's "securelogin.hughes.net", but the Dropbox SDK expects to be connecting to "content.dropboxapi.com" and so it rejects the connection.

One common way this happens is when WiFi access points want you to log in before they give you internet access.  They do that by redirecting all requests to their log in server.  So, for example, even if you make a request to "content.dropboxapi.com", the WiFi access point will convert the request to go to the log in server.

**Comment by sameerthigale** [comment]
So this is not a bug. Thanks :)
