### ISSUE TITLE
500 ServerException without message when deleting file

### ISSUE THREAD

**Issue by jacobras** [dropbox/dropbox-sdk-java#141]
I'm adding a file using the SDK and then I delete it using the SDK. I see the file being deleted from Dropbox, but the call returns a `500 ServerException` with an empty `message` parameter. This behavior is consistent.

The request ID for my latest attempt is `ee2fdc2ca0e2c472f88ffa9a361e5efe`.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by greg-db** [comment]
Apologies for the delay here. This should be fixed. Let me know if you're still seeing these.

**Comment by jacobras** [comment]
I will, Greg! Thanks for always following up on these issues, much appreciated!
