### ISSUE TITLE
Proguard rules not working

### ISSUE THREAD

**Issue by ShivamDev31** [dropbox/dropbox-sdk-java#143]
Android app is not running whenever I enable proguard. I tried the proguard rules given in the examples.
Below is the error I'm getting : 

`Warning:com.dropbox.core.http.OkHttpRequestor$AsyncCallback: can't find superclass or interface com.squareup.okhttp.Callback
Warning:com.dropbox.core.http.OkHttpRequestor$PipedRequestBody: can't find superclass or interface com.squareup.okhttp.RequestBody
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.OkHttpClient
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Dispatcher
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.OkHttpClient
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Request$Builder
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.OkHttpClient
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Call
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Response
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.ResponseBody
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Request$Builder
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Headers
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.OkHttpClient
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Dispatcher
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Request
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Call
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Response
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.ResponseBody
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Headers
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.OkHttpClient
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Request$Builder
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Response
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Request$Builder
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Response
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Request$Builder
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Headers
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.OkHttpClient
Warning:com.dropbox.core.http.OkHttpRequestor: can't find referenced class com.squareup.okhttp.Headers
Warning:com.dropbox.core.http.OkHttpRequestor$AsyncCallback: can't find referenced class com.squareup.okhttp.Callback
Warning:com.dropbox.core.http.OkHttpRequestor$AsyncCallback: can't find referenced class com.squareup.okhttp.Response
Warning:com.dropbox.core.http.OkHttpRequestor$AsyncCallback: can't find referenced class com.squareup.okhttp.Request
Warning:com.dropbox.core.http.OkHttpRequestor$AsyncCallback: can't find referenced class com.squareup.okhttp.Response
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Request$Builder
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.OkHttpClient
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Call
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Request$Builder
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.RequestBody
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Call
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Response
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.ResponseBody
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Request$Builder
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Response
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.OkHttpClient
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Call
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.RequestBody
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Response
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.ResponseBody
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Request
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Request$Builder
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.RequestBody
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Call
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Request$Builder
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.RequestBody
Warning:com.dropbox.core.http.OkHttpRequestor$BufferedUploader: can't find referenced class com.squareup.okhttp.Response
Warning:com.dropbox.core.http.OkHttpRequestor$PipedRequestBody: can't find referenced class com.squareup.okhttp.RequestBody
Warning:com.dropbox.core.http.OkHttpRequestor$PipedRequestBody: can't find referenced class com.squareup.okhttp.MediaType
Warning:there were 95 unresolved references to classes or interfaces.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebug'.
> Job failed, see logs for details
Information:BUILD FAILED`

**Comment by greg-db** [comment]
Are you using the latest release, currently v3.0.3? If not, please upgrade and let us know if you're still running in to this.

If so, please share the following so we can try to reproduce it:
- your build.gradle or pom.xml
- your proguard-rules.pro
- your AndroidManifest.xml
- the relevant code

**Comment by ShivamDev31** [comment]
Hi @greg-db Thanks for your reply.
Yeah I'm using v3.0.3 and I just stumbled upto [https://github.com/dropbox/dropbox-sdk-java#does-this-sdk-require-any-special-proguard-rules-for-shrink-optimizations](https://github.com/dropbox/dropbox-sdk-java#does-this-sdk-require-any-special-proguard-rules-for-shrink-optimizations) and it fixed the issue.

Thanks
