### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by codedsun** [dropbox/dropbox-sdk-java#146]
The Link to App Console is broken in Readme.md under the section "Register a Dropbox API app".
Kindly update the following.

Initially it's redirecting to https://github.com/dropbox/dropbox-sdk-java/blob/master/developers/apps

It should be updated to https://www.dropbox.com/developers/apps

**Comment by jiuyangzhao** [comment]
Thanks for reporting! We have fixed it.
