### ISSUE TITLE
Add method to read "account_id" field from DbxAuthFinish 

### ISSUE THREAD

**Issue by mustpax** [dropbox/dropbox-sdk-java#149]
`com.dropbox.core.DbxAuthFinish` is parsed back from the response to the `/oauth2/token` endpoint. This endpoint contains two user ids: the legacy`uid` field and the recommended`account_id` field.

`DbxAuthFinish.getUserId()` returns `uid`. There is no current way to get the `account_id` field from the response with `DbxAuthFinish`. There should be a separate `getAccountId()` method for reading `account_id`.

I'm happy to create a PR to make this improvement this if maintainers are open to it.

**Comment by greg-db** [comment]
Thanks for the post! I'll send this along to the team.

We do welcome push requests if you'd like to put one together. Thanks!

**Comment by jiuyangzhao** [comment]
I've added code to expose this field. Will be out in next release.

**Comment by greg-db** [comment]
For reference, this is now available as [`DbxAuthFinish.getAccountId`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/DbxAuthFinish.html#getAccountId--) as of [v3.0.6](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v3.0.6).
