### ISSUE TITLE
Using Android Fragment with Auth redirect

### ISSUE THREAD

**Issue by Raywilliams01** [dropbox/dropbox-sdk-java#151]
Hello Everyone,

I am trying to redirect the user back to the android app after call `Auth.startOAuth`..... command. The problem is after the user is does the authentication the user is not redirect back to the App the user is still in the Chrome browser. 

```
if (accessToken == null) {
    Auth.startOAuth2Authentication(getActivity().getApplicationContext(), getString(R.string.app_key));
}
```

**Comment by greg-db** [comment]
The user should be automatically redirected via the custom URL scheme defined for your app. Did you configure that with your app key as shown here?

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/AndroidManifest.xml#L33
