### ISSUE TITLE
metadata error

### ISSUE THREAD

**Issue by jchunly** [dropbox/dropbox-sdk-java#152]
tengo un error en FileMetadata metadata = params[0];
al intentar descargar un archivo, simpre params es 0.
como asigno un archivo de dropbox a esos parametros.
algun ejemplo un poco mas claro y sencillo a los que hay???

**Comment by greg-db** [comment]
No entiendo su pregunta. ¿Puedes elaborar? Comparte el código para reproducir el problema y cualquier error / salida.
--------
I don't understand your question. Can you elaborate? Please share the code to reproduce the issue, and any error/output.

**Comment by jchunly** [comment]
ya esta solucionador. gracias.
