### ISSUE TITLE
Security alert

### ISSUE THREAD

**Issue by phukhanhlee** [dropbox/dropbox-sdk-java#153]
Auth.startOAuth2Authentication(DropboxListActivity.this, appKey);

I got popup error : "Security alert -Another app on your phone may be trying to pose as the app you are currently using....."

I removed all app related to this appKey in my phone. With sdk v1(now deprecated not working anymore) this can help. But now i have just updated to sdk v2, how to resolve this problem ! please hep !

This "appKey" is now using for my android app (which i need to update to v2). Do i need to create new dropbox app and generate new dropbox app key ? or I can reuse current appKey to update my android app.

Thanks,
Khanh

**Comment by zjiuyang** [comment]
Hey to help you debugging.

The code of validating intent is [here](https://github.com/dropbox/dropbox-sdk-java/blob/5f47303107da2813f696b520ce976b73d0ba7847/src/main/java/com/dropbox/core/android/AuthActivity.java#L275).

You can run similar code in your app and see which app on your phone is conflicting with it.

**Comment by phukhanhlee** [comment]
Thanks for your help to find out my problems ! This is my fault. It is not same key in another app :) It's duplicate AuthActivity activity in manifest.xml.
