### ISSUE TITLE
API changes report for Dropbox SDK

### ISSUE THREAD

**Issue by lvc** [dropbox/dropbox-sdk-java#154]
The review of API changes for the Dropbox SDK since 2.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/dropbox-core-sdk/

Hope it will be helpful for users and maintainers of the library.

The report is generated for jars found at http://central.maven.org/maven2/com/dropbox/core/dropbox-core-sdk/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![dropbox-core-sdk-2](https://user-images.githubusercontent.com/1517837/31113912-478576d4-a824-11e7-94aa-0d0d9743d394.png)
![dropbox-core-sdk-1](https://user-images.githubusercontent.com/1517837/31113913-4785ed44-a824-11e7-8c18-effdf6d73740.png)

**Comment by greg-db** [comment]
Thanks!
