### ISSUE TITLE
_data column is not found exception in 7.0 Nougat

### ISSUE THREAD

**Issue by kumarbhubnesh** [dropbox/dropbox-sdk-java#156]
Hi Am using URIHelpers.java for getting the uri from file path but in nougat its throwing exception.

```
 Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
     at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
     at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
     at dropbox.UriHelpers.getDataColumn(UriHelpers.java:98)
     at dropbox.UriHelpers.getFileForUri(UriHelpers.java:73)
     at dropbox.UploadFileTask.doInBackground(UploadFileTask.java:62)
     at dropbox.UploadFileTask.doInBackground(UploadFileTask.java:28)
     at android.os.AsyncTask$2.call(AsyncTask.java:304)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
     at java.lang.Thread.run(Thread.java:761) 
```

**Comment by greg-db** [comment]
@kumarbhubnesh Can you share the code that reproduces this issue? Thanks in advance!

**Comment by kumarbhubnesh** [comment]
[UriHelpers.txt](https://github.com/dropbox/dropbox-sdk-java/files/1368039/UriHelpers.txt) Line no. 73 of this file. i have used this file from dropbox sample.

**Comment by greg-db** [comment]
@kumarbhubnesh Apologies, I'm not sure I follow. Can you share any code that you wrote that triggers this? Or, if there is code in one of our samples that triggers this, can you link to the relevant sample and line? Thanks in advance!

**Comment by kumarbhubnesh** [comment]
Hi @greg-db Please check above file for code which is causing crash. Thanks in advance.

**Comment by kumarbhubnesh** [comment]
[UploadFileTask.txt](https://github.com/dropbox/dropbox-sdk-java/files/1370623/UploadFileTask.txt)
@greg-db This is the file from your sample which triggers it.

**Comment by greg-db** [comment]
@kumarbhubnesh Thanks! I just tried uploading a file using [the Android example app](https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android) that [uses](https://github.com/dropbox/dropbox-sdk-java/blob/7ecc15cf0f51d6ae2ba5cdb334aac2c2f3474b87/examples/android/src/main/java/com/dropbox/core/examples/android/FilesActivity.java#L251) [`UploadFileTask`](https://github.com/dropbox/dropbox-sdk-java/blob/7ecc15cf0f51d6ae2ba5cdb334aac2c2f3474b87/examples/android/src/main/java/com/dropbox/core/examples/android/UploadFileTask.java#L20) on Android 7.0 though and it didn't reproduce that crash. 

Can you share some more specific steps for reproducing this? Thanks in advance!

**Comment by kumarbhubnesh** [comment]
@greg-db Ok let me check that sample again,.

**Comment by nicolabeghin** [comment]
Any update on this?

**Comment by greg-db** [comment]
@nicolabeghin I don't have an update on this. Are you seeing this issue as well? We have not been able to reproduce it. If you can, please share the code and steps to do so. Thanks!

**Comment by nicolabeghin** [comment]
Hi @greg-db I just used the de-facto standard `aFileChooser` and just selected a file from the Dropbox app. I can confirm the `_data` column is not available, therefore throwing an exception at https://github.com/iPaulPro/aFileChooser/blob/master/aFileChooser/src/com/ipaulpro/afilechooser/utils/FileUtils.java#L330

Maybe your `UploadFileTask` is not crashing because you're uploading a file and not selecting one?

![image](https://user-images.githubusercontent.com/2743637/33579172-bd8e01be-d940-11e7-94cb-7406dbb56751.png)

**Comment by greg-db** [comment]
@nicolabeghin I see, thank you. Based on this, I see that this error is actually more about interacting with the official Dropbox Android app (com.dropbox.android) and not the Dropbox API itself. I can only provide support for the Dropbox API part though.

Please open this is as [a ticket here](https://www.dropbox.com/developers/contact) with these details and I'll redirect that to the right people. Thanks!

**Comment by HBiSoft** [comment]
@nicolabeghin Did you resolve this? If you did, do you mind sharing? Thank you.

**Comment by nicolabeghin** [comment]
@HBiSoft if I'm not wrong I changed in aFileChooser to handle all files as "to be downloaded" like below. Not pretty if you ask me, but had no time to deep dive in this.

```
public static boolean isCloudFile(Uri uri) {
        return "content".equalsIgnoreCase(uri.getScheme());
    }
```

**Comment by HBiSoft** [comment]
@nicolabeghin So I can just change 

https://github.com/iPaulPro/aFileChooser/blob/master/aFileChooser/src/com/ipaulpro/afilechooser/utils/FileUtils.java#L330

This - 

    // MediaStore (and general)
    else if ("content".equalsIgnoreCase(uri.getScheme())) {

        // Return the remote address
        if (isGooglePhotosUri(uri))
            return uri.getLastPathSegment();

        return getDataColumn(context, uri, null, null);
    }

To this - 

    // MediaStore (and general)
    else if ("content".equalsIgnoreCase(uri.getScheme())) {
        Cursor cursor = getContentResolver().query(uri, null, null, null, null);
        int nameIndex = cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME);
        int sizeIndex = cursor.getColumnIndex(OpenableColumns.SIZE);
        cursor.moveToFirst();
        String filename = cursor.getString(nameIndex);
        long filesize = cursor.getLong(sizeIndex);
        InputStream is = getContentResolver().openInputStream(uri);
        File downloadedCloudFile = new 
        File(downloads_folder, filename);
        if (downloadedCloudFile.exists()) {
            downloadedCloudFile.delete();
        }
        FileOutputStream out = new FileOutputStream(downloadedCloudFile);
        IOUtils.copy(is, out);
        return downloadedCloudFile.getAbsolutePath();
    }

As you mentioned here - https://github.com/iPaulPro/aFileChooser/issues/85
