### ISSUE TITLE
OKHTTP header error

### ISSUE THREAD

**Issue by qmetzler-luna** [dropbox/dropbox-sdk-java#157]
Using the 3.0.4 version of the sdk my user got an exception while trying to sync :

10-06 22:22:07.579  3030  4055 W System.err: java.lang.IllegalArgumentException: Unexpected char 0x41f at 0 in User-Agent value: Приложение/4.0.5 OfficialDropboxJavaSDKv2/3.0.4
10-06 22:22:07.580  3030  4055 W System.err: 	at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:320)
10-06 22:22:07.580  3030  4055 W System.err: 	at okhttp3.Headers$Builder.add(Headers.java:270)
10-06 22:22:07.580  3030  4055 W System.err: 	at okhttp3.Request$Builder.addHeader(Request.java:176)
10-06 22:22:07.580  3030  4055 W System.err: 	at com.dropbox.core.http.OkHttp3Requestor.toOkHttpHeaders(OkHttp3Requestor.java:156)
10-06 22:22:07.580  3030  4055 W System.err: 	at com.dropbox.core.http.OkHttp3Requestor.startUpload(OkHttp3Requestor.java:150)
10-06 22:22:07.580  3030  4055 W System.err: 	at com.dropbox.core.http.OkHttp3Requestor.startPost(OkHttp3Requestor.java:139)
10-06 22:22:07.580  3030  4055 W System.err: 	at com.dropbox.core.DbxRequestUtil.startPostRaw(DbxRequestUtil.java:237)
10-06 22:22:07.580  3030  4055 W System.err: 	at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:107)
10-06 22:22:07.580  3030  4055 W System.err: 	at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(DbxRawClientV2.java:284)
10-06 22:22:07.580  3030  4055 W System.err: 	at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(DbxRawClientV2.java:102)
10-06 22:22:07.580  3030  4055 W System.err: 	at com.dropbox.core.v2.files.DbxUserFilesRequests.listFolder(DbxUserFilesRequests.java:1335)
10-06 22:22:07.580  3030  4055 W System.err: 	at com.dropbox.core.v2.files.ListFolderBuilder.start(ListFolderBuilder.java:143)

It seems related to the language not being supported for http header https://github.com/square/okhttp/issues/2896
Is it something you should fix or I should fix in my app?

**Comment by cakoose** [comment]
It looks like you're setting "Приложение/4.0.5" as the "clientIdentifier" when constructing the `DbxRequestConfig` instance.  The Dropbox SDK puts this value in the `User-Agent` header of every request.

Unfortunately, HTTP headers use the [ISO-8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), which can't represent "Приложение/4.0.5".  ISO-8859-1 is a superset of ASCII with 128 additional characters (enough to support Spanish, German, and a few others), but it doesn't handle all of Unicode and doesn't handle Cyrillic.

Additionally, recent versions of the HTTP spec strongly discourage using anything other than ASCII, and OkHttp has issues with non-ASCII.

I think your best option is to change your "clientIdentifier" to be an ASCII-only string.

**Comment by qmetzler-luna** [comment]
Thank you for the the answer. I've fixed it in my app.
