### ISSUE TITLE
How to authenticate multiple accounts in app without checking account‘s password again

### ISSUE THREAD

**Issue by yangjieK** [dropbox/dropbox-sdk-java#160]
I create  a app Dropbox API.

I have about@123.com and run@123.com accounts. and authenticate them with one by one. 

I log in " about@123.com " 
![device-2017-10-13-113539_](https://user-images.githubusercontent.com/4345445/31529309-fb0faa9c-b00a-11e7-82cf-1f3cce0b23bf.png)

**My question is that When I switch to run@123.com account, how can I authenticate  run@123.com without its password ?** 
The following steps
1) log out " about@123.com " .  I call `tokenRevoke()`

![device-2017-10-13-113934_](https://user-images.githubusercontent.com/4345445/31529359-6619b3f0-b00b-11e7-8ffc-cfb22d9dc217.png)

2) switch run@123.com account, and login wtih dropbox, then the website url links to the about@123.com account,so I need logout about@123.com in website to input password and name again.

## **The question: how to authenticate  in run@123.com without input password.**
![device-2017-10-13-114724_](https://user-images.githubusercontent.com/4345445/31529676-350a644c-b00d-11e7-925d-fae54d90eb96.png)

(Note: Both about@123.com and run@123.com were  authenticated  a few hours ago)

**Comment by cakoose** [comment]
To keep access to both accounts, do not call `tokenRevoke()`.  Just keep track of the access token and pass that in when you create `DbxClientV2`.

**Comment by yangjieK** [comment]
@cakoose 

> To keep access to both accounts, do not call tokenRevoke(). Just keep track of the access token and pass that in when you create DbxClientV2.

Will The access token never be changed if I don't tokenRevoke it?

**Comment by cakoose** [comment]
By default, the token is valid for years.  However, the user can choose to invalidate the token using this page: https://www.dropbox.com/account/connected_apps

If the token expires or the user invalidates the token, when you try to make an API call with that token, you'll get an [`InvalidAccessTokenException`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/InvalidAccessTokenException.html).  At that point you can ask the user if they want to re-auth.

**Comment by yangjieK** [comment]
@cakoose 
thanks,I got this

**Comment by yangjieK** [comment]
@cakoose I try to keep track of the access token  between run@123.com and about@123.com. Their token are different. When I switch to about@123.com account and recreate a new client with its token, load `mDbxClient.users().getCurrentAccount()`  info is run@123.com? 

So i try to slove it again.
1. `Auth.startOAuth2Authentication(UserActivity.this, getString(R.string.app_key))` and use about@123.com authenticate

2. load mDbxClient.users().getCurrentAccount() still be run@123.com

**Comment by greg-db** [comment]
You'll need a client for the new access token. Are you using `DropboxClientFactory` though? If so, be careful because that will re-use the old token. You'll need to throw that away and re-initialize it. There's some more information on that here:

https://github.com/dropbox/dropbox-sdk-java/issues/92#issuecomment-280002810

**Comment by yangjieK** [comment]
I got it. and it works , the following step

1. set Client null
2. clear sharepreference token null
3.login other account and authenicate 
(Note don't call tokenRevoke)
