### ISSUE TITLE
Android: Auth.getOAuth2Token() returns null from browser

### ISSUE THREAD

**Issue by g-martins** [dropbox/dropbox-sdk-java#161]
I'm trying to get the token but it seems that it only works when I have the dropbox app installed on the device.

SDK version 3.0.5

**Comment by g-martins** [comment]
Ok, the app key on AndroidManifest was missing the **db-** at the beginning.

**Comment by lbarrosop** [comment]
Hello  I have the same problem, however if I add the db- at the beginning on my manifest it opens a dialog that prevents any other authentication...I'm using V2 api

**Comment by greg-db** [comment]
@lbarrosop The `db-` is required for the custom URL scheme [as shown in the example](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/AndroidManifest.xml#L32).

Can you elaborate on the issue you're seeing? Please share the code and steps to reproduce the issue, as well as a screenshot of the dialog you're referring to.
