### ISSUE TITLE
Creating a folder in a subfolder with an ID

### ISSUE THREAD

**Issue by dAti-zz** [dropbox/dropbox-sdk-java#164]
Hello,

Is there any possibility to create a folder in a subfolder without specifying a path but just a subfolder ID  + name ? 
Also is it possible to know the path when specifying only the folderID ?

Thanks in advance,

David

**Comment by greg-db** [comment]
The `createFolder` functionality unfortunately doesn't accept ID-relative paths like that, but I'll pass this along as a feature request. 

You can get the metadata for any file or folder just from its ID though, using [`getMetadata`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#getMetadata-java.lang.String-) though.

**Comment by dAti** [comment]
Thanks for the quick reply !

**Comment by handstandsam** [comment]
I'm going to close this issue as a response was provided.
