### ISSUE TITLE
ListSharedLinksResult listSharedLinks(ListSharedLinksArg arg) is not public

### ISSUE THREAD

**Issue by leosabbir** [dropbox/dropbox-sdk-java#167]
ListSharedLinksResult listSharedLinks(ListSharedLinksArg arg) is not public method. How can one retrieve more shared links if there are more left?

**Comment by greg-db** [comment]
You can use [`listSharedLinksBuilder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/sharing/DbxUserSharingRequests.html#listSharedLinksBuilder--) to get a [`ListSharedLinksBuilder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/sharing/ListSharedLinksBuilder.html), on which you can use [`withCursor`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/sharing/ListSharedLinksBuilder.html#withCursor-java.lang.String-) before [`start`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/sharing/ListSharedLinksBuilder.html#start--)ing the call.
