### ISSUE TITLE
Exceptions occurs when migrate Dropbox v1 code to V2 in Android

### ISSUE THREAD

**Issue by Trainingnga** [dropbox/dropbox-sdk-java#168]
1 . exception occur while uploading: com.dropbox.core.BadRequestException: HTTP header "Dropbox-API-User-Locale": Malformed RFC 5646 language tag: "azkw4rf2bxhewjw": The first group contains digits: "azkw4rf2bxhewjw". -----why this exception occur?
2.  please provide me clear steps in Android App to use dropbox api v2 in existing code of Dropbox api v1(because I have done changes in existing code of V1 but it's not working).

**Comment by greg-db** [comment]
1. The exception indicates that the SDK received an invalid language tag for the locale. Are you calling `withUserLocale`? If so, make sure you supply a valid value. Currently, the SDK is receiving  "azkw4rf2bxhewjw", which is not valid.

2. There's an example Android app using the Dropbox API v2 Java SDK here:

https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android

Your AndroidManifest.xml should be set up as shown here:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/AndroidManifest.xml#L33

You start the flow by calling startOAuth2Authentication as shown here:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/UserActivity.java#L36

You complete the flow by calling getOAuth2Token as shown here:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/DropboxActivity.java#L22

Your app can store and re-use the resulting access token for that user, as the example does here:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/DropboxActivity.java#L24

Once you have an access token, you can make a client as shown here:

https://github.com/dropbox/dropbox-sdk-java/blob/395d463840778b4c6ec730aef82b0a9dbee10f8e/examples/android/src/main/java/com/dropbox/core/examples/android/DropboxClientFactory.java#L21

With a client, you can make whatever calls you want, as shown in the readme and examples:

https://github.com/dropbox/dropbox-sdk-java/blob/master/ReadMe.md#try-some-api-requests

If you need more time to migrate your app to API v2, we can offer an extension for access to API v1. Please share the app key(s) that needs extended access and we'll get that set up for you.
