### ISSUE TITLE
Download Folder with API V2 [ Not file , i need to download folder/s]

### ISSUE THREAD

**Issue by goxr3plus** [dropbox/dropbox-sdk-java#170]
I know how to download a File and get also the progress , but **i don't know how to do it for a Folder .
For example on the DropBox website when you click to download a folder , it downloads it as a .zip .** How this can be done ? I CAN'T FIND NO WHERE AN EXAMPLE OF THIS :) please some help .

So downloading a File with the API V2 is pretty easy like : 

``` JAVA
/**
 * Download Dropbox File to Local Computer
 * 
 * @param client
 *            Current connected client
 * @param dropBoxFilePath
 *            The file path on the Dropbox cloud server -> [/foldername/something.txt]
 * @param localFileAbsolutePath
 *            The absolute file path of the File on the Local File System
 * @throws DbxException
 * @throws DownloadErrorException
 * @throws IOException
 */
 public void downloadFile(DbxClientV2 client , String dropBoxFilePath , String localFileAbsolutePath) throws DownloadErrorException , DbxException , IOException {
				
	//Create DbxDownloader
	DbxDownloader<FileMetadata> dl = client.files().download(dropBoxFilePath);
				
	//FileOutputStream
	FileOutputStream fOut = new FileOutputStream(localFileAbsolutePath);
	System.out.println("Downloading .... " + dropBoxFilePath);
				
				
	//Add a progress Listener
	dl.download(new ProgressOutputStream(fOut, dl.getResult().getSize(), (long completed , long totalSize) -> {

		System.out.println( ( completed * 100 ) / totalSize + " %");
					
	}));
				
				
}
```

where ```ProgressOutputStream``` is the below : 

``` JAVA
import java.io.IOException;
import java.io.OutputStream;

/**
 * Used to track progress of OutputStream User 
 * 
 * @author GOXR3PLUS
 *
 */
public class ProgressOutputStream extends OutputStream {
	
	private OutputStream underlying;
	private Listener listener;
	private int completed;
	private long totalSize;
	
	public ProgressOutputStream(OutputStream underlying, long totalSize, Listener listener) {
		this.underlying = underlying;
		this.listener = listener;
		this.completed = 0;
		this.totalSize = totalSize;
	}
	
	@Override
	public void write(byte[] data , int off , int len) throws IOException {
		this.underlying.write(data, off, len);
		track(len);
	}
	
	@Override
	public void write(byte[] data) throws IOException {
		this.underlying.write(data);
		track(data.length);
	}
	
	@Override
	public void write(int c) {
		try {
			this.underlying.write(c);
			track(1);
		} catch (IOException e) {
			e.printStackTrace();
		}
		
	}
	
	private void track(int len) {
		this.completed += len;
		this.listener.progress(this.completed, this.totalSize);
	}
	
	/**
	 * The total File size
	 * 
	 * @return the totalSize The total File size
	 */
	public long getTotalSize() {
		return totalSize;
	}
	
	public interface Listener {
		public void progress(long completed , long totalSize);
	}
}

```

**Comment by greg-db** [comment]
The Dropbox API doesn't offer the ability to download entire folders as zips, but I'll pass this along as a feature request. That being the case, you'll need to loop through the desired files and download each one.

**Comment by greg-db** [comment]
The API now offers the ability to download folders as zips. In the Java SDK, you can use the `downloadZip` method:

https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#downloadZip-java.lang.String-

**Comment by goxr3plus** [comment]
Just a question i have here , i am using the code mentioned above in `ProgressOutputStream ` and i need to know the total size of the final zip folder , how can i retrieve it :) ?

**Comment by goxr3plus** [comment]
And please can you implement **DownloadProgress** and **UploadProgress** , it's been 1 year , is it so difficult for your team guys ? For example use the **DownloadProgress** code i gave you above . It is VERY FRUSTRATING NOT HAVING IT GUYS ...

**Comment by greg-db** [comment]
@goxr3plus The `downloadZip` method doesn't offer a way to retrieve the final zip size unfortunately, but I'll pass this along as a feature request. 

I see you also opened #192 about the progress request, so I'll follow up there.

**Comment by rahuldn** [comment]
Hi sir, can you share the source code for downloading a file from Dropbox.

**Comment by rahuldn** [comment]
@goxr3plus 
Sir can you share the source code for downloading a file from Dropbox to Android studio..
Please sir! It's a humble request!

**Comment by rahuldn** [comment]
@goxr3plus
I couldn't find it anywhere!! API v2..!! I read your comment.. so could you share source code with me!

**Comment by rahuldn** [comment]
Thank you 😊@goxr3plus

**Comment by rahuldn** [comment]
I couldn't find it @goxr3plus

**Comment by greg-db** [comment]
@rahuldn You can find a basic example of using the Dropbox API v2 Java SDK to download a file via [the `download` method](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#download-java.lang.String-) here:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/tutorial/src/main/java/com/dropbox/core/examples/tutorial/Main.java#L54

**Comment by greg-db** [comment]
@rahuldn [The sample I linked to in my previous comment](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/tutorial/src/main/java/com/dropbox/core/examples/tutorial/Main.java#L54) is a complete example of downloading a file. Does that not cover what you need?
