### ISSUE TITLE
a error I think is not supposed to appear

### ISSUE THREAD

**Issue by yufengvac** [dropbox/dropbox-sdk-java#173]
public static String getOAuth2Token() {
        Intent data = AuthActivity.result;

        if (data == null) {
            return null;
        }

        String token = data.getStringExtra(AuthActivity.EXTRA_ACCESS_TOKEN);
        String secret = data.getStringExtra(AuthActivity.EXTRA_ACCESS_SECRET);
        String uid = data.getStringExtra(AuthActivity.EXTRA_UID);

        if (token != null && !token.equals("") &&
                secret != null && !secret.equals("") &&
                uid != null && !uid.equals("")) {
            return secret;
        }

        return null;
}
  getOAuth2Token but return secret???

**Comment by greg-db** [comment]
I'm afraid I don't follow. Can you clarify exactly what isn't working as expected? Please include steps to reproduce the issue and the unexpected output. (Be sure to redact any access token itself though.) Thanks in advance!

**Comment by jiuyangzhao** [comment]
@yufengvac Hey sorry for the confusing in naming. But in OAuth2 we don't have access_token_secret any more. The secret we return here is exactly the OAuth2 access_token.
