### ISSUE TITLE
ProGuard - Can't find referenced class javax.servlet.http.HttpSession

### ISSUE THREAD

**Issue by chrisonline** [dropbox/dropbox-sdk-java#174]
I use ProGuard and don't have added extra lines to my ProGuard file for DropBox because of this info:
https://github.com/dropbox/dropbox-sdk-java#does-this-sdk-require-any-special-proguard-rules-for-shrink-optimizations

But If I try to create the APK I get this error:
com.dropbox.core.DbxStandardSessionStore: can't find referenced class javax.servlet.http.HttpSession

So it seems I need extra lines in my ProGuard, but why are this extra lines not added by the library?

**Comment by greg-db** [comment]
Thanks for the report. To clarify, does your app work if you do add [the directives from the documentation](https://github.com/dropbox/dropbox-sdk-java#does-this-sdk-require-any-special-proguard-rules-for-shrink-optimizations)?

**Comment by chrisonline** [comment]
Yes if I will add "-dontwarn javax.servlet.**" it is working.

**Comment by greg-db** [comment]
Thanks for confirming that! I'll send this along to the team as a request to automatically add these, if possible.
