### ISSUE TITLE
Can't upload my file!

### ISSUE THREAD

**Issue by Lakshamana** [dropbox/dropbox-sdk-java#176]
Hi there! I'm using the example code from this repository, and I've got an error in upload a tiny file to dropbox. The error message is:

`com.dropbox.core.v2.files.UploadErrorException: Exception in 2/files/upload: {".tag":"path","reason":{".tag":"conflict","conflict":"file_ancestor"},"upload_session_id":"AAAAAAAAAPOCp779j-S9nQ"}
	at com.dropbox.core.v2.files.UploadUploader.newException(UploadUploader.java:37)
	at com.dropbox.core.v2.files.UploadUploader.newException(UploadUploader.java:23)
	at com.dropbox.core.DbxUploader.finish(DbxUploader.java:225)
	at com.dropbox.core.DbxUploader.uploadAndFinish(DbxUploader.java:106)
	at com.dropbox.core.v2.DbxUploadStyleBuilder.uploadAndFinish(DbxUploadStyleBuilder.java:92)`

And the line which does the upload is:

`.uploadAndFinish(in);`

Whole method code:

`private static void uploadFile(DbxClientV2 dbxClient, File localFile, String dropboxPath) {
        try (InputStream in = new FileInputStream(localFile)) {
            FileMetadata metadata = dbxClient.files().uploadBuilder(dropboxPath)
                .withMode(WriteMode.ADD)
                .withClientModified(new Date(localFile.lastModified()))
                .uploadAndFinish(in);

            System.out.println(metadata.toStringMultiline());
        } catch (UploadErrorException ex) {
            System.err.println("Erro 1 em upload para o Dropbox: " + ex.getMessage());
            ex.printStackTrace();
            System.exit(1);
        } catch (DbxException ex) {
            System.err.println("Erro 2 em upload para o Dropbox: " + ex.getMessage());
            System.exit(1);
        } catch (IOException ex) {
            System.err.println("Erro 1 lendo arquivo \"" + localFile + "\": " + ex.getMessage());
            System.exit(1);
        }
    }`

PS: I could not do the well-formatting int this issue, sorry =)

**Comment by jiuyangzhao** [comment]
Hi @Lakshamana 

According to [document](https://www.dropbox.com/developers/documentation/http/documentation#files-upload).

conflict means: Couldn't write to the target path because there was something in the way.
file_ancestor.
file_ancestor means: There's a file at an ancestor path, so we couldn't create the required parent folders.

So you can either change the path to upload or delete that ancestor file causing conflict to make it go though.

**Comment by Lakshamana** [comment]
Thank you (a lot) jiuyangzhao, now it works fine!

2018-01-17 11:23 GMT-03:00 jiuyangzhao <notifications@github.com>:
