### ISSUE TITLE
Share link url not getting android

### ISSUE THREAD

**Issue by adityaflexsin** [dropbox/dropbox-sdk-java#185]
Hi I am using this code for get dropbox share link url but this not woking.
list size return 0
please resolve this issue  
 @Override
    protected String doInBackground(String... params) {
        String url = null;
        try {
            ListSharedLinksResult sharedLinkMetadata = mDbxClient.sharing().listSharedLinksBuilder().withPath(mFileName).withDirectOnly(true).start();
            List<SharedLinkMetadata> list = sharedLinkMetadata.getLinks();
            if (list != null && list.size() > 0) {
                url = list.get(0).getUrl();
            }
        } catch (CreateSharedLinkWithSettingsErrorException ex) {
            mException = ex;

        } catch (SharedLinkErrorException ex) {
            mException = ex;

        } catch (DbxException ex) {
            mException = ex;
        }
        return url;
    }

**Comment by greg-db** [comment]
You're using `listSharedLinksBuilder` for a particular path with `withDirectOnly` set to `true`. This will only return shared links that already exist for that exact path. If none exists, you'll get an empty list like you posted.

If you're looking for a parent shared link, set `withDirectOnly` to `false`.

If you want to create a shared link, use [`createSharedLinkWithSettings`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/sharing/DbxUserSharingRequests.html#createSharedLinkWithSettings-java.lang.String-com.dropbox.core.v2.sharing.SharedLinkSettings-) instead.

Also, note that in this code you're catching `CreateSharedLinkWithSettingsErrorException` which would apply to [`createSharedLinkWithSettings`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/sharing/DbxUserSharingRequests.html#createSharedLinkWithSettings-java.lang.String-com.dropbox.core.v2.sharing.SharedLinkSettings-), not `listSharedLinksBuilder`.

**Comment by adityaflexsin** [comment]
Hello Greg,
createSharedLinkWithSettings working for first time and  second time same file share the issue
Exception in 2/sharing/create_shared_link_with_settings: "shared_link_already_exists"
Please help for this issue also.

**Comment by greg-db** [comment]
If you call `createSharedLinkWithSettings` for a file for which there is already a shared link, it will fail with `shared_link_already_exists`. When you get that, you should use `listSharedLinksBuilder` to get the existing link.
