### ISSUE TITLE
Can't resolve captcha, maybe wrong authorization URL

### ISSUE THREAD

**Issue by kschroeer** [dropbox/dropbox-sdk-java#188]
I've the following situation: I want to give the user the possibility to authorizing my application to access the own Dropbox account.
For this purpose I'm using the official Dropbox SDK. The process itself takes place in a webview (SWT Browser) with a Jetty server running for redirect and getting the access token.

The authorization url which is generated by the SDK and which I show in the webview looks like this (I hide state and client_id in the example below):

https://www.dropbox.com/oauth2/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fdropbox-auth-finish&state=???&client_id=???

The first thing I'm wondering about is that my webview shows up the login form and also a recaptcha frame. If I'm using a "normal" browser and navigate the same url, there's no captcha displayed.

And the second problem is that the captcha can't be resolved. If I click the right graphics and press "Send" nothing happens. It's the same issue on Windows and macOS.

**Comment by greg-db** [comment]
"SWT Browser" isn't [officially supported by the Dropbox web site](https://www.dropbox.com/help/desktop-web/system-requirements#web) unfortunately, so I'm afraid it will be susceptible to web site issues like this, and we won't be able to offer fixes for it. That being the case, please update your app to use the system browser.

**Comment by kschroeer** [comment]
I think you confuse something: SWT is not a browser. It's a widget which always wraps the standard system browser.
So you can reproduce the problem for example by using Internet Explorer under Windows or Safari under macOS. That's why I opened this issue.
With Firefox, Chrome or Opera there's no error.

**Comment by greg-db** [comment]
So, to clarify, have you been able to reproduce this issue using the system Internet Explorer under Windows or Safari under macOS? If so, please share the specific version numbers of the browsers you've seen this so we can try to replicate it. Thanks!

By the way though, you should process the OAuth app authorization flow in the system browser, not embedded in a web view anyway, per [the OAuth 2 documentation](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize).
