### ISSUE TITLE
how to get the file downloading/uploading progres

### ISSUE THREAD

**Issue by kbboss** [dropbox/dropbox-sdk-java#189]
for a long time, how to get the file downloading/uploading progress

**Comment by greg-db** [comment]
The API v2 Java SDK doesn't offer download/upload progress listeners, but this is open as a feature request. This is a duplicate of #66.

**Comment by kbboss** [comment]
@greg-db  how about now . Does sdk support it?

**Comment by greg-db** [comment]
This is planned for the next release. Please refer to #66 for more information.
