### ISSUE TITLE
Usage in OSGi Subsystems: Require-Capability

### ISSUE THREAD

**Issue by dritter-hd** [dropbox/dropbox-sdk-java#19]
Hello,

the dropbox sdk java currently uses the "maven-bundle-plugin", which automatically generates an OSGi-Subsystem compatible "Require-Capability" that expresses the base JRE requirement of the bundle: Require-Capability: "osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))".

When using an OSGi container, e.g., equinox >= v3.8.2 + aries.subsystem, and packaging the dropbox sdk java bundle into a subsystem on a more recent JRE, the subsystem cannot start because of the (outdated?) required JRE capability.

Hence, to make the bundle usable in an OSGi subsystem either the required JRE version will be updated or through an additional BND instruction in the "maven-bundle-plugin", which prevents the plugin to generate the "Require-Capability".
...
    \<extensions>true\</extensions>
    \<configuration>
        \<instructions><_noee>true</_noee>\</instructions>
    \</configuration>
...

If you like, I can as well provide a pull request for that.

Best Regards,
Daniel

**Comment by cakoose** [comment]
I don't know anything about OSGi.  But go ahead and make a pull request so I can understand exactly what you're trying to do.  And maybe the person who contributed the original OSGi support (@manuelh9r) can take a look at it as well.

**Comment by dritter-hd** [comment]
Pull request created https://github.com/dropbox/dropbox-sdk-java/pull/20 and @manuelh9r informed.
