### ISSUE TITLE
Upload with OkHttp3Requestor can upload corrupt file when switching network from 4G to 3G.

### ISSUE THREAD

**Issue by jiuyangzhao** [dropbox/dropbox-sdk-java#191]
https://stackoverflow.com/questions/50485684/reduced-file-size-when-uploading-files-using-dropbox-core-api-v2

It seems like during we upload a file, if an in coming call forced us to switch from 4G to 3G, client(SDK) will receive an error and a corrupted file will still get uploaded to Dropbox finally.

Correct Behavior 1: File should not be uploaded.
Correct Behavior 2: Upload should not be interrupted.

**Comment by cakoose** [comment]
@jiuyangzhao: Do you know what the bug is?  Were you able to reproduce it?

**Comment by justapps4u** [comment]
This bug can be easily reproduced. Try uploading a large file (atleast 500 KB) using uploadBuilder() on 4G network. Call this in serial order (3-4 times) each time making changes to the file. Now, switch network from 4G to 3G (an incoming call does that). Upload fails but a file with size can be seen on Dropbox.

**Comment by greg-db** [comment]
@justapps4u Thanks for your patience. Unfortunately, we can't seem to reproduce this behavior using the steps you described. Can you supply a sample project that reproduces this issue? Thanks in advance, and apologies for the bother.

**Comment by eyousefi** [comment]
Fixed in v5.0.0, https://github.com/dropbox/dropbox-sdk-java/commit/13c082348891f87f312ae01335c1b4e22d0ea2bc
