### ISSUE TITLE
Check if File|Folder is starred or use API V2 to star File|Folder

### ISSUE THREAD

**Issue by goxr3plus** [dropbox/dropbox-sdk-java#195]
After long search on the web i am curious to know if this can be done with the current dropbox-sdk-java ? 

I mean check which files are starred or star new files.

I have checked discussion like [this](https://www.dropboxforum.com/t5/Photos-and-videos/Selecting-all-starred-photos/td-p/256114/page/3) and [this ](https://www.dropboxforum.com/t5/Sharing-and-collaboration/Starred-Folders/td-p/270898)
![screenshot_1](https://user-images.githubusercontent.com/20374208/42977162-3d75b0d0-8bce-11e8-8e06-8db4ef30eea6.jpg)

Waiting for your kind response :)

**Comment by greg-db** [comment]
The Dropbox API unfortunately doesn't offer the ability to get starred files or star new files, but I'll pass this along as a feature request.

**Comment by goxr3plus** [comment]
Thank you boss :)

**Comment by handstandsam** [comment]
An answer was provided, so I'm going to close out this issue.  Please re-open if more information is needed.  Thanks!
