### ISSUE TITLE
No Api to support resumed download ,just like chuncked upload?

### ISSUE THREAD

**Issue by kbboss** [dropbox/dropbox-sdk-java#200]
hello, Dropbox can support chunck upload ,but I don't found api about resumed download.
So does dropbox support it?

**Comment by greg-db** [comment]
You can do this by downloading specific portions of files using `DbxDownloadStyleBuilder.range`:

https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/DbxDownloadStyleBuilder.html#range-long-
