### ISSUE TITLE
Next release date? 

### ISSUE THREAD

**Issue by goxr3plus** [dropbox/dropbox-sdk-java#201]
Can we know the next release date :) ?

**Comment by goxr3plus** [comment]
@greg-db  Thanks i am asking because i see they have added (download and upload ) progress listeners and i am crying from happiness , please also add like two examples on how to user them with simple files and zip folders :) 

Much love Greg please release assap.

**Comment by greg-db** [comment]
@goxr3plus We've released [v3.0.9](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v3.0.9). Hope this helps!

**Comment by goxr3plus** [comment]
Yes saw it i love you :) How to add it on the download and upload of a file
or folder? I mean can we have simple examples?


Also can we use it for ZipFolder download to track the progress :)?

**Comment by greg-db** [comment]
@goxr3plus There's an example of using it with an upload here:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/upload-file/src/main/java/com/dropbox/core/examples/upload_file/Main.java#L50

It works the same way with file downloads; the `download` method optionally takes a `ProgressListener` parameter the same way.

This doesn't work for zip folder downloads though unfortunately. For the sake of performance, the zips are created 'on the fly', which means the total size isn't known during the transfer, so we can't report progress as a percent of the total.

**Comment by goxr3plus** [comment]
@greg-db  Hm would be great to find a work around for ZIPs ... hm ... so when you say it happens on the fly .... like it doesn't add all the files to the archieve and then sending ?

Can you suggest a work around technique and i will write code about it and pull request :)

**Comment by greg-db** [comment]
@goxr3plus Unfortunately I can't think of a workaround. The zip file isn't complete when the server begins streaming the zip content in the HTTPS response body, so there isn't a way to code around this client-side. You can see how many bytes have been transferred so far, but you can't know how many more there are to go, since the server doesn't even know.
