### ISSUE TITLE
Error in file upload to a folder id using DbxClientV2

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#207]
Hi 

i am trying to upload a dummy input stream to a folder id of dropbox using the SDK ,but its giving me  the error. I passed the parent folder id in format **id:-MEeLvbEJHAAAAAAAAAALg** as path value

Exception in 2/files/upload: {".tag":"path","reason":{".tag":"conflict","conflict":"folder"},"upload_session_id":"AAAAAAAAAPLIr-yqcKQXAQ"}

`public void uploadFile(String dropbBoxAccessToken, String pathInfo)
      throws UploadErrorException, IOException, DbxException {
    byte[] bytes = "asdf".getBytes("UTF8");
    ByteArrayInputStream bytestream = new ByteArrayInputStream(bytes);
  
    client = this.buildDropBoxApiClient(dropbBoxAccessToken);
     client.files().uploadBuilder("id:-MEeLvbEJHAAAAAAAAAALg").uploadAndFinish(bytestream);
  }`

**Comment by greg-db** [comment]
When uploading a file, you need to include the full file path and name or ID for the file itself. 

That means one of:
- the full desired file path and name (and extension, if any) of the file, e.g., "/folder/file.ext"
- the full file ID, e.g., "id:abcde123"
- the full ID of the parent folder and the desired file name (and extension, if any), e.g.,  "id:fghi456/filename.ext"

So, if `"id:-MEeLvbEJHAAAAAAAAAALg"` is the ID for a folder, you need to also include the file name, such as:
```
client = this.buildDropBoxApiClient(dropbBoxAccessToken);
 client.files().uploadBuilder("id:-MEeLvbEJHAAAAAAAAAALg/filename.ext").uploadAndFinish(bytestream);
```
