### ISSUE TITLE
Getting invalid_access_token

### ISSUE THREAD

**Issue by cherbin** [dropbox/dropbox-sdk-java#210]
Hello,

Our test user has went to the https://www.dropbox.com/oauth2/authorize/?client_id=....
page 

And has gotten "Enter this code into .. to finish the process"

We put this code in the ~/.dropbox_uploader
OAUTH_ACCESS_TOKEN=.......

And we get the following:
++ check_http_response
++ CODE=0
++ case $CODE in
++ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
+++ sed -n 's/{".tag": *"*\([^"]*\)"*.*/\1/p' /tmp/du_resp_debug
++ local 'TYPE={"error_summary": "invalid_access_token/", "error": invalid_access_token'

Do you know what is happening ?

**Comment by greg-db** [comment]
Based on the code you shared, it looks like you're actually using the third party "Dropbox Uploader" from https://github.com/andreafabrizi/Dropbox-Uploader, and not the official Dropbox API v2 Java SDK, for which you opened this issue.

We can't provide support for that script, as it's made by a third party. That said, it sounds like you're probably trying to use an "authorization code" in place of an "access token". These are two different things and cannot be used interchangeably. In short, it sounds like you're using [the "code" flow](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize), so you should exchange the authorization code for an access token using [/oauth2/token](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-token). (Or, if you have a redirect URI you can use, you can switch to using [the "token" flow](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize), which returns the access token directly.)

You can find information on how the OAuth flow works in [the OAuth Guide](https://www.dropbox.com/developers/reference/oauth-guide), as well as [the Dropbox authorization documentation](https://www.dropbox.com/developers/documentation/http/documentation#authorization).
