### ISSUE TITLE
Can i use dropbox api in Iran?

### ISSUE THREAD

**Issue by MkazemAkhgary** [dropbox/dropbox-sdk-java#214]
I live in iran. I wanted to know if i can use dropbox api and if it is not against terms of use

**Comment by greg-db** [comment]
You can find the terms for using Dropbox itself here:

https://www.dropbox.com/terms

And you can find the terms for the Dropbox API in particular here:

https://www.dropbox.com/developers/reference/tos

From a technical perspective, if the service is blocked in a particular country, that is outside of our control, so unfortunately we’re unable to offer advice or assistance.

From a legal perspective, I can't interpret the terms or offer legal advice. If you have any legal questions regarding your use of a service with respect to its terms, you may want to consult an attorney.
