### ISSUE TITLE
showing notification in dropbox when our api_app uploads a file to dropbox

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#216]
We have a use case , where we are uploading a file to dropbox using v2 sdk. We also want that whenever we push any file from our api_app to dropbox, a notification indicating a new file has been added should show up in the dropbox notification bar, so that user can get aware. Is this feasible through api's (like passing some config in upload api invocation ?). or is there some way to achieve the same ?

**Comment by greg-db** [comment]
If the user has the Dropbox desktop client installed, they will receive notifications of added/edited files, but that is subject to their own notifications setting. (That is, the user can turn that feature off on any computer.) 

Changed files will also show in the "Recent Files" section of the Dropbox desktop client tray window.
