### ISSUE TITLE
uploaded file gets uploaded in both home(in recent section) as well as the target folder id

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#217]
We are uploading a file using dropbox java sdk and while uploading we are giving the parent folder id as the parameter 
fileUploadFullPath = folderId.concat("/").concat(fileName);
client.files().uploadBuilder(fileUploadFullPath).withMode(WriteMode.ADD).uploadAndFinish(in);

The file gets successfully uploaded in the target folder location, but its listing also appears in the home i.e root folder in the "recents section". We dont want the listing on the home folder but only on the target folder , how can we achieve this ?

**Comment by greg-db** [comment]
No, there isn't a way to prevent files from showing in the recents list. That will show any files recently added/edited.
