### ISSUE TITLE
Api error when root namespace id changes when user leaves team 

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#227]
we are storing user's root namespace id in our DB and all the api call we make to dropbox is with namepsace root
client = new DbxClientV2(config, dropBoxAccesToken).withPathRoot(PathRoot.namespaceId(rootFolderInfo.getRootNamespaceId()));

Now when user leaves the group its namespace id will change and will the api call fail ?
if it fails , what is the  exception_type it will throw , 

like catch(DbxException ex){
          if(ex instanceof "exception_type"){
            }

**Comment by greg-db** [comment]
If the path root is incorrect, you'll get a [`PathRootError`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/common/PathRootError.html). You can check that error object to see specifically what is wrong. For instance, for an incorrect root namespace ID, [`PathRootError.isInvalidRoot`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/common/PathRootError.html#isInvalidRoot--) will be true, and you can retrieve the specific information using [`PathRootError.getInvalidRootValue`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/common/PathRootError.html#getInvalidRootValue--).
