### ISSUE TITLE
Dropbox-Api-Path-Root specifying with tag as root

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#228]
Hi we need to pass the value for the header Dropbox-Api-Path-Root in dropbox api calls
Dropbox-Api-Path-Root:  {".tag": "namespace_id", "namespace_id": "namespace_id"}

what if have done is client = 
new DbxClientV2(config, dropBoxAccesToken).withPathRoot(PathRoot.namespaceId(rootFolderInfo.getRootNamespaceId()));

does this snippet honor .tag value with "root" or with "namespace_id".
what changes we need to do if we need to honor .tag value to root instead of namespace_id in the sdk ?

**Comment by greg-db** [comment]
It sounds like you're looking for [`PathRoot.root`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/common/PathRoot.html#root-java.lang.String-) (in place of [`PathRoot.namespaceId`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/common/PathRoot.html#namespaceId-java.lang.String-)). 

Hope this helps!
