### ISSUE TITLE
max allowed file name length in upload api

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#229]
hi i am using v2 sdk and calling client.files().uploadBuilder(fileUploadFullPath).withMode(WriteMode.ADD).withAutorename(true).uploadAndFinish(signedDocStream);

in the fileUploadFullPath we specify it as "folderid/filename" . What is the max allowed length for the filename. i can see in some documents that its 260. but the api is failing even for 255 character length with {".tag":"path","reason":{".tag":"malformed_path","malformed_path":null},"upload_session_id":"AAAA

**Comment by greg-db** [comment]
The Dropbox API allows path components to be up to 255 characters long. If any particular path component (such as the last component, the filename itself) is longer than this, the call will fail with a `path/malformed_path` error. 

I'll ask the team to specifically document this.
