### ISSUE TITLE
how to get notification when a file is uploaded to dropbox via api_app

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#230]
we are uploading file to dropbox via v2 api and file gets successfully uploaded. but in the dropbox web ,in the notification bar it should also appear up as file has been added like something so that user gets aware. How to achieve this, i didnt find any api /setting for this ?

i am not using mute=true in upload api call

**Comment by greg-db** [comment]
[Cross-linking for reference: https://www.dropboxforum.com/t5/API-Support-Feedback/Getting-notification-when-a-file-is-uploaded-by-an-api-app-to-my/m-p/317316 ]

I see you also posted this on the forum so I'll follow up there, and this wouldn't be specific to the Java SDK in particular anyway.
