### ISSUE TITLE
extensions/trigger_file_notification api support in SDK

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#231]
Hi 

i got to know this endpoint https://api.dropboxapi.com/2/extensions/trigger_file_notification
is used to issue a notification for file upload , but on trying i am getting 500 internal server error , can i get the cURL request for this api , also is this api handler supported in SDK ?

**Comment by greg-db** [comment]
It sounds like you're referring to a private API endpoint. I don't have any documentation/examples to share for that, as it's private, and likewise it's not implemented in this public Java SDK. 

If you've been given access to this endpoint and have any questions about it, please refer to the documentation you should have been supplied for it, or reach out to your Dropbox contact for more information.
