### ISSUE TITLE
Uploading multiple files to dropbox in Zip format

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#234]
Hi 

we have a use case where we need to upload more than one file to dropbox in zip format. Is this supported in SDK ? , if so will the resulting zip file containing multiple files will have a single file id ?

currently for upload we are using this snippet,          

FileMetadata uploadedFileMetadata = client.files().uploadBuilder(fileUploadFullPath).withMode(WriteMode.ADD).withAutorename(true).uploadAndFinish(signedDocStream);

**Comment by greg-db** [comment]
Do you mean you want the result to remain as a zip file once on Dropbox? If you want to upload multiple files to Dropbox in a zip file, you should zip the files up locally, and then upload the resulting zip archive to Dropbox in a single file upload request (e.g., using `uploadBuilder`).

The result will be the zip committed to Dropbox as a single file, with a single file ID. You can then later download the zip file and unzip it locally.

If that's not the behavior you want, please clarify. Thanks!
