### ISSUE TITLE
upload in zip format 

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#235]
>>
you should zip the files up locally, and then upload the resulting zip archive to Dropbox in a single file upload request and then upload the resulting zip archive to Dropbox in a single file upload request 
<<

should i use any java library for this or dropbox SDK do provide any affordance. how to achieve club multiple files into a single a zip file i.e what i wanted to know
 if i am to upload two files onto a single dropbox zip path , what is the syntax i should follow
how to club two bytestream into a upload handler ?
A code snippet might help

**Comment by greg-db** [comment]
(It looks like this is a follow up to #234. For reference, you can comment on closed issues.)

The Dropbox SDK itself does not offer functionality for creating zip archives locally like this. I expect there are a number of third party libraries available in Java for doing so, but I can't recommend or support any in particular.

Once you have the data for the zip file, you can upload it using the Dropbox SDK just like any other file.

**Comment by cakoose** [comment]
@prashantharshi: The Dropbox SDK can upload files with either an `OutputStream`-based or `InputStream`-based interface.  See the two examples at the top of the page: https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/DbxUploader.html

(`DbxUploader` is what is returned from the `DbxClientV2.files().uploadBuilder()...start()`.)

The Java standard library has support for building a zip file and writing it to an `OutputStream`: https://stackoverflow.com/a/1091817/163832
