### ISSUE TITLE
Client not initialized

### ISSUE THREAD

**Issue by ghilbing** [dropbox/dropbox-sdk-java#238]
Hello everybody! I am trying to use this example and it works fine, but when I download a file the app crashes and it says Client not initialized. And I did a lot of debugging and I googled a lot and I cannot find the mistake.
Here is my github repository: https://github.com/ghilbing/ProbandoDropbox
If you can help me I will be really thankful.

**Comment by greg-db** [comment]
[Cross-linking for reference: https://stackoverflow.com/questions/55152076/unable-to-start-activity-java-lang-illegalstateexception-client-not-initialize ]

Can you share the full stack trace, as well as just the relevant snippet of code?

**Comment by ghilbing** [comment]
Thanks for your fast answer...
2019-03-13 15:06:29.620 18869-18869/? I/probandodropbo: Not late-enabling -Xcheck:jni (already on)
2019-03-13 15:06:29.681 18869-18869/? W/probandodropbo: Unexpected CPU variant for X86 using defaults: x86
2019-03-13 15:06:30.328 18869-18869/com.hilbing.probandodropbox W/probandodropbo: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
2019-03-13 15:06:30.330 18869-18869/com.hilbing.probandodropbox W/probandodropbo: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
2019-03-13 15:06:30.489 18869-18869/com.hilbing.probandodropbox D/AndroidRuntime: Shutting down VM
2019-03-13 15:06:30.497 18869-18869/com.hilbing.probandodropbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hilbing.probandodropbox, PID: 18869
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hilbing.probandodropbox/com.hilbing.probandodropbox.FilesActivity}: java.lang.IllegalStateException: Client not initialized.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Client not initialized.
        at com.hilbing.probandodropbox.DropboxClientFactory.getClient(DropboxClientFactory.java:24)
        at com.hilbing.probandodropbox.FilesActivity.onCreate(FilesActivity.java:70)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ghilbing** [comment]
this is the DropboxClientFactory class:
package com.hilbing.probandodropbox;

import com.dropbox.core.DbxRequestConfig;
import com.dropbox.core.http.OkHttp3Requestor;
import com.dropbox.core.v2.DbxClientV2;

public class DropboxClientFactory {

    private static DbxClientV2 sDbxClient;

    public static void init(String accessToken) {
        if (sDbxClient == null) {
           // DbxRequestConfig requestConfig = DbxRequestConfig.newBuilder("examples-v2-demo")
            DbxRequestConfig requestConfig = DbxRequestConfig.newBuilder("ExampleMarch")
                    .withHttpRequestor(new OkHttp3Requestor(OkHttp3Requestor.defaultOkHttpClient()))
                    .build();

            sDbxClient = new DbxClientV2(requestConfig, accessToken);
        }
    }

    public static DbxClientV2 getClient() {
        if (sDbxClient == null) {
            throw new IllegalStateException("Client not initialized.");
        }
        return sDbxClient;
    }

}

**Comment by ghilbing** [comment]
and MainActivity:

package com.hilbing.probandodropbox;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;

import com.dropbox.core.DbxException;
import com.dropbox.core.DbxRequestConfig;
import com.dropbox.core.android.Auth;
import com.dropbox.core.v2.DbxClientV2;
import com.dropbox.core.v2.users.FullAccount;

public class MainActivity extends AppCompatActivity {

    //private static final String ACCESS_TOKEN = "KIvEwbgLGjMAAAAAAAADOGqJXmEJexDNNzhzWiRFA3ZkqE9rSjR2Un1uG_xK2E7W";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Auth.startOAuth2Authentication(getApplicationContext(), getString(R.string.app_key));
        String ACCESS_TOKEN = Auth.getOAuth2Token();

        //Create Dropbox Client
        DbxRequestConfig config = DbxRequestConfig.newBuilder("ExampleMarch").build();
        DbxClientV2 client = new DbxClientV2(config, ACCESS_TOKEN);

        //Get current account info
        FullAccount account = null;
        try {
            account = client.users().getCurrentAccount();
        } catch (DbxException e) {
            e.printStackTrace();
        }
        Log.d("Account", account.getName().getDisplayName());

    }
}

**Comment by greg-db** [comment]
Thanks! I see that your app is based on [the Dropbox Java SDK sample app](https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android), but you've modified it somewhat. It looks like you're gotten the authorization flow and client initialization into a bad state in the process. (You should probably also uninstall and re-install the app too, to clear any bad state in the installed app itself.)

I recommend reverting to the original sample code to get it working again.

For example, you have the `getOAuth2Token` call immediately following the `startOAuth2Authentication` call. That's not the correct flow however, as the user needs to authorize the app in between those two method calls, in order for `getOAuth2Token` to return an access token.

You start the flow by calling `startOAuth2Authentication` as shown here:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/UserActivity.java#L35

And then later complete the flow by calling `getOAuth2Token` as shown here:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/DropboxActivity.java#L22

**Comment by ghilbing** [comment]
Thanks Greg for your answer, I will try to fix it!

Gretel

**Comment by ghilbing** [comment]
Hi Greg, sorry to bother you again.

I tested what you said, I change the files as the original ones, and I did the uninstall process, but I get the same error when I try to download
a file, it is working fine for upload.

I cannot find the problem. Sorry, but I am new trying to use Dropbox and REST API in general…

Thanks for your time, your patience and your help!

Gretel

**Comment by greg-db** [comment]
For comparison, if you run [the original Dropbox Java SDK sample app itself](https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android), do you see the same issue? I ran that sample and downloaded a file and didn't see the issue.

**Comment by ghilbing** [comment]
Hi Greg,

When I did the clone the error is this one.

**Comment by greg-db** [comment]
Apologies, to be clear, do you mean that when you the original Dropbox Java SDK sample app, without modifications, you receive the same "Client not initialized" error? 

That didn't occur for me, so can you let me know the exact steps you followed to reach that error?

Also, if you try on a different device/simulator, do you see the same error?

**Comment by AbandonedCart** [comment]
I was facing a similar issue and (correct me if I am wrong) came to understand that the Dropbox SDK does not actually handle its own authentication flow, but instead relies on the placement of a button to handle pausing the process for the user to authenticate. Is that correct?

Are there any plans to implement some sort of handling for instances where buttons are not conventional? I am recently returning to the SDK from an app that is nearly 2 years old and it appears as though this is still an issue, so I do not have high hopes for a positive answer.

The workflow I am suggesting is similar to that of the Android permissions flow.

**Comment by greg-db** [comment]
@AbandonedCart I'm not sure I understand your question. The Dropbox Java SDK does support the Dropbox OAuth app authorization flow, but you can control the UI in your app for initiating that.

For Android, you should use [the `com.dropbox.core.android.Auth` functionality](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/android/Auth.html), as shown [in the example here](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/DropboxActivity.java#L94).

For non-Android, you should use [the `com.dropbox.core.DbxWebAuth` functionality](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/DbxWebAuth.html), as shown [in the example here](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/web-file-browser/src/main/java/com/dropbox/core/examples/web_file_browser/DropboxAuth.java#L37).

Also, since it's been a while, please make sure you're using the latest version of the SDK, currently v3.1.3.

If something's not working, please [open a new issue](https://github.com/dropbox/dropbox-sdk-java/issues/new) with details.

**Comment by AbandonedCart** [comment]
@greg-db I see you misinterpreted it as asking for assistance. Let me start off by saying my app is fully working. I am not having an issue. 

I ran into a similar issue in the past because the authorization flow provided is to perform a few setup tasks, wait for the user to interact with a button on the UI, then interact with Dropbox.

I am saying that the part where you `wait for the user to interact with a button` is evidence that the flow is incomplete. As it stands, I have a handler loop until there is no longer an `IllegalStateException` attempting to call the client.

My question is if there are any plans to add a callback or some other method of notifying the app that the authorization is complete outside of waiting for them to return to the app and click something to notify the app they have returned?

**Comment by greg-db** [comment]
@AbandonedCart Thanks for clarifying. No, there are no current plans to update the authorization flow support in the SDK like that.

**Comment by AbandonedCart** [comment]
Thanks for being honest. I will seek out alternative services, as the lack of callbacks is only compounded by issues with Chrome not returning to the app. It creates a rather unsavory experience for the end user.

**Comment by cakoose** [comment]
I haven't used the Android SDK in a long time so I may be misremembering, but I thought the authorization flow _does_ redirect to your app automatically.

That's one of the reasons you have to modify your AndroidManifest.xml to add a URL scheme:

```
<data android:scheme="db-{api-app-key-goes-here}" />
```

([Full example.](https://www.dropbox.com/developers-v1/core/sdks/android))

If the Dropbox Android app is installed, authorization happens in that app.  If it's not installed, authorization happens in Chrome.  I think the redirect works in both cases.

**Comment by AbandonedCart** [comment]
@cakoose Newer Android versions have issues redirecting back to the app when defaulting to Chrome, but that is completely unrelated unless you are talking about the discussion from March 2019.
