### ISSUE TITLE
OAuth 2.0 for native apps

### ISSUE THREAD

**Issue by astonbitecode** [dropbox/dropbox-sdk-java#243]
Being in a need to authenticate to dropbox from a native (desktop) application, it seems that that the code OAuth 2.0 flow is implemented and available [only for the web apps](https://www.dropboxforum.com/t5/API-Support-Feedback/OAuth-2-0-for-native-apps/m-p/335102#M19547).

However, as mentioned [here](https://www.oauth.com/oauth2-servers/oauth-native-apps/) for the native apps:

> The current industry best practice is to use the Authorization Flow while omitting the client secret, and to use an external user agent to complete the flow.

Are there plans to support this best practice?

**Comment by jiuyangzhao** [comment]
In this SDK, only Android part support native app. You can always write your own code to implement token flow in non Android part. Our server support both token and code flow.

**Comment by handstandsam** [comment]
A PKCE flow is available in the latest versions.  Use the method `com.dropbox.core.android.Auth.startOAuth2PKCE(...)`

More info on Dropbox & PKCE:
https://dropbox.tech/developers/pkce--what-and-why-
