### ISSUE TITLE
Implementation uses SUN/Oracle Key Store (JKS) 

### ISSUE THREAD

**Issue by gitman89** [dropbox/dropbox-sdk-java#25]
SSLConfig uses JKS directly. Please note that JKS is private Sun/Oracle implementation of Key Store.
I suggest dropbox should use: KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());

https://github.com/dropbox/dropbox-sdk-java/blob/master/src/com/dropbox/core/http/SSLConfig.java#L306

**Comment by cakoose** [comment]
In which situations will `KeyStore.getInstance("JKS")` not work?  Are there commonly-used cryptographic providers that don't support it?

Our current process:
1. Our certificate pinning file is a PEM file.
2. Our SDK build process converts the PEM file to a JKS-format file.
3. When the SDK runs, it loads the JKS-format file into the key store.

If I do `KeyStore.getInstance(KeyStore.getDefaultType())`, can I still use `KeyStore.load` to load that JKS-format file?

**Comment by gitman89** [comment]
It will not work if you don't have JKS key store e.g. in non Sun/Oracle VM. I am using embedded JVM called Skelmir that does not have JKS.

**Comment by cakoose** [comment]
Hmm, ok.  Some other options:
1. Load the cert directly from the PEM file.  The code isn't that complicated ([PemLoader.java](https://github.com/dropbox/pem-to-jks-maven-plugin/blob/master/src/com/dropbox/maven/pem_to_jks/PemLoader.java)).
2. Change our build process to output to a custom format instead of the JKS format.  The custom format would be simple -- just a bunch of length+data pairs, one for each cert, all concatenated together in a file.  The SDK can easily read this data and load it into any KeyStore.

I'm leaning toward option 2, since it's slightly more efficient.

Unfortunately, I don't think I have time to work on this right now.  If you are able to work on it now, let me know and I can give you more details.

**Comment by gitman89** [comment]
I will try out second solution. I will prepare simple tool using PemLoader to convert certs to file (in way you suggest data length + data). Then I will modify SDK's SSLConfig to load it from this custom file using any KeyStore. 
But I have only very basic knowledge on maven and github so in order to share my work I would need some assistance/guidelines. 
Are you willing and able to help me share my work?

**Comment by cakoose** [comment]
The current setup uses a Maven plugin we built called "pem-to-jks-maven-plugin".  Right now, that plugin only supports converting to the JKS format.

I just renamed it to "pem-converter-maven-plugin" and updated the ReadMe.md to describe how I think it should behave.

If you want to move forward, this is my suggested course of action:
1. Update ["pem-converter-maven-plugin"](https://github.com/dropbox/pem-converter-maven-plugin) to behave as described by the [updated ReadMe](https://github.com/dropbox/pem-converter-maven-plugin/commit/3b355f2caaa3284a48538ba23c03c3bc94c33d3b#diff-f9e9432b3b778c13806aea6c01e507d0).  (Feel free to make adjustments if something I wrote seems weird.)
2. Update "dropbox-sdk-java" to use the new "pem-converter-maven-plugin".  (To try things out locally, I think you can do a "mvn install" on the plugin project and then do a "mvn build" in the "dropbox-sdk-java" project -- it should pick up the freshly-installed plugin.)
3. There's a TODO in the "pem-converter-maven-plugin" ReadMe for describing how to load a "raw" certificate file.  Fill in the TODO with sample code.

Once everything works send me two pull requests (one for each repo).  I'll test things out and if everything works, I'll publish the new versions to GitHub and to Maven Central.

Thanks a lot!  And feel free to ask me questions if you run into any issues.

**Comment by gitman89** [comment]
So as far as I get I see that PEM file is the best "raw" format for holding certificates So I don't see what is the point of converter in this case.  I wiould suggest to go without converter at all and just do the parsing and reading to key store directly in SDK. 
Note that to be able to read certificate I have to store it proper format. And this format is actually the same as in PEM the only difference is that in PEM it is base64 encoded. And what converter does is just decode this parts and load to new empty key store and then save key store.  So if I just move this reading to empty key store to SDK it will work. 
So from my point of view there is nothing we get by using converter (maybe just base64 decoding).  I will modify SDK pom to just copy pem and then copy code for loading (PemLoader) to SDK to load it to empty keyStore. 
What do you think about this approarch? It is actually what you suggest as point 1.
