### ISSUE TITLE
Extra argument in 'authorize-beta' example.

### ISSUE THREAD

**Issue by cakoose** [dropbox/dropbox-sdk-java#250]
The help message says that it takes three arguments, but it actually only takes two arguments: 
https://github.com/dropbox/dropbox-sdk-java/blob/011052e328faff1d12b965d4e590c1e33e6a0767/examples/authorize-beta/src/main/java/com/dropbox/core/examples/authorize_beta/Main.java#L30-L32

**Comment by greg-db** [comment]
Thanks!

**Comment by jiuyangzhao** [comment]
I've fixed them!
