### ISSUE TITLE
Confused about 'authorize' vs 'authorize-beta' example.

### ISSUE THREAD

**Issue by cakoose** [dropbox/dropbox-sdk-java#251]
- "authorize-beta" behaves like the old "authorize", it takes two arguments: [code](https://github.com/dropbox/dropbox-sdk-java/blob/011052e328faff1d12b965d4e590c1e33e6a0767/examples/authorize-beta/src/main/java/com/dropbox/core/examples/authorize_beta/Main.java#L30-L32)
- "authorize" takes an additional "token-access-type" argument: [code](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/authorize/src/main/java/com/dropbox/core/examples/authorize/Main.java#L29-L31)

It seems like the "-beta" version should be the one with the additional argument, right?

**Comment by greg-db** [comment]
Thanks as always Kannan!

**Comment by jiuyangzhao** [comment]
Thank you Kannan!.

I will just just revert the authorize example to old version!

**Comment by jiuyangzhao** [comment]
Thanks! I've fixed!
