### ISSUE TITLE
com.dropbox.core.NetworkIOException: Pipe closed

### ISSUE THREAD

**Issue by pramodkr123** [dropbox/dropbox-sdk-java#252]
Hello,
 I am getting this exception while uploading file on dropbox.

 'com.dropbox.core.NetworkIOException: Pipe closed'

My Internet connection is working fine.

**Comment by TaylorKrusen** [comment]
I'll be happy to help with any issues you're having with the Dropbox API, but I'll need some more information. Please reply with:

- the version number of the platform and SDK you are using
- the full text of the error stack
- the steps to reproduce the issue
- the relevant code snippet(s)

**Comment by ziseyanhua** [comment]
I have same problem with you。Could you tell me how do you resolve

**Comment by pramodkr123** [comment]
Just restart your android device.
