### ISSUE TITLE
Getting file upload success response but file is not uploaded on Dropbox

### ISSUE THREAD

**Issue by pramodkr123** [dropbox/dropbox-sdk-java#253]
When I am uploading file on Dropbox, I am getting upload success response but File is not uploaded on Dropbox and Getting last modified time.

Getting every time same revision number
I am using this dependencies : compile 'com.dropbox.core:dropbox-core-sdk:3.1.0'
This issue is coming on Android Pie Devices.

When i using this code It is working, if file is not exist on Dropbox.
If file is exist on Dropbox , not OVERWRITE  the file .

**My code to upload file :** 
    obj = mDbxClient.files().uploadBuilder(remoteFolderPath + "/" + remoteFileName)
                    .withMode(WriteMode.OVERWRITE)
                    .uploadAndFinish(inputStream,progressListener);

**Previous upload Response :** 
{".tag":"file","name":"demo1.db","id":"id:CD6HSNj88gAAAAAAAAACIg",**"client_modified":"2019-05-26T13:57:26Z","server_modified":"2019-05-26T13:57:26Z"**,"rev":"2097aa3c2350","size":933888,"path_lower":"/demo1.db","path_display":"/demo1.db","content_hash":"4ec058c1fa071c0c1fb136edbbec995a6e73a31d2df571d4d013a614b673a1b4"}

**Try Again to upload file getting same response -**
{".tag":"file","name":"demo1.db","id":"id:CD6HSNj88gAAAAAAAAACIg",**"client_modified":"2019-05-26T13:57:26Z","server_modified":"2019-05-26T13:57:26Z"**,"rev":"2097aa3c2350","size":933888,"path_lower":"/demo1.db","path_display":"/demo1.db","content_hash":"4ec058c1fa071c0c1fb136edbbec995a6e73a31d2df571d4d013a614b673a1b4"}

**Comment by TaylorKrusen** [comment]
Based on the output, it looks like the file data is not changing across the uploads. Are you uploading the same exact data each time? If so, this is expected. Uploading the same data is not considered a change and so will not change the data or cause a conflict. It would just return the existing metadata as you're seeing here.
