### ISSUE TITLE
Unable to extend DbxRawClientV2

### ISSUE THREAD

**Issue by dkocher** [dropbox/dropbox-sdk-java#254]
One can no longer extend from `DbxRawClientV2` as the new methods `canRefreshAccessToken` and `needsRefreshAccessToken` introduced lack the `protected` keyword.

**Comment by db-api-support-github-notifications** [comment]
Thanks for letting us know, David. I filed a bug with engineering. I'll 
reach out once I have an update.

**Comment by TaylorKrusen** [comment]
^^ That's me, by the way. I should have replied from here so you knew who you're speaking with. 
I'll let you know when I hear back!

**Comment by dkocher** [comment]
Any status update? This is blocking us from upgrading to the current release.

**Comment by greg-db** [comment]
@dkocher No, we don't have an update on this yet. This is still open with the team though, and we'll follow up here once we have any news.

**Comment by handstandsam** [comment]
It appears these methods are not `private` anymore, and therefore can be extended.

https://github.com/dropbox/dropbox-sdk-java/blob/e55b3cd3f0f8296a5b5286d8b55c5cc01d6b1a08/dropbox-sdk-java/src/main/java/com/dropbox/core/v2/DbxRawClientV2.java#L92-L94

Closing as fixed.

**Comment by handstandsam** [comment]
Ahh, I think I see the issue.  Because these are not marked as `public` or `private` explicitly, they are considered package private.

If there is still a need for this, please re-open, and we can either make these `protected` or `public`.

**Comment by dkocher** [comment]
> If there is still a need for this, please re-open, and we can either make these `protected` or `public`.

It seems I am not allowed to reopen the issue.

**Comment by greg-db** [comment]
@dkocher I've reopened it for you. Thanks!

**Comment by handstandsam** [comment]
Thanks for the quick response.  Since it is still needed, we can tag it to get into this next version to be released next week.

We should be able to mark both methods as `protected`.

**Comment by handstandsam** [comment]
This has been addressed in https://github.com/dropbox/dropbox-sdk-java/pull/452

@dkocher can you confirm this is what was requested?

**Comment by handstandsam** [comment]
Closing since the work was done.  I can make any additional changes if this isn't what you were looking for.
