### ISSUE TITLE
How to cache responses using dropbox-sdk-java and OkHttp

### ISSUE THREAD

**Issue by SailReal** [dropbox/dropbox-sdk-java#255]
I'm using dropbox-sdk-java using OkHttp to make the requests in Android and want to use the caching mechanism implemented in OkHttp.

I create a `DbxClientV2` using the following code:

``` java
private DbxClientV2 createDropboxClient(final String accessToken) {
    final Cache cache = new Cache(new File(context.getCacheDir(), "HttpCacheDropbox"), 1024 * 1024 * 10);

    final OkHttpClient okHttpClient = OkHttp3Requestor //
            .defaultOkHttpClientBuilder() //
            .cache(cache) //
            .addNetworkInterceptor(provideCacheInterceptor()) //
            .addInterceptor(provideOfflineCacheInterceptor()) //
            .addInterceptor(httpLoggingInterceptor(context)) //
            .connectTimeout(CONNECTION.getTimeout(), CONNECTION.getUnit()) //
            .readTimeout(READ.getTimeout(), READ.getUnit()) //
            .writeTimeout(WRITE.getTimeout(), WRITE.getUnit()) //
            .build();

    final DbxRequestConfig requestConfig = DbxRequestConfig //
            .newBuilder("Test-Android/" + BuildConfig.VERSION_NAME) //
            .withUserLocale(Locale.getDefault().toString()) //
            .withHttpRequestor(new OkHttp3Requestor(okHttpClient)) //
            .build();

    return new DbxClientV2(requestConfig, accessToken);
}
```

The `cacheInterceptors` are implemented like described in this post: https://stackoverflow.com/a/45431753/825532

Then I make e.g. a download request using the following snippet:

``` java
...
    .createDropboxClient(accessToken) //
    .download(file.getPath()) //
    .download(...)
```

The requests itself works and the intercepted functions are called but the caching itself doesn't work.

If I use the `okHttpClient` directly to make a `GET` request to a random server the response is cached but not using the `DbxClientV2`.

Do you have a idea what the problem could be?
Thanks!

**Comment by greg-db** [comment]
[Cross-linking for reference: [https://stackoverflow.com/questions/56906089/cache-responses-using-dropbox-sdk-java-and-okhttp-not-works](https://stackoverflow.com/questions/56906089/cache-responses-using-dropbox-sdk-java-and-okhttp-not-works) ]

The Dropbox API doesn't support HTTP caching like this. If you want to avoid re-downloading the same file data though, you can check the metadata returned by the API first. That is, when you first [`download`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#download-java.lang.String-) a file, store the [`FileMetadata.rev`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/FileMetadata.html#rev) value. You can then later check the file using [`getMetadata`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#getMetadata-java.lang.String-). If the `rev` is the same, you know the file hasn't changed so you don't need to download it again,
