### ISSUE TITLE
Network I/O Error: Broken Pipe

### ISSUE THREAD

**Issue by ufumerfarooq** [dropbox/dropbox-sdk-java#257]
I am trying to upload file via dropbox core api but suddenly my internet connection disconnects. Then I got following exception:

> com.dropbox.core.NetworkIOException: Write error: ssl=0xa17da540: I/O error during system call, Broken pipe
> com.dropbox.core.DbxUploader.uploadAndFinish(DbxUploader.java:123)`
>com.dropbox.core.v2.DbxUploadStyleBuilder.uploadAndFinish(DbxUploadStyleBuilder.java:160)
And upload client stops uploading.

Thanks

**Comment by greg-db** [comment]
Can you share the steps and code to reproduce this issue?

Also, can you elaborate on what you're referring to when you say "suddenly my internet connection disconnects"? If there's an issue with your network connection, that would be out of our control, and an error would be expected. Or are you saying this _only_ and reproducibly occurs when uploading to Dropbox?

**Comment by ufumerfarooq** [comment]
Yes, you can reproduce the error by following these steps:

- Setup Dropbox android sdk.
- Try to upload a file.
- While uploading, disconnect your phone from internet.
- Now uploadProcess will not wait for internet to re-establish and throws Network I/O Exception.

Dropbox Api Version: 3.0.10

**Comment by ufumerfarooq** [comment]
Now I change my `DbxRequestConfig` from
`DbxRequestConfig config = new DbxRequestConfig("Dropbox/Apps/Sample");`

to

```
DbxRequestConfig config = DbxRequestConfig.newBuilder("Dropbox/Apps/Sample")
                .withHttpRequestor(new OkHttp3Requestor(OkHttp3Requestor.defaultOkHttpClient()))
                .build();
```
Now UploadTask throws following error:

> com.dropbox.core.NetworkIOException: InputStream is closed
> at com.dropbox.core.DbxUploader.finish(DbxUploader.java:275)
> at com.dropbox.core.DbxUploader.uploadAndFinish(DbxUploader.java:126)
> at com.dropbox.core.DbxUploader.uploadAndFinish(DbxUploader.java:96)
> at com.dropbox.core.v2.DbxUploadStyleBuilder.uploadAndFinish(DbxUploadStyleBuilder.java:92)

**PS: I also changed my sdk to latest version**

**Comment by greg-db** [comment]
Thanks for the additional information! This looks like the expected behavior though. A network disconnect like this is expected to cause a `NetworkIOException`.
