### ISSUE TITLE
Apache HTTP in Android SDK

### ISSUE THREAD

**Issue by MariusVolkhart** [dropbox/dropbox-sdk-java#26]
The Android SDK uses the Apache HTTP client from the Android platform. In Android API 23 the apache client is no longer available. This produces compile errors if the Dropbox SDK is included in a project targeting the latest version of Android.

I couldn't find the Android SDK on github anywhere so I am reporting here.

**Comment by cakoose** [comment]
It looks like there's a workaround: [https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client](https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client).  Please let me know if it doesn't work for you.

In a few months be releasing a brand new Android SDK that doesn't use Apache HttpClient.  Unfortunately, that SDK won't be compatible with the existing Android SDK and you'll have to modify your code to use it.

**Comment by MariusVolkhart** [comment]
Yeah we were using the workaround already. Just wanted to make sure the Apache client removal was on the radar. Thanks
