### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied

### ISSUE THREAD

**Issue by mallireddy15** [dropbox/dropbox-sdk-java#260]
`public class DropBoxConnection {

    private static final String ACCESS_TOKEN = "xxxxxxxxxxxxxxxxxxxxxxxx";
    private static DbxRequestConfig config = null;
    static DbxClientV2 client = null;
    FullAccount account = null;

    public static void main(String[] args) {
        // Create Dropbox client
        config = new DbxRequestConfig("dropbox/java-tutorial");
        client = new DbxClientV2(config, ACCESS_TOKEN);

        try {

            FullAccount account = client.users().getCurrentAccount();
            System.out.println(account.getName().getDisplayName());
        }
        catch (DbxException dbxe)
        {
            dbxe.printStackTrace();
        }
    }
}`

Getting SSLHandshakeException when I try to run the above code?

**Comment by greg-db** [comment]
Is that the full error output you get? If not, can you share the rest?

Also, is there anything on your network connection, e.g., firewall, proxy, anti-virus, or other security or networking software that may be interfering with the connection to api.dropboxapi.com?

**Comment by mallireddy15** [comment]
Greg - It's certificate issue. After adding the dropbox cert to Trusted Root Certification Authorities in certmngr code is working fine.
