### ISSUE TITLE
search_v2 API is not implemented ?

### ISSUE THREAD

**Issue by bubbleguuum** [dropbox/dropbox-sdk-java#261]
Looks like search_v2 as described on https://www.dropbox.com/developers/documentation/http/documentation#files-search is not implemented at all. Any plans to add it ?
search v1 is rather limited.

**Comment by greg-db** [comment]
Yes, this should be available in the next release of the Java SDK. I'll ask the team to work on that.

**Comment by bubbleguuum** [comment]
Excellent! Thank you.

**Comment by greg-db** [comment]
The new search endpoints are now implemented as [`searchV2`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#searchV2-java.lang.String-)/[`searchContinueV2`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#searchContinueV2-java.lang.String-).
