### ISSUE TITLE
Logging done successfully, but the folder is not uploading

### ISSUE THREAD

**Issue by sahujaunpuri** [dropbox/dropbox-sdk-java#263]
Logging done successfully, but the folder is not uploading.
**Loging**

  `  import android.content.Context;
         import android.content.DialogInterface;
      import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.os.Bundle;
import android.preference.Preference;
import android.preference.PreferenceActivity;
import android.preference.PreferenceCategory;
import android.support.annotation.Nullable;
import android.support.v7.app.AlertDialog;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.Toast;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.android.AndroidAuthSession;
import com.dropbox.client2.session.AppKeyPair;

import co.com.aashriyatechnology.automaticcallrecorder.controller.UploadFile;
import co.com.aashriyatechnology.automaticcallrecorder.utils.ConnectionUtils;
import co.com.aashriyatechnology.automaticcallrecorder.utils.MyConstants;
import co.com.aashriyatechnology.automaticcallrecorder.utils.PreferUtils;

   public class CloudActivity extends PreferenceActivity
        implements MyConstants,View.OnClickListener,Preference.OnPreferenceClickListener {
    private Context mContext;

    public static DropboxAPI<AndroidAuthSession> mDropboxApi;
    private Button mSyncAll;
    private Preference mDrive, mDropbox;

    @Override
    protected void onPostCreate(Bundle savedInstanceState) {
        super.onPostCreate(savedInstanceState);
        LinearLayout root = (LinearLayout) findViewById(android.R.id.list).getParent().getParent().getParent();
        Toolbar bar = (Toolbar) LayoutInflater.from(this).inflate(R.layout.toolbar_layout, root, false);
        root.addView(bar, 0); // insert at top
        bar.setTitle(getString(R.string.nav_cloud));
        bar.setNavigationOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                finish();
                CallRecorderApp.isNeedShowPasscode = false;
            }
        });
    }

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mContext = this;
        getPreferenceManager()
                .setSharedPreferencesName(MyConstants.PREFS_NAME);
        addPreferencesFromResource(R.xml.cloud_acount_prefs);
        getListView().setDivider(new ColorDrawable(Color.TRANSPARENT));
        setContentView(R.layout.footer_cloud_account);
        mSyncAll = (Button)findViewById(R.id.footer_cloud_account_btn_sync_all);
        mSyncAll.setOnClickListener(this);
        mDrive = findPreference(KEY_DRIVE_ACCOUNT);
        mDropbox = findPreference(KEY_DROPBOX_ACCOUNT);
        mDrive.setOnPreferenceClickListener(this);
        mDropbox.setOnPreferenceClickListener(this);

        getInstanceDropbox(mContext);

        //For Hide Drive account cloud , will update in next version
        if(!IS_ENABLE_GOOGLE_DRIVE){
            PreferenceCategory mCategory = (PreferenceCategory) findPreference("preference_category_account_cloud");
            Preference mGoogleDivePref = findPreference("key_drive_account");
            mCategory.removePreference(mGoogleDivePref);
        }
        Log.d(TAG,"isDropboxLinked = "+isDropboxLinked());
        setLoggedIn(isDropboxLinked(), false);

    }

    @Override
    protected void onResume() {
        super.onResume();

//        setLoggedIn(PreferUtils.getbooleanPreferences(mContext, IS_DROPBOX_LINKED),false);
        AndroidAuthSession session = mDropboxApi.getSession();
        // The next part must be inserted in the onResume() method of the
        // activity from which session.startAuthentication() was called, so
        // that Dropbox authentication completes properly.
        if (session.authenticationSuccessful()) {
            try {
                // Mandatory call to complete the auth
                session.finishAuthentication();
                // Store it locally in our app for later use
                storeAuth(session);
                setLoggedIn(true,false);// disable Drive google
                if(!PreferUtils.getbooleanPreferences(mContext, KEY_IS_THE_FIRST_SYNC_AFTER_AUTHENTICATION)){
                    if(ConnectionUtils.isWifiAvailable(mContext)){
                        new UploadFile(mContext, mDropboxApi).execute(MODE_UPLOAD_FOLDER);
                    }else if (ConnectionUtils.isMobileAvailable(mContext)) {
                        createWaringDialog(getString(R.string.warning_dialog_using_mobile_data_title),
                                getString(R.string.warning_dialog_using_mobile_data_des), true);
                    }

                    PreferUtils.savebooleanPreferences(mContext, KEY_IS_THE_FIRST_SYNC_AFTER_AUTHENTICATION, true);
                }
            } catch (IllegalStateException e) {
                Toast.makeText(mContext, "Couldn't authenticate with Dropbox",
                        Toast.LENGTH_SHORT).show();
                Log.d(TAG, "Error authenticating" + e.getLocalizedMessage());
            }
        }
    }

    public static DropboxAPI<AndroidAuthSession> getInstanceDropbox(
            Context context) {
        AndroidAuthSession session = buildSession(context);
        mDropboxApi = new DropboxAPI<>(session);
        return mDropboxApi;
    }

    /**
     * Check this app linked to Dropbox or not
     *
     * @return
     */
    public static boolean isDropboxLinked() {
        return (mDropboxApi != null && (mDropboxApi.getSession().isLinked()));
    }

    public static AndroidAuthSession buildSession(Context context) {
        AppKeyPair appKeyPair = new AppKeyPair(DROPBOX_APP_KEY,
                DROPBOX_APP_SECRET);
        AndroidAuthSession session = new AndroidAuthSession(appKeyPair);
        loadAuth(context, session);
        return session;
    }

    /**
     * Shows keeping the access keys returned from Trusted Authenticator in a
     * local store, rather than storing user name & password, and
     * re-authenticating each time (which is not to be done, ever).
     */
    public static void loadAuth(Context context, AndroidAuthSession session) {
        SharedPreferences prefs = context.getSharedPreferences(
                ACCOUNT_PREFS_NAME, 0);
        String key = prefs.getString(ACCESS_KEY_NAME, null);
        String secret = prefs.getString(ACCESS_SECRET_NAME, null);
        if (key == null || secret == null || key.length() == 0
                || secret.length() == 0)
            return;

        if (key.equals("oauth2:")) {
            // If the key is set to "oauth2:", then we can assume the token is
            // for OAuth 2.
            session.setOAuth2AccessToken(secret);
        }
    }

    /**
     * Shows keeping the access keys returned from Trusted Authenticator in a
     * local store, rather than storing user name & password, and
     * re-authenticating each time (which is not to be done, ever).
     */
    private void storeAuth(AndroidAuthSession session) {
        // Store the OAuth 2 access token, if there is one.
        String oauth2AccessToken = session.getOAuth2AccessToken();
        if (oauth2AccessToken != null) {
            SharedPreferences prefs = getSharedPreferences(ACCOUNT_PREFS_NAME,
                    0);
            SharedPreferences.Editor edit = prefs.edit();
            edit.putString(ACCESS_KEY_NAME, "oauth2:");
            edit.putString(ACCESS_SECRET_NAME, oauth2AccessToken);
            edit.commit();
            return;
        }
    }

    private void logOut() {
        // Remove credentials from the session
        mDropboxApi.getSession().unlink();
        // Clear our stored keys
        clearKeys();
        // Change UI state to display logged out version
        setLoggedIn(false, false);
        PreferUtils.savebooleanPreferences(mContext, KEY_IS_THE_FIRST_SYNC_AFTER_AUTHENTICATION, false);
        PreferUtils.savebooleanPreferences(mContext, IS_DROPBOX_LINKED, false);
    }
    /**
     * Enable view when login dropbox or google drive
     *
     * @param userDropboxLoggedIn
     * @param userGoogleLoggedIn
     */
    private void setLoggedIn(boolean userDropboxLoggedIn, boolean userGoogleLoggedIn) {
        if (DEBUG)
            Log.i(TAG, "Dropbox login is " + userDropboxLoggedIn);
        if(userDropboxLoggedIn)
            PreferUtils.savebooleanPreferences(mContext, IS_DROPBOX_LINKED, true);
        if (userDropboxLoggedIn || userGoogleLoggedIn) {
            findPreference("cloud_sync_wifi_only")
                    .setEnabled(true);
            findPreference("cloud_sync_automatic")
                    .setEnabled(true);
            mSyncAll.setEnabled(true);
        } else {
            findPreference("cloud_sync_wifi_only")
                    .setEnabled(false);
            findPreference("cloud_sync_automatic")
                    .setEnabled(false);
            mSyncAll.setEnabled(false);
        }

        if(IS_ENABLE_GOOGLE_DRIVE){
            //for 2 account : Dropbox and Drive .
            if (userDropboxLoggedIn) {
                findPreference("key_drive_account").setIcon(R.drawable.ic_drive_unlink);
                findPreference("key_dropbox_account").setIcon(R.drawable.ic_dropbox);
            } else if (userGoogleLoggedIn) {
                findPreference("key_drive_account").setIcon(R.drawable.ic_drive);
                findPreference("key_dropbox_account").setIcon(R.drawable.ic_dropbox_unlink);
            } else {
                findPreference("key_drive_account").setIcon(R.drawable.ic_drive_unlink);
                findPreference("key_dropbox_account").setIcon(R.drawable.ic_dropbox_unlink);
            }
        }else {
            // one account : Dropbox
            if (userDropboxLoggedIn) {
                findPreference("key_dropbox_account").setIcon(R.drawable.ic_dropbox);
            }else {
                findPreference("key_dropbox_account").setIcon(R.drawable.ic_dropbox_unlink);
            }
        }

    }

    private void clearKeys() {
        SharedPreferences prefs = getSharedPreferences(ACCOUNT_PREFS_NAME, 0);
        SharedPreferences.Editor edit = prefs.edit();
        edit.clear();
        edit.commit();
    }

    @Override
    public void onClick(View view) {
        switch (view.getId()) {
            case R.id.footer_cloud_account_btn_sync_all:
                // Toast.makeText(mContext, "Sync All", Toast.LENGTH_LONG).show();
                if(ConnectionUtils.isWifiAvailable(mContext)){
                    new UploadFile(mContext, mDropboxApi).execute(MODE_UPLOAD_FOLDER);
                }else if (ConnectionUtils.isMobileAvailable(mContext)) {
                    // warning -> OK
                    createWaringDialog(getString(R.string.warning_dialog_using_mobile_data_title),
                            getString(R.string.warning_dialog_using_mobile_data_des), true);
                }else {
                    // warning -> NO
                    createWaringDialog("", getString(R.string.no_internet), false);
                }

                // new UploadFile(mContext, mDropboxApi).execute(MODE_UPLOAD_FOLDER);

                break;

            default:
                break;
        }
    }

    @Override
    public boolean onPreferenceClick(Preference preference) {
        String key = preference.getKey();
        if (key == null)
            return false;
        if(!ConnectionUtils.isConnectingToInternet(mContext)){
            createWaringDialog("", getString(R.string.no_internet), false);
            return false;
        }
        if (key.equals(KEY_DRIVE_ACCOUNT)) {
            Toast.makeText(mContext, "Login Google Drive", Toast.LENGTH_LONG)
                    .show();

        } else if (key.equals(KEY_DROPBOX_ACCOUNT)) {
            if (isDropboxLinked()) {
                if (DEBUG) Log.i(TAG, "isDropboxLinked " + isDropboxLinked());
                logOut();
            } else {
                if (DEBUG) Log.i(TAG, "isDropboxLinked " + isDropboxLinked());
                mDropboxApi.getSession().startOAuth2Authentication(mContext);

            }

        }
        return false;
    }

    private void createWaringDialog(String title,String message,boolean isOnline){
        AlertDialog.Builder builder = new AlertDialog.Builder(mContext);

        if(isOnline) {
            builder.setTitle(title);
            builder.setMessage(message);
            // Add the buttons
            builder.setPositiveButton(R.string.string_ok, new DialogInterface.OnClickListener() {
                public void onClick(DialogInterface dialog, int id) {
                    // User clicked OK button
                    new UploadFile(mContext, mDropboxApi).execute(MODE_UPLOAD_FOLDER);
                }
            });
            builder.setNegativeButton(R.string.string_cancel, new DialogInterface.OnClickListener() {
                public void onClick(DialogInterface dialog, int id) {
                    // User cancelled the dialog
                    dialog.dismiss();
                }
            });
        }else {
            builder.setMessage(message);
            builder.setPositiveButton(R.string.string_ok, new DialogInterface.OnClickListener() {
                public void onClick(DialogInterface dialog, int id) {
                    // User clicked OK button
                    dialog.dismiss();
                }
            });
        }

        AlertDialog dialog = builder.create();
        dialog.show();
    }

    @Override
    public void onBackPressed() {
        super.onBackPressed();
        CallRecorderApp.isNeedShowPasscode = false;
    }
}
`

**UploadFile**

`import android.content.Context;
import android.os.AsyncTask;
import android.util.Log;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.DropboxAPI.UploadRequest;
import com.dropbox.client2.exception.DropboxException;
import com.dropbox.client2.exception.DropboxFileSizeException;
import com.dropbox.client2.exception.DropboxIOException;
import com.dropbox.client2.exception.DropboxParseException;
import com.dropbox.client2.exception.DropboxPartialFileException;
import com.dropbox.client2.exception.DropboxServerException;
import com.dropbox.client2.exception.DropboxUnlinkedException;
import co.com.aashriyatechnology.automaticcallrecorder.R;
import co.com.aashriyatechnology.automaticcallrecorder.utils.MyConstants;
import co.com.aashriyatechnology.automaticcallrecorder.utils.PreferUtils;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;

public class UploadFile extends AsyncTask<String, Long, Boolean> implements MyConstants{
	
	private DropboxAPI<?> dropboxApi;
	private Context mContext;
	
	private NotificationController mNotificationHelper;
	private final int mNotificationUploadId = 1988;
	private String mErrorMsg;
	
	public UploadFile(Context context, DropboxAPI<?> dropboxApi) {
		this.mContext = context.getApplicationContext();
		this.dropboxApi = dropboxApi;
		mNotificationHelper = new NotificationController(context);
	}
	@Override
	protected void onPreExecute() {
		// TODO Auto-generated method stub
		super.onPreExecute();
		// Show notification
		mNotificationHelper.createNotification(mNotificationUploadId,
				R.drawable.ic_sync,
				mContext.getString(R.string.sync_notification_content_text),
				mContext.getString(R.string.sync_notification_content_title));
	}

	@Override
	protected Boolean doInBackground(String... modeUpload) {
		// TODO Auto-generated method stub
		FileInputStream fileInputStream;
		try {
			if (modeUpload[0].equals(MODE_UPLOAD_FOLDER) ) {
				List<File> listFile = getAllRecordFromSdcard();
				File[] mFilesToUpload = listFile.toArray(new File[listFile.size()]);
				for (int i = 0; i < mFilesToUpload.length; i++) {
					File file = mFilesToUpload[i];
					// publishProgress(Long.parseLong(""+i));
					fileInputStream = new FileInputStream(file);
					String path = PreferUtils.getNameFolderSaveData(mContext)
								+ File.separator 
								+ file.getParentFile().getName()
								+ File.separator
								+ file.getName();
					if(DEBUG) Log.i(TAG, "MODE_UPLOAD_FOLDER : " +path);
					UploadRequest request = dropboxApi.putFileOverwriteRequest(path, fileInputStream,
									file.length(), null);
					request.upload();
					if (isCancelled()) return false;
				}
				return true;
			}else if (modeUpload[0].equals(MODE_UPLOAD_ONE_FILE)) {
				File file = new File(modeUpload[2]);

				 //Uploading the newly created file to Dropbox.
				fileInputStream = new FileInputStream(file);
				String path = PreferUtils.getNameFolderSaveData(mContext)
						+ File.separator 
						+ file.getParentFile().getName()
						+ File.separator
						+ file.getName();
				if(DEBUG) Log.i(TAG, "MODE_UPLOAD_ONE_FILE : " +path);
				UploadRequest requestOneFile = dropboxApi.putFileOverwriteRequest(path, fileInputStream,
									file.length(), null);
				requestOneFile.upload();
				if (isCancelled()) return false;
				 
				return true;
			}else {
				if(DEBUG) Log.i(TAG, "Don't have any mode upload");
				return false;
			}

		} catch (DropboxUnlinkedException e) {
			// This session wasn't authenticated properly or user unlinked
			if (DEBUG)
				Log.e(TAG, "DropboxUnlinkedException :"
						+ "This app wasn't authenticated properly.");
		} catch (DropboxFileSizeException e) {
			// File size too big to upload via the API
			mErrorMsg = "This file is too big to upload";
			if (DEBUG)
				Log.e(TAG, "DropboxFileSizeException: " + mErrorMsg);
		} catch (DropboxPartialFileException e) {
			// We canceled the operation
			mErrorMsg = "Upload canceled";
			if (DEBUG)
				Log.e(TAG, "DropboxPartialFileException: " + mErrorMsg);
		} catch (DropboxServerException e) {
			// Server-side exception. These are examples of what could
			// happen,
			// but we don't do anything special with them here.
			if (e.error == DropboxServerException._401_UNAUTHORIZED) {
				// Unauthorized, so we should unlink them. You may want to
				// automatically log the user out in this case.
				if (DEBUG)
					Log.e(TAG, "DropboxServerException: "
							+ "401_UNAUTHORIZED");
			} else if (e.error == DropboxServerException._403_FORBIDDEN) {
				// Not allowed to access this
				if (DEBUG)
					Log.e(TAG, "DropboxServerException: " + "403_FORBIDDEN");
			} else if (e.error == DropboxServerException._404_NOT_FOUND) {
				// path not found (or if it was the thumbnail, can't be
				// thumbnailed)
				if (DEBUG)
					Log.e(TAG, "DropboxServerException: " + "404_NOT_FOUND");
			} else if (e.error == DropboxServerException._507_INSUFFICIENT_STORAGE) {
				// user is over quota
				if (DEBUG)
					Log.e(TAG, "DropboxServerException: "
							+ "507_INSUFFICIENT_STORAGE");
			} else {
				// Something else
				if (DEBUG)
					Log.e(TAG, "DropboxServerException: " + "UNKNOW ERROR");
			}
			// This gets the Dropbox error, translated into the user's
			// language
			mErrorMsg = e.body.userError;
			if (mErrorMsg == null) {
				mErrorMsg = e.body.error;
			}
		} catch (DropboxIOException e) {
			e.printStackTrace();
			// Happens all the time, probably want to retry automatically.
			mErrorMsg = "Network error.  Try again.";
			if (DEBUG)
				Log.e(TAG, "DropboxIOException: " + mErrorMsg);
		} catch (DropboxParseException e) {
			// Probably due to Dropbox server restarting, should retry
			mErrorMsg = "Dropbox error.  Try again.";
			if (DEBUG)
				Log.e(TAG, "DropboxIOException: " + mErrorMsg);
		} catch (DropboxException e) {
			// Unknown error
			mErrorMsg = "Unknown error.  Try again.";
			if (DEBUG)
				Log.e(TAG, "DropboxIOException: " + mErrorMsg);
		} catch (FileNotFoundException e) {
			if (DEBUG)
				Log.e(TAG, "FileNotFoundException: ");
		} catch (AbstractMethodError e) {
			// TODO: handle exception
			if (DEBUG)
				Log.e(TAG, "AbstractMethodError: ");
		}

		return false;
		
	}
	@Override
	protected void onPostExecute(Boolean result) {
		// TODO Auto-generated method stub
		super.onPostExecute(result);
		// Hide notifications
		mNotificationHelper.completed(mNotificationUploadId);
	}
	
	/**
	 * Get all file record in my save folder
	 * 
	 * @return
	 */
	private List<File> getAllRecordFromSdcard() {
		List<File> listAllFile = new ArrayList<File>();
		File parentDir = new File(MyFileManager.getFilePath(),
				PreferUtils.getNameFolderSaveData(mContext));
		listAllFile = listDir(parentDir, mContext);
		return listAllFile;
		
	}
	private List<File> listDir (File parentDir, Context context){
		File[] files = parentDir.listFiles();
		List<File> fileList = new ArrayList<File>();
		for (File file : files) {
			if (file.isDirectory()) {			
				fileList.addAll(listDir(file, mContext));
			} else {
				fileList.add(file);
			}
		}
		return fileList;
	}

}
`

Please tell me where i'm doing I have made a mistake

**Comment by greg-db** [comment]
I'll be happy to help with any issues you're having with the Dropbox API, but I'll need some more information. Please reply with:

- the version number of the SDK you have installed
- a clear description of what exactly isn't behaving as you expect it to
- the steps to reproduce the issue, including just relevant code snippet(s)
- the full text of any error or unexpected output

You've shared a significant amount of code here, so it's unclear which parts are relevant. Please share only the relevant code.

**Comment by sahujaunpuri** [comment]
Appended below is the version I have installed:

- dropbox-core-sdk:3.1.1

- After login neither any error is observed in during debug nor  release. Data are getting synchronized but it is not being saved in drop box. 

- Which code i am using , has been already posted in earlier post.
- After login neither any error is observed in during debug nor  release. This is only confusing me that neither it working nor any error being observed.

**Comment by greg-db** [comment]
You've shared a large amount of code, and haven't specified what specific functionality isn't doing what you expect, so it's unclear what you're requesting help with exactly.

I recommend stepping through with a debugger to see where the code execution goes and where/when it isn't doing what you expect.

That said, looking through some of the code here, it looks like you're actually trying to use some functionality from the now retired Dropbox API v1 (e.g., the `com.dropbox.client2` import and `putFileOverwriteRequest` call appear to be from the old SDK for Dropbox API v1). Calling API v1 now will fail, and should return a specific error message.

To use Dropbox API v2 from an Android app, please use [the official Dropbox API v2 Java SDK as documented here](https://github.com/dropbox/dropbox-sdk-java), as shown in [the included Android example app](https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android).
