### ISSUE TITLE
.withIncludeMediaInfo - "This parameter will no longer have an effect starting December 2, 2019"

### ISSUE THREAD

**Issue by DennyWeinberg** [dropbox/dropbox-sdk-java#268]
Hello,

I didn't see that coming and finally my app isn't working anymore because the media info aren't anymore included when using `withIncludeMediaInfo`. Right now I'm unable to extract the Date Taken, Longitude and Latitude for the fiven photos using the API. Is there another way of doing it? Any permissions to request? Or is that feature now completely gone?

I'm talking about my f* awesome Android App: https://play.google.com/store/apps/details?id=com.levionsoftware.instagram_map

Please help me. I fear to remove Dropbox from by supported cloud services!

Denny

**EDIT**: Solution provided here: https://www.dropboxforum.com/t5/API-Support-Feedback/include-media-info-quot-This-parameter-will-no-longer-have-an/m-p/386436#M21475

But I'm not happy at all with that solution :( Please bring that feature back!

**Comment by greg-db** [comment]
[Cross-linking for reference: https://www.dropboxforum.com/t5/API-Support-Feedback/include-media-info-quot-This-parameter-will-no-longer-have-an/td-p/386432 ]

I see you also posted on the forum and and had a discussion about it there, so I'll follow up on that thread.
