### ISSUE TITLE
Android example in Kotlin version

### ISSUE THREAD

**Issue by AliAzaz** [dropbox/dropbox-sdk-java#272]
Kotlin is now becoming the most admirable language for programmers due to the simplicity of code, helps to avoid most renowned NullPointerException, Interoperability, Data classes and much more. So, we require this library in Kotlin to provide ease to the developers.

**Comment by greg-db** [comment]
Thanks for sharing this. I'm sending this request for an Android example for this SDK in Kotlin along to the team. I can't promise if/when one might be written and released though.

**Comment by AliAzaz** [comment]
Thanks for this. Sir May I do convert it to Kotlin???

**Comment by greg-db** [comment]
Our SDK is [released under the MIT license](https://github.com/dropbox/dropbox-sdk-java/blob/master/License.txt) so you're welcome to modify it as desired. We also welcome [pull requests](https://github.com/dropbox/dropbox-sdk-java/pulls) if you wish to share your work.

**Comment by cakoose** [comment]
@AliAzaz: I don't work for Dropbox, but I would first recommend creating your own repo and putting your Kotlin SDK there.
1. This will allow you to iterate more quickly and allow others to try it out sooner, without having to wait for Dropbox to approve every change.
2. Dropbox might want to keep their Java SDK backwards compatible.  By creating a separate Kotlin SDK, you are free to break compatibility to take advantage of Kotlin features.

**Comment by AliAzaz** [comment]
Sorry for the late reply to this convo.
 @cakoose you're right that Dropbox might want to keep their Java SDK backward compatible but maybe people who want kotlin code can't able to get my repo cause there would be no linking in my repo and main dropbox repo.
Currently, doing working in conversion code and will push all of my code in Kotlin branch, create PR and comment in this issue conversation that I converted code and if anyone wants it then they could directly get it from my repo.

**Comment by cakoose** [comment]
Just a heads-up in case you weren't aware: a lot of the SDK code is auto-generated from API specs.
- The API-to-code library: https://github.com/dropbox/stone
- The code generator backend for this SDK: https://github.com/dropbox/dropbox-sdk-java/blob/master/generator/java.stoneg.py
- The API specs: https://github.com/dropbox/dropbox-api-spec

When Dropbox makes changes to their API, they update the API specs and re-generate their SDKs.  You may or may not want to do the same thing for the Kotlin version.

**Comment by AliAzaz** [comment]
I'm only going to reconstruct android example from java --> kotlin

**Comment by cakoose** [comment]
Oh, I'm sorry, I misunderstood!  I thought you were converting the whole SDK.  🤦‍♂

**Comment by greg-db** [comment]
We've added a Kotlin example here: https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/DropboxAndroid
