### ISSUE TITLE
RetryException.html#getBackoffMillis documentation is not consistent

### ISSUE THREAD

**Issue by canburak** [dropbox/dropbox-sdk-java#278]
[RetryException.html#getBackoffMillis](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/RetryException.html#getBackoffMillis--) is inconsistently documenting "seconds" and "miliseconds". Please change seconds to miliseconds.

> Returns the number of **milliseconds** the client should backoff before retrying the request.

> backoff time, in **seconds**, before retrying the request, or 0 if the request can be retried immediately.

**Comment by greg-db** [comment]
Thanks for pointing that out! I'll ask the team to fix that up.
