### ISSUE TITLE
Recursive List Folder bad behaviour

### ISSUE THREAD

**Issue by riemann89** [dropbox/dropbox-sdk-java#281]
I am trying to recursively read from a Dropbox folder and I get the following strange behaviour: given 

```
var result: ListFolderResult =
  client.files().listFolderBuilder(folderPath)
    .withRecursive(true)
    .start
```

Sometimes `result.getHasMore == true`  but `result.getEntries` returns empty array, also it  `result.getHasMore` returns `false`, but we know there are more files (because we checked the counts).

Is there any API limit that could lead to this?

**Comment by greg-db** [comment]
First, to clarify, do you have [`listFolderContinue`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolderContinue-java.lang.String-) implemented? That's what you should use when [`getHasMore`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/ListFolderResult.html#getHasMore--) is `true`, regardless of how many entries were returned.

Please implement that as documented under [`listFolderBuilder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolderBuilder-java.lang.String-) if you haven't already. If you have implemented that and are still seeing unexpected results, please share the rest of the relevant code and the unexpected output you're getting. Feel free to [open an API ticket here](https://www.dropbox.com/developers/contact) instead if you'd prefer to share privately.

**Comment by riemann89** [comment]
Thanks for answering.

Yep, I use `result = client.files.listFolderContinue(result.getCursor)` to get other results in an iterative manner. The code works well but after fetching like 6000 files (this number can slightly change) I get `.getHasMore=True` and an empty list.

**Comment by greg-db** [comment]
Getting an empty entries list is possible in some cases. If `getHasMore` is `True` though you still need to proceed normally, i.e., call back to `listFolderContinue` again with the newly returned cursor. Does your code currently do so? What do you get back then?

**Comment by riemann89** [comment]
Hi Greg, just opened an API ticket, with some code in it.

> Does your code currently do so? What do you get back then?

Yep, there is `while` loop that is executed if I end up in the situation that `getHasMore=True` and `result.getEntries = List()`, but after a further call of `client.files.listFolderContinue(result.getCursor)`, `result.getHasMore` becomes `false`.

**Comment by greg-db** [comment]
Thanks! I'll close out this issue in favor of your ticket then. We'll follow up with you there.

**Comment by riemann89** [comment]
Writing this here since could be useful for other people: 

I have just found out that could be something related to the rights access, It's not actually the case because it should throw a `ListFolderErrorException` but using a different account I have found that I am able to read most of the content of the folder but still getting an empty list at a certain point.

**Comment by samthebest** [comment]
> Getting an empty entries list is possible in some cases. If getHasMore is True though you still need to proceed normally, i.e., call back to listFolderContinue again with the newly returned cursor. Does your code currently do so? What do you get back then?

Why is the API not returning reliably sized buffers?  Does other parts of the API also have unreliably filled buffers - like the reading of bytes?

This could cause inefficiencies, especially if this happens on file reading - could cause heaps of unnecessary CPU cycles.

Also, if `getHasMore = true` one expects a non-zero sized buffer to return, this is just standard expectation from an IO API.

**Comment by samthebest** [comment]
> I have just found out that could be something related to the rights access, It's not actually the case because it should throw a ListFolderErrorException but using a different account I have found that I am able to read most of the content of the folder but still getting an empty list at a certain point.

@riemann89   I agree, if you try to list a folder for which you do not have full permissions to see all files in that folder you should get an error, rather than the API ignoring those files.  Either the API should return a per-record error (e.g. MetadataError), or blow up the whole call.

Think like using `find` or `ls -R`, it will give "permission denied" to `stderr`.

**Comment by greg-db** [comment]
@samthebest This discussion was only referring to the RPC-style API calls for listing the contents of a folder. These calls are paginated, to support folder listings of any size, and due to various implementation details and variables on the backend, the size of any single page cannot be guaranteed, e.g., due to the activity on the specific account. This does not apply to calls for downloading file content.
