### ISSUE TITLE
Document minimum Android version

### ISSUE THREAD

**Issue by kenmorse** [dropbox/dropbox-sdk-java#285]
Does the Dropbox Java SDK have a minimum supported version of Android OS? I see the included Android example supports API version 19 but don't see this documented anywhere. (My apologies if I'm missing it).

**Comment by greg-db** [comment]
I believe that's the only place we currently document that, so please do consider Android 19 to be the minimum supported version of Android for the Dropbox SDK. I'll ask the team to clarify and better document this. Thanks!

**Comment by nilrambhad** [comment]
please let me know it is deprecated with android if not then it is supported to higher version android SDK.

**Comment by greg-db** [comment]
@nilrambhad I'm not sure I understand your question. Can you clarify?

**Comment by handstandsam** [comment]
We will be creating an Android Artifact in the 6.x version of this library next year that will contain information regarding a minSdk, and will be released as an Android Library.  In that version we will be aiming to have a `minSdk` of 21.

Here is the ticket tracking the addition of an Android Artifact: https://github.com/dropbox/dropbox-sdk-java/issues/446

I'm going to close this issue as the upcoming work in the attached ticket will include this.
