### ISSUE TITLE
Question: how check from the Metadata if a file is new or modified?

### ISSUE THREAD

**Issue by riemann89** [dropbox/dropbox-sdk-java#286]
Assuming that after I have fetched all file metadata by using the `ListFolder/ListFolderContinue` mechanism, I store last cursor and then after a while I start fetching again from the last cursor: from the new Metadata results am I able to differentiate if a file is new or just modification of an old one, without using any other side information (e.g. list of files fetched previously)?
Thanks

**Comment by greg-db** [comment]
Without comparing with your previously retrieved metadata, the Dropbox `Metadata` information doesn't offer a way to determine if the file is new or not. I'll pass this along as a feature request, but I can't promise if or when that might be implemented. 

You could call [`listRevisions`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listRevisions-java.lang.String-) to see the file version history, but that would require an extra API call for each file you want to check.
