### ISSUE TITLE
sdk-version version checking regex mismatch

### ISSUE THREAD

**Issue by anudeep3998** [dropbox/dropbox-sdk-java#29]
Hi. The regex in DbxSdkVersion.java is looking for strings of the form 1.8-a . Do you mean to enforce the trailing hyphen and subversion ? I'm getting LoaderErrors since the text file adk-version.txt only contains version strings like 1.8

**Comment by cakoose** [comment]
Yup, that's a bug.  The fixed version is on GitHub and Maven Central (v1.8.1).  The copy on "dropbox.com/developers" will be updated soon.
