### ISSUE TITLE
How to logout user with v2 API?

### ISSUE THREAD

**Issue by panovvitalik** [dropbox/dropbox-sdk-java#290]
I called client.auth().tokenRevoke(); - It's not working: current user is not logged out
Version: com.dropbox.core:dropbox-core-sdk:3.1.5

How I can resolve this issue?

Ofcourse I can press "Sign Out" link in the OAuth web page - and this will resolve the issue. But how I can do it forcelly from my android App?

**Comment by greg-db** [comment]
[The `tokenRevoke` method](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/auth/DbxUserAuthRequests.html#tokenRevoke--) only revokes the access token itself. The access token is not connected to the user's web session on www.dropbox.com (where the OAuth app authorization web page operates) though, so revoking one does not affect the other.

If the official Dropbox mobile app is not installed, the Dropbox SDK will send the user through the app authorization flow via their system browser, where they can manage their own web session. For example, they can choose to sign out of www.dropbox.com if they wish by clicking "Sign out", as you mentioned (or by manually browsing to www.dropbox.com/logout).

Also, note that if they are not already signed in to the Dropbox web site, when the user signs in during the OAuth app authorization flow, they will only receive "Session" cookies, so they will only stay signed in for the length of the "session" as determined by the browser.
