### ISSUE TITLE
Last modified user?

### ISSUE THREAD

**Issue by Deverlain** [dropbox/dropbox-sdk-java#291]
Is there a way to get name and/or id of user, who last modified specific file?

**Comment by greg-db** [comment]
Yes, for any [`FileMetadata`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/FileMetadata.html) you get for a file in a shared folder, such as from [`getMetadata`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#getMetadata-java.lang.String-), you can get the [`FileSharingInfo`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/FileSharingInfo.html) using [`FileMetadata.getSharingInfo`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/FileMetadata.html#getSharingInfo--). On the [`FileSharingInfo`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/FileSharingInfo.html) you can use [`FileSharingInfo.getModifiedBy`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/FileSharingInfo.html#getModifiedBy--) to get the account ID of the account that last modified the file. You can then use [`getAccount`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/users/DbxUserUsersRequests.html#getAccount-java.lang.String-) to look up the account information for that account ID.
