### ISSUE TITLE
Missing Security Policy

### ISSUE THREAD

**Issue by outsidecoder** [dropbox/dropbox-sdk-java#299]
There are no 'Security Advisories' identified in Github at the moment, however there is no Security Policy defined in Github.

**Comment by greg-db** [comment]
Thanks! I'll ask the team to add a Security Policy here.

**Comment by digitalbuddha** [comment]
Howdy ho @outsidecoder, do you have an example. I don't believe any of our repos have one and I cannot find one. Happy to run by legal if you have a starting point. Thank you kindly

**Comment by digitalbuddha** [comment]
closed due to inactivity
