### ISSUE TITLE
searchV2  file_extensions  don't work

### ISSUE THREAD

**Issue by yangjieK** [dropbox/dropbox-sdk-java#301]
I use dropbox Api 
I input options file_extensions: "jpg", but the result response files contains .pdf and .png.

**options:**
![image](https://user-images.githubusercontent.com/4345445/110596714-97772480-81ba-11eb-9073-86a05c97d82a.png)

**result:**
![image](https://user-images.githubusercontent.com/4345445/110596943-eae97280-81ba-11eb-8442-048b65a5daa9.png)

**Comment by greg-db** [comment]
Thanks for the report. This doesn't seem to be specific to the Java SDK though, and doesn't reproduce for me so, please [open an API ticket here](https://www.dropbox.com/developers/contact) from the affected account so we can check on it specifically for you. Thanks!
