### ISSUE TITLE
Any plans to make a separate, Java 7+ (or even 8+) API?

### ISSUE THREAD

**Issue by fge** [dropbox/dropbox-sdk-java#31]
From my understanding, the only reason that 6 is required is because of Android.

Does Dropbox have any plans to offer a more modern version of the API? Especially since it becomes harder and harder to lay one's hand on a Java 6 SDK implementation nowadays...

**Comment by smarx** [comment]
Are you saying you ran into an issue when you used the SDK with a more recent version of Java? The README claims "Dropbox Core SDK for Java 6+", so I would expect it to work with any version of Java 6 or higher.

**Comment by cakoose** [comment]
Are there specific improvements to the SDK you'd like to make using Java 7/8 language features?

**Comment by fge** [comment]
@smarx not at all; it is just that, well, this is 2015, and even Java 7 is EOL now...

@cakoose two things:

* make the download/upload classes implement `AutoCloseable` (Java 7+), and
* possibly, provide a `Stream<X>`, where `X` is to be determined, for directory listing.

For the second point, it is due to the fact that at the moment a directory listing may not be complete the first time and you have to do it again; sure, you can make your own `Iterator` for this, but then let's just go all the way and do streams, right? You can see an example of a `Spliterator<String>` I have written for my newer JSR 203 implementation over Dropbox (using the v2 API) here: https://github.com/fge/java7-filesystems/blob/master/java7-fs-dropbox/src/main/java/com/github/fge/fs/dropbox/driver/DropboxDirectoryListSpliterator.java

**Comment by cakoose** [comment]
Android is often the limiting factor: http://developer.android.com/about/dashboards/index.html#Platform

`AutoCloseable` requires Android API 19 or higher.  Roughly 1/3 of Android users are currently on a version older than that, and that's too big a number to drop support just yet.

There might be other solutions, though.  For example, Java's lazy-loading allows us to reference Android-specific classes in the SDK but have things still work for non-Android users.

**Comment by krieb** [comment]
@fge currently we have no plans to update the library for Java 7 or 8. As @cakoose mentioned, until we see a larger change in Android usage, we will continue to be Java 6 compatible.
