### ISSUE TITLE
Sample code problems

### ISSUE THREAD

**Issue by chk2902** [dropbox/dropbox-sdk-java#310]
- will the Android SDK sample code be updated to support the new SLT?

- will there be a sample for SLT file upload in the background? All references to the existing sample code are worthless or at least confusing as there's no "Activity" available for the background upload. Split in 2 parts: the part for the "initial" login (get credentials) which is the existing source code, and one part with the background upload task.

I have a user here which did the login successfully, but the upload fails with {"error_summary": "invalid_access_token/...", "error": {".tag": "invalid_access_token"}}

my client is created using

`DropboxClientFactory.getClient()`

with

```
public class DropboxClientFactory
    {
    public final static String  PREFS_CREDENTIAL   = "DBX.SLT_credential";
    public final static String  PREFS_ACCESS_TOKEN = "DBX.access_token";

    private static DbxClientV2 sDbxClient;

    public static void init(DbxCredential credential)
        {
        credential = new DbxCredential(credential.getAccessToken(), -1L, credential.getRefreshToken(), credential.getAppKey());
        if (sDbxClient == null)
            {
            sDbxClient = new DbxClientV2(DropboxRequestConfigFactory.getRequestConfig(), credential);
            }
        }

    public static void init()
        {
        SharedPreferences prefs = getAppContext().getSharedPreferences("dropbox", MODE_PRIVATE);

        String serializedCredential = prefs.getString(PREFS_CREDENTIAL, null);

        if (serializedCredential != null)
            {
            try
                {
                DbxCredential credential = DbxCredential.Reader.readFully(serializedCredential);
                DropboxClientFactory.init(credential);
                }
            catch (JsonReadException e)
                {
                throw new IllegalStateException("Credential data corrupted: " + e.getMessage());
                }
            }
        }

    public static DbxClientV2 getClient()
        {
        if (sDbxClient == null)
            {
            init();
            if (sDbxClient == null)
                {
                throw new IllegalStateException("Client not initialized.");
                }
            }
        return sDbxClient;
        }
    }
```

and then I use this client to upload the files.

**Comment by greg-db** [comment]
> will the Android SDK sample code be updated to support the new SLT?

[The Android example app included with the SDK](https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android) has already been updated to use short-lived tokens. It's actually written to support both and you can toggle the different code paths using [this `USE_SLT` variable](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/DropboxActivity.java#L20).

> will there be a sample for SLT file upload in the background?

Currently, there's just [this upload example code](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/UploadFileTask.java) in the Android example app. I can't guarantee exactly what other samples might be released in the future, but I'll pass this along as a feature request for one like you describe. I can't promise if or when that might be done though. 

> I have a user here which did the login successfully, but the upload fails with {"error_summary": "invalid_access_token/...", "error": {".tag": "invalid_access_token"}}

That indicates that the access token is currently invalid. For instance, the user may have unlinked app, etc. The app should prompt the user to reauthorize it if they want to continue using the integration.
