### ISSUE TITLE
com.dropbox.core.v2.DbxClientV2#refreshAccessToken - "Beta" indication meaning

### ISSUE THREAD

**Issue by martinNegriev** [dropbox/dropbox-sdk-java#325]
During a process of long-lived-to-short-lived access token migration, which will soon be mandatory, as explained in https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens, when going through the documentation of com.dropbox.core.v2.DbxClientV2, I noticed that the "refreshAccessToken()" method is indicated as *Beta* and that it shouldn't be used if not being an early access partner.
What are the actual risks that using this method poses and also, which method should be used if there is a need for refreshing the access token manually and not from an API call that does it internally (e.g. DbxUserFilesRequests#listFolder(java.lang.String))?

**Comment by greg-db** [comment]
[The `refreshAccessToken` method](https://dropbox.github.io/dropbox-sdk-java/api-docs/v4.0.0/com/dropbox/core/v2/DbxClientV2.html#refreshAccessToken--) is the right way to explicitly perform a refresh if needed. That method is no longer marked beta though. It sounds like you're using an old version of the SDK from when it was. It was marked beta in version >=v3.1.0 and <3.1.5. I recommend upgrading to the latest version, currently v4.0.0.
