### ISSUE TITLE
token expired before the millisecond that DbxCredential.getExpiresAt returns

### ISSUE THREAD

**Issue by winstonxie3000** [dropbox/dropbox-sdk-java#326]
According to the API document, DbxCredential.getExpiresAt return the millisecond when accessToken is going to expire. However, in some cases, the token has already expired before it. Please help look into it. Thanks.

**Comment by greg-db** [comment]
It sounds like you're describing [this issue](https://github.com/dropbox/dropbox-sdk-java/issues/294). That's been fixed, and the fix should be included in the next release.

**Comment by greg-db** [comment]
This is fixed in release [v4.0.1](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v4.0.1).
