### ISSUE TITLE
Is it possible to set Content type of a file (i.e mime type) using Dropbox API?

### ISSUE THREAD

**Issue by cheyrico2** [dropbox/dropbox-sdk-java#33]
I'm writing application and need to upload those document with their mime type.

**Comment by braincore** [comment]
Hi @cheyrico2,

Could you let us know what you're trying to accomplish by setting the mime type? Are you hoping to see it when retrieving the file's metadata or when downloading the file?

**Comment by cheyrico2** [comment]
I'm writing an application that will upload  a document to Dropbox and I was concerned whether a Dropbox user would be able to make sense of the file.

**Comment by krieb** [comment]
Hi @cheyrico2 

Generally we use filename extensions to determine how to preview a file to a user. If your application is uploading common file types (e.g. jpeg, pdf, txt, docx), you shouldn't have to worry about setting the content-type.

What type of files does your application upload?

**Comment by cheyrico2** [comment]
the application would upload .tiff, .pdf,  and .jpeg

**Comment by varenc** [comment]
Dropbox has no concept of file type outside of extension.  If the files you're uploading have the right extension then you should be all set!
