### ISSUE TITLE
Sharing files folders ..

### ISSUE THREAD

**Issue by houssemzaier** [dropbox/dropbox-sdk-java#34]
Hi hi guys,
I have used the SDK v1 to upload and share files and folders and it was quite easy.
I am wondering if it is the same for the version of sdk 2 .. knowing that it is still in beta4 . 
I have tested that code :

/**  **/
DbxRequestConfig config = new DbxRequestConfig("dropbox/java-tutorial", "en_US");
		DbxClientV2 client = new DbxClientV2(config, ACCESS_TOKEN);

ListFoldersResult shr_result = client.sharing.listFolders();
ArrayList<SharedFolderMetadata> shr_list = shr_result.entries;
for(SharedFolderMetadata shr_data : shr_list){
  System.out.println("Share Folder : "+shr_data.name);
}
/**  **/
and I have getting this error:
Exception in thread "main" com.dropbox.core.DbxException$BadRequest: Error in call to API function "sharing/list_folders": Your API app is an "App Folder" app. It is not allowed to access this API function.
 

/**  **/
Please can you share some samples about sharing data to public or to some restricted list of members.  
Thanks in advance

**Comment by cakoose** [comment]
That error means that the app key you're using is for an "App Folder" app.  These kinds of apps are not allowed to access the shared folder API.

To fix this, go to https://www.dropbox.com/developers/apps and click "Create app".  When it asks for the "type of access" you need, choose "Full Dropbox".

Feel free to re-open this issue if that doesn't work.

**Comment by juliocesarboll** [comment]
I'm using the SDK v2 and trying to share the folders. I've the "Full Dropbox" in the App's settings.
I tried the houssemzaier's cod but I needed to do some fixes...
`ListFoldersResult shr_result = client.sharing().listFolders();
ArrayList shr_list = shr_result.getEntries(); `

**Comment by juliocesarboll** [comment]
I'm using the SDK v2 and trying to share the folders. I've the "Full Dropbox" in the App's settings.
I tried the houssemzaier's cod but I needed to do some fixes...
`ListFoldersResult shr_result = client.sharing().listFolders(); `
`ArrayList shr_list = shr_result.getEntries();`
In the second line I'm not able to get the `result.getEntries()` to the `ArrayList`.
Thanks in advance.
