### ISSUE TITLE
Android: API not working with latest Dropbox App (258.2.2) on Android 11/12

### ISSUE THREAD

**Issue by jporta44** [dropbox/dropbox-sdk-java#354]
Apps cannot connect with latest Android Dropbox App installed, on devices running Android 11 or 12.
Even the sample app in this repo is not working. See attached screenshot for error.

![image](https://user-images.githubusercontent.com/1789361/140177165-5cfc6217-dda6-4635-8898-eadafb9cdda0.png)

**Comment by greg-db** [comment]
Thanks for the report! We're looking into it.

**Comment by developernotes** [comment]
Hi @greg-db 

We have also added the [`<queries>`](https://github.com/dropbox/dropbox-sdk-java#android-11-updates) change to our `AndroidManifest.xml` while using version `5.0.0` of the library, however, we are still seeing the same behavior reported by @jporta44. Have you been able to reproduce the issue?

**Comment by greg-db** [comment]
@developernotes Yes, and we're working on a fix on our side. I'll follow up once that's released.

**Comment by xiaozun3** [comment]
The installed version is the app version is 260.22.using version 5.0.0 of the library, I also encountered the same problem. Is it solved?

**Comment by greg-db** [comment]
@xiaozun3 This issue is not solved yet. I'll follow up here once I have news on it.

**Comment by beprogressive** [comment]
Same trouble starting from Android 11.

**Comment by greg-db** [comment]
@beprogressive Yes, that's correct, this issue affects Android 11+. We're working on a fix and I'll follow up here when it's released.

**Comment by beprogressive** [comment]
The problem fixed by migrating app to scoped in Dropbox console.

**Comment by greg-db** [comment]
@beprogressive I'm not aware of such a workaround, but for reference we are planning to have this fixed for both scoped and non-scoped apps.

**Comment by greg-db** [comment]
This should be fixed in the latest version of the official Dropbox Android app, v262.2.2. Please update to that and let us know if you're still seeing any issues. Thanks!

**Comment by developernotes** [comment]
Hi @greg-db 

Thanks for the update, I have verified the latest update to the Dropbox Android app resolved this issue. Thanks again!
