### ISSUE TITLE
How do you establish an HTTPS connection with Dropbox on Java JDK 1.6?

### ISSUE THREAD

**Issue by cheyrico2** [dropbox/dropbox-sdk-java#37]
I'm writing an API that will provide Dropbox services using the Java SDK for API v2. However, I'm running in to some issues when it comes to establishing an HTTPS connection with the SSL configuration provided by Dropbox.

Attempted Step 1: When I use the default configuration using the StandardHttpRequestor, I got a ClassCastException from the following:

    private HttpsURLConnection prepRequest(String url, Iterable<Header> headers) throws IOException
    {
        URL urlObject = new URL(url);
        HttpsURLConnection conn = (HttpsURLConnection) urlObject.openConnection(this.proxy);

with the following out exception

    java.lang.ClassCastException:            com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl 
    cannot be cast to javax.net.ssl.HttpsURLConnection  at 
    com.dropbox.core.http.StandardHttpRequestor.prepRequest(StandardHttpRequestor.java:150)  at 
    com.dropbox.core.http.StandardHttpRequestor.startPost(StandardHttpRequestor.java:75)  at 
    com.dropbox.core.http.StandardHttpRequestor.startPost(StandardHttpRequestor.java:23)  at 

Attempted Step 2: To resolve the ClassCastException I created a subclass to StandardHttpRequestor where I made the following change:

        URL urlObject = new URL(null, url, new sun.net.www.protocol.https.Handler());

And I received the following DbxException$NetworkIO from:

    public static HttpRequestor.Response startPostRaw(DbxRequestConfig requestConfig, String host, String path, byte[] body, /@Nullable/ArrayList headers) throws DbxException.NetworkIO {     String uri = buildUri(host, path);
    headers = addUserAgentHeader(headers, requestConfig);
    headers.add(new HttpRequestor.Header("Content-Length", Integer.toString(body.length)));
    
    try {
        HttpRequestor.Uploader uploader = requestConfig.httpRequestor.startPost(uri, headers);
        try {
            uploader.body.write(body);
            return uploader.finish();
        }
        finally {
            uploader.close();
        }
    }
    catch (IOException ex) {
        throw new DbxException.NetworkIO(ex);
    }

with the following out exception

    com.dropbox.core.DbxException$NetworkIO: 
    javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair  at 
    com.dropbox.core.DbxRequestUtil.startPostRaw(DbxRequestUtil.java:192)  at 
    com.dropbox.core.DbxRequestUtil.startPostNoAuth(DbxRequestUtil.java:164)  at 
    com.dropbox.core.DbxRequestUtil.doPostNoAuth(DbxRequestUtil.java:326)  at 
    com.dropbox.core.DbxWebAuthHelper.finish(DbxWebAuthHelper.java:43)  at 
    com.dropbox.core.DbxWebAuthNoRedirect.finish(DbxWebAuthNoRedirect.java:86)  at

**Comment by cakoose** [comment]
Can you add the line `System.getProperties().list(System.err)` right before calling `urlObject.openConnection(this.proxy)`, then copy/paste the output here?

**Comment by cheyrico2** [comment]
here you go

    [stderr] -- listing properties --
    [stderr] java.vendor=Sun Microsystems Inc.
    [stderr] dsdk.auth.permission.2cprint.support=false
    [stderr] org.osgi.service.http.port=8080
    [stderr] sun.management.compiler=HotSpot Client Compiler
    [stderr] xgp.dataPath=/hdd/ts/sdk/dsdk/xlet/336920832/home/
    [stderr] dsdk.util.appswitch.ext.support=true
    [stderr] dsdk.auth.input.cert.ext.support=true
    [stderr] dsdk.cvm.version=11.28
    [stderr] java.os.name=NetBSD
    [stderr] os.name=NetBSD
    [stderr] org.knopflerfish.framework.debug.errors=true
    [stderr] sun.boot.class.path=/mnt/usb4/sdk/16975872/lib/resources....
    [stderr] dsdk.auth.sasmgr.support=true
    [stderr] gsnx.version.major=2.3
    [stderr] org.knopflerfish.log.out=false
    [stderr] org.knopflerfish.prodver=3.3.6
    [stderr] dsdk.auth.extlimit.support=true
    [stderr] java.vm.specification.vendor=Sun Microsystems Inc.
    [stderr] java.runtime.version=1.6.0_21-final-b17_fix
    [stderr] dsdk.util.sysshutdown.support=false
    [stderr] org.knopflerfish.log.file=false
    [stderr] org.knopflerfish.log.level=info
    [stderr] dsdk.function.printplus.support=true
    [stderr] xgp.connectionTimeout=10000
    [stderr] dsdk.cipher.strength=0
    [stderr] user.name=dsdk
    [stderr] dsdk.xam.version=11.28
    [stderr] gsnx.version.minor=1.1
    [stderr] dsdk.activation=02.50
    [stderr] org.osgi.framework.system.packages=
    [stderr] org.knopflerfish.framework.debug.packages=false
    [stderr] org.knopflerfish.http.dnslookup=false
    [stderr] user.language=en
    [stderr] sun.boot.library.path=/mnt/usb4/sdk/16975872/lib/mips32
    [stderr] org.knopflerfish.framework.debug.startlevel=false
    [stderr] dsdk.auth=1.00
    [stderr] dsdk.vas.version=15.5
    [stderr] java.version=1.6.0_21-final
    [stderr] dsdk.system.LocaleServiceSupport=false
    [stderr] org.osgi.service.http.port.secure=51443
    [stderr] user.timezone=GMT-05:00
    [stderr] sun.arch.data.model=32
    [stderr] dsdk.ap=1.0.0,true,true
    [stderr] microedition.configuration=CLDC-1.1
    [stderr] dsdk.panel.colormode=LC_COLOR
    [stderr] java.endorsed.dirs=/mnt/usb4/sdk/16975872/lib/endorsed
    [stderr] sun.cpu.isalist=
    [stderr] sun.jnu.encoding=ISO646-US
    [stderr] file.encoding.pkg=sun.io
    [stderr] file.separator=/
    [stderr] java.specification.name=Java Platform API Specification
    [stderr] dsdk.auth.detection.papersizemode.support=false
    [stderr] java.class.version=50.0
    [stderr] user.country=US
    [stderr] org.knopflerfish.bundle.cm.store=cmdir
    [stderr] java.home=/mnt/usb4/sdk/16975872
    [stderr] java.vm.info=mixed mode
    [stderr] org.knopflerfish.startlevel.use=true
    [stderr] gsnx.region=exp
    [stderr] os.version=2.0.3_STABLE
    [stderr] gsnx.auth.internal.logout.timeout=15000
    [stderr] dsdk.function.scan.jpeg2000support=false
    [stderr] path.separator=:
    [stderr] dsdk.function.appcounter.extcounter.support=false
    [stderr] java.vm.version=19.0-b02
    [stderr] dsdk.machine.multilinkpanel=true
    [stderr] dsdk.function.print.color=FC
    [stderr] org.knopflerfish.http.secure.enabled=true
    [stderr] java.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol
    [stderr] org.knopflerfish.framework.debug.ldap=false
    [stderr] dsdk.full.version=11.28.3
    [stderr] dsdk.machine.serialcode=E154M261482
    [stderr] dsdk.function.print.maxsize=A3
    [stderr] java.awt.printerjob=sun.print.PSPrinterJob
    [stderr] sun.io.unicode.encoding=UnicodeLittle
    [stderr] org.osgi.provisioning.spid=knopflerfish
    [stderr] dsdk.function.scan.maxsize=A3
    [stderr] org.knopflerfish.startlevel.initlevel=8
    [stderr] dsdk.dsdk.version=11.28
    [stderr] dsdk.auth.billing.code.support=false
    [stderr] user.home=/mnt/usb4/sdk/16975872
    [stderr] dsdk.httpservice.ssl.isDisabledLessThan128BitKey=false
    [stderr] org.osgi.framework.dir=/mnt/usb4/sdk/common/fwdir
    [stderr] java.specification.vendor=Sun Microsystems Inc.
    [stderr] dsdk.function.printplus.pinch.support=true
    [stderr] org.knopflerfish.log.grabio=true
    [stderr] java.vendor.url=http://java.sun.com/
    [stderr] java.library.path=/mnt/usb4/sdk/common
    [stderr] gsnx.extendedProperties=true
    [stderr] java.vm.vendor=Sun Microsystems Inc.
    [stderr] org.knopflerfish.http.enabled=true
    [stderr] java.runtime.name=Java(TM) SE Runtime Environment
    [stderr] java.class.path=/mnt/usb4/sdk/16975872/lib/oswego.jar...
    [stderr] dsdk.cvm.bsversion=4.00
    [stderr] dsdk.auth.external.userid.support=true
    [stderr] nand.path=/mnt/usb4/
    [stderr] java.vm.specification.name=Java Virtual Machine Specification
    [stderr] java.vm.specification.version=1.0
    [stderr] sun.os.patch.level=unknown
    [stderr] sun.cpu.endian=big
    [stderr] java.awt.headless=true
    [stderr] java.net.preferIPv6Addresses=false
    [stderr] java.io.tmpdir=/hdd/ts/dsdk/var/tmp
    [stderr] dsdk.function.scan.searchablepdf.support=false
    [stderr] java.vendor.url.bug=http://java.sun.com/cgi-bin/bugreport...
    [stderr] gsnx.displayName=GlobalScan NX
    [stderr] dsdk.function.scan.autosizedetect.support=false
    [stderr] gsnx.version.postfix=
    [stderr] oscar.repository.url=http\://www.knopflerfish.org/repo/rep...
    [stderr] java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
    [stderr] os.arch=lpuxmips
    [stderr] xgp.xlet.productId=336920832
    [stderr] dsdk.panel.panelsize=WVGA
    [stderr] java.ext.dirs=/mnt/usb4/sdk/16975872/lib/ext:/usr/j...
    [stderr] user.dir=/sdk/sdk1/16975872/obj
    [stderr] jcifs.smb.client.dcResponseTimeout=5000
    [stderr] dsdk.function.scan.color=FC
    [stderr] org.knopflerfish.framework.bundlestorage.file.unpack=false
    [stderr] gsnx.edition=gsnx
    [stderr] dsdk.machine.system.version=3.12
    [stderr] dsdk.auth.service.support=TRUE
    [stderr] line.separator=
    
    [stderr] org.knopflerfish.gosg.jars=file:/mnt/usb4/sdk/common/jars/;file:...
    [stderr] java.vm.name=OpenJDK Client VM
    [stderr] dsdk.machine.scan.image.rotationtype=TYPE_A
    [stderr] dsdk.auth.cis.support=true
    [stderr] dsdk.function.scan.searchablepdf.languages=
    [stderr] dsdk.function.scan.jpegcompsetting.support=true
    [stderr] dsdk.machine.model.name=690001
    [stderr] dsdk.function=MFP
    [stderr] org.knopflerfish.framework.debug.classloader=false
    [stderr] xgp.installPath=/hdd/ts/sdk/dsdk/xlet/336920832/
    [stderr] xgp.soTimeout=30000
    [stderr] dsdk.imghlib.version=15.5
    [stderr] gsnx.type=p2p
    [stderr] file.encoding=ISO646-US
    [stderr] org.knopflerfish.verbosity=0
    [stderr] java.specification.version=1.6
    [stderr] org.osgi.framework.executionenvironment=CDC-1.0/Foundation-1.0,OSGi/Minimum-1.0
    [stderr] dsdk.panel.usb.keyboard.support=false

**Comment by cakoose** [comment]
This thread seems relevant: https://community.oracle.com/thread/1535882

Based on the information there, this is what I think is going on:
- JDK 1.3 and before didn't have SSL support built-in, but you could tell the JVM to use an external library by setting the System property `java.protocol.handler.pkgs` to
`com.sun.net.ssl.internal.www.protocol`.
- JDK 1.4+ has a built-in SSL library.  That's the library that the Dropbox SDK uses.
- In your setup, that System property is set, which causes `URL.openConnection()` to the external SSL library instead of the built-in one.
- These two libraries aren't compatible, which causes the `ClassCastException`.

I think the best option is to stop setting that System property.  I'm don't know how it's getting set, though... it may be somewhere in your code, configuration files, servlet container, etc.

**Comment by cheyrico2** [comment]
Thank you @cakoose , the underlying issue was related to the BouncyCastleProvider which doesn't support SSL. I was able to successfully establish connectivity using the normal Java SE 6.
