### ISSUE TITLE
Cannot use any classes from core package

### ISSUE THREAD

**Issue by VISWESWARAN1998** [dropbox/dropbox-sdk-java#375]
I have installed the SDK by adding the dependency given in the project home page and I can able to see the JAR file showing in the dependencies section of my IDE.

When I try to import one class for testing for example,

```java
import com.dropbox.core.DbxAccountInfo;
```

I get this error

```
[ERROR] /src/main/java/backup/dropbox/DropboxAccessToken.java:[10,24] cannot find symbol
[ERROR]   symbol:   class DbxAccountInfo
[ERROR]   location: package com.dropbox.core
```

**Comment by greg-db** [comment]
The `DbxAccountInfo` class is from an old version of the Dropbox API and should no longer be used. The equivalent class in the latest version is `FullAccount` which you can import like this:
```
import com.dropbox.core.v2.users.FullAccount;
```
You can find [an example here](https://github.com/dropbox/dropbox-sdk-java/blob/e52fc828c7c753e04c3fa9d47ab6de7e85d000c4/examples/account-info/src/main/java/com/dropbox/core/examples/account_info/Main.java).

**Comment by VISWESWARAN1998** [comment]
Even for this class same issue is coming, as I said I cannot use any classes!

**Comment by greg-db** [comment]
In that case, can you share more information about your setup? For instance, what IDE are you using, are you using Maven or Gradle, and what does your configuration look like? Do [the examples](https://github.com/dropbox/dropbox-sdk-java/tree/master/examples) work for you?

**Comment by VISWESWARAN1998** [comment]
I am using Netbeans IDE and maven

My IDE shows me this error:

![](https://i.imgur.com/TgbrssR.png)

However I can see the jar file in dependencies,

![](https://i.imgur.com/vkIkk3m.png)

I have this in my pom file

```
 <dependency>
            <groupId>com.dropbox.core</groupId>
            <artifactId>dropbox-core-sdk</artifactId>
            <version>5.1.1</version>
        </dependency>
```

Thank you very much!

**Comment by VISWESWARAN1998** [comment]
Tried mvn clean install as well in the command prompt without IDE, seeing the same error!

**Comment by greg-db** [comment]
I can't reproduce this issue using Maven in NetBeans to import v5.1.1 of the Dropbox SDK. The import (such as `import com.dropbox.core.v2.users.FullAccount;`) works successfully for me and I'm able to perform a Dropbox API call (`getCurrentAccount`).

Are you able to run [the example code](https://github.com/dropbox/dropbox-sdk-java/tree/master/examples)? Could you share a small sample project that reproduces the issue?

**Comment by VISWESWARAN1998** [comment]
Here is an example sample project: https://cdn.visweswaran.com/biz/dropboxtest.zip
My java version is: 

```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**Comment by greg-db** [comment]
Thanks for the sample and additional information. We bumped the Dropbox SDK's Java source and target compatibility to 11 in v5.1.0 of the SDK. Please try upgrading your Java version to 11, or downgrading to v5.0.0 of the Dropbox SDK.

**Comment by VISWESWARAN1998** [comment]
Thank you very much! it is working fine after downgrading to v5.0.0
