### ISSUE TITLE
How does the search endpoint work? Will this endpoint support regex?

### ISSUE THREAD

**Issue by cheyrico2** [dropbox/dropbox-sdk-java#38]
I seems that the it only returns matches where the word begings with the keyword by subtituting non-alphanumeric for space. I can find "Get Started with Dropbox.pdf" by searching the letter 'g' but i can't find it by searching 'e' (the second letter). I doesn't seem to provide result for contains keyword. 

1. Is my observation correct?
2. Do you plan to support regex?

**Comment by cakoose** [comment]
The [docs for /search](https://www.dropbox.com/developers/documentation/http/documentation#files-search) say:

> For file name searching, the last token is used for prefix matching (i.e. "bat c" matches "bat cave" but not "batman car").

So if you search for "g", you'll find all files with words that start with "g".  If you search for "e", you'll find files with words that start with "e".

BTW, for questions that aren't specific to the Java SDK, use the general [Dropbox API Development](https://www.dropboxforum.com/hc/en-us/community/topics/200209245-API-Development) forum.  More people will see it and you'll probably get a quicker response

**Comment by cheyrico2** [comment]
Thank you
