### ISSUE TITLE
Microsoft 365 documents

### ISSUE THREAD

**Issue by RiccardoManzan** [dropbox/dropbox-sdk-java#381]
Hello,
I'm developing an application that should execute some BL operations on microsoft documents (`.docx` like)
I would like to be able to know:
- If a docx file has been created by dropbox/office 365 integration, or uploaded manually
- If Office365 webapp is opened on file

I tried checking [dropbox http documentation](https://www.dropbox.com/developers/documentation/http/documentation) and this sdk methods, but i can't find anything that supplies me some the data i need.
Any advice is very much appreciated.

Thanks

**Comment by handstandsam** [comment]
@greg-db - Can you ensure that this request was passed on to the server team?  Because it is not part of our Java SDK specifically, I'm going to go ahead and close this issue since the request has been forwarded to the appropriate team.

**Comment by greg-db** [comment]
@handstandsam Yes, this is filed internally for the server.
