### ISSUE TITLE
gradle is missing 5.1.1  (4.0.1 works)

### ISSUE THREAD

**Issue by emilycrutcher** [dropbox/dropbox-sdk-java#382]
My system cannot find 5.1.1,  if I use 4.01, Gradle finds it with no problem.  Using 
	mavenCentral()
	maven { url "https://m2.objectdb.com" }
	maven { url 'https://repository.jboss.org/nexus/content/repositories/thirdparty-releases' }

Build scan: excerpt: 

compileClasspath
0.013s
com.dropbox.core:dropbox-core-sdk:5.1.1
FAILED
com.google.code.gson:gson:2.8.4
com.itextpdf:html2pdf:3.0.4
com.j2html:j2html:1.4.0
com.objectdb:objectdb:2.8.6
com.squareup.okhttp3:okhttp:4.4.1
edu.stanford.nlp:stanford-corenlp:4.2.2
io.undertow:undertow-core:2.0.11.Final
javax.jdo:jdo-api:3.0.1
net.bican:jwordpress:0.7.0
org.apache.commons:commons-email:1.5
org.slf4j:slf4j-jdk14:1.7.28
redstone.xmlrpc:xmlrpc:1.1.1

**Comment by greg-db** [comment]
It's not clear what the issue might be here. Is that the full error/output you get for that failure? Are you able to enable more verbose output? I just tried and I was able to load v5.1.1 in a project.

Also, can you share your gradle config and the steps you're following when this occurs?

For reference though, v5.1.1 of the library is available on Maven Central, according to their website: https://search.maven.org/artifact/com.dropbox.core/dropbox-core-sdk/5.1.1/jar as well as listed here: https://repo1.maven.org/maven2/com/dropbox/core/dropbox-core-sdk/5.1.1/

That said, this may be more of a matter of Gradle or Maven Central, so they may be able to offer more help.

**Comment by emilycrutcher** [comment]
If you can load it via gradle in maven central, then presumably it’s
something idiomatic to my config.

The odd thing was that gradle reported the artifact not to exist, even
though it clearly existed. If no one else has this problem in the next few
weeks, I’d ignore it if I was you. If anyone else has it, feel free to
reach out and I will pound on it some more :-)

I've attached my gradle config and here is the build scan
<https://scans.gradle.com/s/fpayilm2drqbq> in case it turns out that it is
worth debugging.

  Cheers,

        Emily

**Comment by greg-db** [comment]
Thanks! I just dug in to that a bit, and I found this message on [this page](https://scans.gradle.com/s/fpayilm2drqbq/dependencies?focusedDependency=WzAsMCwxOTcsWzAsMCxbMTk3XV1d&focusedDependencyView=dependencies_or_failure&toggled=W1swXSxbMCwwXSxbMCwxXSxbMCwyXSxbMCwzXV0#configurationId=0&projectId=0):
> Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

The team did [bump compatibility of the Java SDK to 11](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v5.1.0). So, it looks like you should be able to fix this either by upgrading to 11, if that's an option for you, or other instead requesting  v5.0.0 (or older) of the SDK.

**Comment by greg-db** [comment]
Thanks! I'll ask the team to update that.
