### ISSUE TITLE
allow_download missing 

### ISSUE THREAD

**Issue by mxmmarmol** [dropbox/dropbox-sdk-java#383]
SharedLinkSettings does not have the optional value allow_download. On the documentation this value is marked as optional but supported. Can be added to the sdk? This is important for both creating and updating links.

https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings
allow_download Boolean? Boolean flag to allow or not download capabilities for shared links. This field is optional.

**Comment by rogebrd** [comment]
It seems that the version of the api spec is currently outdated. I have brought this issue up with the owning team but can't make any promises on when it will be fixed.

**Comment by greg-db** [comment]
That's correct, this will require an update from Dropbox to get the SDK up to date to include that option.

**Comment by greg-db** [comment]
[`SharedLinkSettings.Builder.withAllowDownload`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.3.0/com/dropbox/core/v2/sharing/SharedLinkSettings.Builder.html#withAllowDownload(java.lang.Boolean)) is now available in the latest version of the Java SDK (currently v5.3.0).
