### ISSUE TITLE
uploading file to dropbox by parallelism

### ISSUE THREAD

**Issue by mengyuan1112** [dropbox/dropbox-sdk-java#384]
I would like to try to upload my file into dropbox account by chunks, and I would like to upload many chunks at the same time by using parallelism. @jgoldverg

I follow the reply from this link https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/parallel-upload-failing-quot-lookup-failed-incorrect-offset-quot/td-p/503800
> You can upload in parallel if you want, but you need to set session_type:concurrent and follow a few other constraints. 

I have tried to find **UploadSessionType.concurrent** and **UploadSessionStartArg.session_type** in objects **UploadSessionStartUploader** and **UploadSessionStartArg** follow by the document https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-start  but didn't find **concurrent** and **session_type** field.
> For better performance, you can instead optionally use a UploadSessionType.concurrent upload session. To start a new concurrent session, set UploadSessionStartArg.session_type to UploadSessionType.concurrent

How do l set **UploadSessionStartArg.session_type** to **UploadSessionType.concurrent** or is this field located in somewhere else?

**Comment by tidrop** [comment]
@mengyuan1112 unfortunately this is not currently available in our Java SDK. I have filed a request on your behalf to add this to the SDK. Will follow back up when this has been implemented.

**Comment by greg-db** [comment]
This functionality is now available in the latest version of the Java SDK (currently v5.3.0). For example:

- https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.3.0/com/dropbox/core/v2/files/UploadSessionType.html
- https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.3.0/com/dropbox/core/v2/files/UploadSessionStartBuilder.html#withSessionType(com.dropbox.core.v2.files.UploadSessionType)
- https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.3.0/com/dropbox/core/v2/files/DbxUserFilesRequests.html#uploadSessionStartBatch(long,com.dropbox.core.v2.files.UploadSessionType)
- https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.3.0/com/dropbox/core/v2/files/UploadSessionStartBuilder.html#withSessionType(com.dropbox.core.v2.files.UploadSessionType)

**Comment by jgoldverg** [comment]
Awesome thx so much :)
