### ISSUE TITLE
how to sync ?

### ISSUE THREAD

**Issue by TarasOryshhij** [dropbox/dropbox-sdk-java#39]
how to sync ? not download or upload. I need just sync database my app whith dropbox. i find tutorial:
https://www.dropbox.com/developers-v1/sync/start/android, but they deprecated. Thanks

**Comment by cakoose** [comment]
We no longer provide an SDK that handles sync for you.  If you want to accomplish this on your own, you probably want to try the [`/list_folder`](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder) endpoint.

1. First, call `/list_folder` with `{"recursive": true, "path": ...}`.  You'll get back a list of folder contents along with a `cursor` that keeps track of how much you've seen so far.
2. Then, periodically call `/list_folder/continue` to get updated folder contents along with a new `cursor`.

If you need further help with `/list_folder`, try the general [API development forum](https://www.dropboxforum.com/hc/en-us/community/topics/200209245-API-Development).
