### ISSUE TITLE
With recursive is returning only 12 results

### ISSUE THREAD

**Issue by shajiahmed** [dropbox/dropbox-sdk-java#393]
With the following statement 
result = getDbxClient().files().listFolderBuilder(folderPath).withRecursive(true).withLimit((long)20).start();
Actual result is limited to 12, it must return 20
even changing the order to 
result = getDbxClient().files().listFolderBuilder(folderPath).withLimit((long)20).withRecursive(true).start(); 
returns 12 
when I change to 
result = getDbxClient().files().listFolderBuilder(folderPath).withLimit((long)20).start();

Actual Result is returning 20 as expected.

**Comment by greg-db** [comment]
Is [`ListFolderResult.getHasMore()`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.2.0/com/dropbox/core/v2/files/ListFolderResult.html#getHasMore()) returning true? If so, you need to call back to [`listFolderContinue`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.2.0/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolderContinue(java.lang.String)) to retrieve more entries. You are not guaranteed to get all results back on a single call. Refer to the [`listFolder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.2.0/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolder(java.lang.String)) documentation for more information.

The "limit" you can set only enforces an approximate maximum number of entries to return per page; it does not guarantee a minimum number of entries to return.

**Comment by handstandsam** [comment]
It looks like the answer from @greg-db was the answer needed.  Closing this issue.  Feel free to re-open if this shouldn't have been closed yet.
