### ISSUE TITLE
Muting deletions and folder creation

### ISSUE THREAD

**Issue by jacobras** [dropbox/dropbox-sdk-java#40]
First off: I like the new SDK. It's a huge improvement over the old one, looking at the API.

When uploading a file it's possible to mute notifications using `UploadBuilder.mute()`. Are there any plans to make this functionality also available when deleting a file/folder and when creating a folder?

**Comment by greg-db** [comment]
Thanks for the feedback! I don't believe there are any immediate plans for that, but I'll be sure to pass this along as a feature request.

**Comment by jacobras** [comment]
Update one and a half year later: this is unfortunately still not possible with the latest version of the SDK (3.0.4). The SDK itself keeps getting better and better with every version though so I'm still hoping to see this feature in a future release.

**Comment by jacobras** [comment]
@greg-db any update on this? I think it would be a nice small improvement to make the mute option available for file deletion and folder creation/deletion.

**Comment by greg-db** [comment]
No, unfortunately I don't have any news on this request.
