### ISSUE TITLE
UploadSessionLookupErrorException replaced or removed?

### ISSUE THREAD

**Issue by NLLAPPS** [dropbox/dropbox-sdk-java#408]
Hi, just updated to 5.3.0 and noticed UploadSessionLookupErrorException was removed. Is there a replacement for it or was it simply removed?

**Comment by greg-db** [comment]
Yes, please use [`UploadSessionAppendErrorException`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.3.0/com/dropbox/core/v2/files/UploadSessionAppendErrorException.html) for `uploadSessionAppendV2`/`uploadSessionAppend` and `UploadSessionFinishErrorException` for `uploadSessionFinish`.
