### ISSUE TITLE
Emoji in the  file name

### ISSUE THREAD

**Issue by NLLAPPS** [dropbox/dropbox-sdk-java#42]
SDK throws error if the file name contains an Unicode emoji chars

`Error in call to API function "files/upload": path: invalid path: character at index X: not part of the Unicode Basic Multilingual Plane`

I don't think it is SDK's responsibility to sanitize file names. I am just posting it for other developers who might come across with the same issue

**Comment by greg-db** [comment]
Thanks for posting this! That's correct, Dropbox doesn't allow file names/paths with non-BMP unicode characters in general.

**Comment by jacobras** [comment]
Perhaps this should be mentioned in the documentation. If you allow user input as a filename in your app you will run into this issue (I also did, a while ago).

**Comment by srerickson** [comment]
+!
