### ISSUE TITLE
listfolder returning not last revision

### ISSUE THREAD

**Issue by network09** [dropbox/dropbox-sdk-java#43]
Hello,
playing with Java V2 API (version 2.0.1) I noticed a strange behavior:  listFolder seems to return back a previous "snapshot" of the folder content.

I created in one of the folder under my app the following files: sample.xml, test2,xml, test3,xml and test4,xml.

After some hours I deleted the file sample.xml, created the file test1.xml and overwrote the other remaning 3.

If a try to do a listfolder after the update I still get back the file sample.xml, test2.xml, test3,xml and test4.xml (even with the old content).

The same does not happen using Python API.
Am I doing something wrong with API?

Thank you
Simone

**Comment by greg-db** [comment]
Can you share the relevant code? Specifically, are you doing a new `listFolder` call each time, that is, without a `cursor`? The best way to stay up to date is to store the returned `cursor` and keep calling back to `listFolderContinue` using the latest `cursor`. Also, in any case, make sure you check `hasMore` on the result and call `listFolderContinue` again if it's `true`.

**Comment by network09** [comment]
I am doing just one call to listFolder, the code I am using is exactly the same of the tutorial:

`List<Metadata> entries = dbxClient.files().listFolder(folderPath).getEntries();
for (Metadata metadata : entries) {
    entityMetadataList.add(metadata);
}`

Using the following code in python a get a different result:

`import dropbox

dbx = dropbox.Dropbox(my_token)

for entry in dbx.files_list_folder(folder_path).entries:
    print(entry.name)`

**Comment by krieb** [comment]
The tutorial should updated to check if there are more results left and properly use the cursor. This doesn't explain the difference in response from Python and Java SDKs, though.

**Comment by network09** [comment]
Yes I agree, it does not explain the difference between the two APIs and moreover it does not explain why the java snippet above downloads also deleted files, which should not be retrieved unless explicitly requested.

**Comment by smarx** [comment]
@network09 Are you absolutely sure you're looking at the current output of the Swift code and that you're using the same account as the one you're using at in Python?

Both SDKs just call the same underlying HTTP API endpoint; it's not very likely that the API itself is returning different results depending on what language you're using.

**Comment by krieb** [comment]
I went ahead and verified that the JSON request being sent by both the Python and Java SDKs are the same, and they are:
```JSON
{
  "path": "",
  "recursive": false,
  "include_media_info": false,
  "include_deleted": false
}
```
I used the following calls:

**Python**
```Python
import dropbox
dbx = dropbox.Dropbox("<ACCESS_TOKEN>")
dbx.files_list_folder("")
```

**Java**
```Java
import com.dropbox.core.v2.DbxClientV2;
import com.dropbox.core.DbxRequestConfig;

DbxClientV2 dbx = new DbxClientV2(new DbxRequestConfig("test", "en_US"), "<ACCESS_TOKEN>");
dbx.files().listFolder("");
```

As @smarx said, can you verify you are using the same tokens for both code samples and can you  reproduce this?

**Comment by network09** [comment]
The token was the same, I found the issue on my code: I was looking into a different folder because of a typo in the folder name. The other "wrong" folder contains the previous versions of the files stored in the "right" folder.

Sorry for bothering you on this and thanks for the help.

**Comment by miroslav-inc** [comment]
> Can you share the relevant code? Specifically, are you doing a new `listFolder` call each time, that is, without a `cursor`? The best way to stay up to date is to store the returned `cursor` and keep calling back to `listFolderContinue` using the latest `cursor`. Also, in any case, make sure you check `hasMore` on the result and call `listFolderContinue` again if it's `true`.

This appears to be the case when there are lot of changes inside folder and for some reason (I guess internal handling) listFolder() is not returning all items but you have to call listFolderContinue() but this should be incorporated inside listFolder no?

**Comment by greg-db** [comment]
@miroslav-inc You are not guaranteed to get all results back from a single call to `listFolder` (or `listFolderContinue`). You need to always check `hasMore` on the result and call back again if it's true. This allows the interface to scale to folders of any size. Please refer to [the documentation](https://dropbox.github.io/dropbox-sdk-java/api-docs/v4.0.1/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolder-java.lang.String-) for more information on using this functionality.
