### ISSUE TITLE
Exception because of missing ProGuard rule: Couldn't find resource "trusted-certs.raw"

### ISSUE THREAD

**Issue by frigus02** [dropbox/dropbox-sdk-java#45]
I use the SDK in an Android app and after running ProGuard, the app crashed with the exception:

```
Caused by: java.lang.AssertionError: Couldn't find resource "trusted-certs.raw"
    at com.dropbox.core.a.b.a(Unknown Source)
    at com.dropbox.core.a.b.<clinit>(Unknown Source)
    at com.dropbox.core.a.c.a(Unknown Source)
    ....
```

This exception is thrown in [SSLConfig](https://github.com/dropbox/dropbox-sdk-java/blob/3cfa878e5d73f06ed4782c8833b229838fd21472/src/main/java/com/dropbox/core/http/SSLConfig.java#L306). I assume because the package names are obfuscated.

I was able to fix this by adding the following ProGuard rule. There might be a better, not so broad option, but I did not want to dig deeper here.

`-keeppackagenames com.dropbox.core.http`

It might be useful to include this info in the ProGuard section of the README.md.

**Comment by cakoose** [comment]
Oh, good catch.

I'm curious, does this option also work for you?
```
-adaptresourcefilenames com/dropbox/core/http/trusted-certs.raw
```

**Comment by frigus02** [comment]
Just tried your suggestion. Works like a charm and is probably better than my solution. Big thanks.
