### ISSUE TITLE
Set target compatibility to Java 8

### ISSUE THREAD

**Issue by dkocher** [dropbox/dropbox-sdk-java#476]
> The current release of Dropbox SDK Java supports Java 11+. If you are running Java 8 and want to use the SDK, you should user version `4.0.1`.

I see no reason to not compile with a 1.8 target. It would allow interoperability with [IKVM](https://github.com/ikvm-revived/ikvm). Would require a partial revert of 8af548f6.

**Comment by handstandsam** [comment]
A version with these Java 8 updates have been released as version `5.4.4` https://repo1.maven.org/maven2/com/dropbox/core/dropbox-core-sdk/5.4.4/

Thanks for letting us know about your issue!

**Comment by dkocher** [comment]
> Thanks for letting us know about your issue!

Many thanks for the quick turnaround. However it looks like this release does not include f1d3f6818976f32301c4a370bd0e1ff7f94c6df8 previously available.
