### ISSUE TITLE
How to identify if folder is shared?

### ISSUE THREAD

**Issue by dkhizhniakov** [dropbox/dropbox-sdk-java#480]
Hi there,

I face a pretty annoying inconvenience with the SDK. 
We at Graebert GmbH create a web app to allow users to work with their CAD files on the web. Currently we have an app that supports all kinds of different storages like Dropbox.
Because of that we have to keep at least somewhat consistent UI across different storages.
One of the features we have - we show different icon in the files' list for shared folders.
Unfortunately, with Dropbox we cannot find a proper way to implement it.

Basically we use `ListFolderBuilder` to get the folder content like this:
`ListFolderBuilder builder = dbxClient.files().listFolderBuilder(path).start();`
Then we iterate through objects and change the data to the format we're using.

So my question would be - how can we identify if some folder returned by this method is shared with someone?
We've been using this call to identify it: `folderInfo.getSharingInfo() != null`, but it's true only if folder has never been shared. 

E. g. 
- if I create folder "test" - it doesn't contain sharingInfo and the condition is false (as expected). 
- Now if I share it with some user - condition is true (as expected)
- If I remove user's share - condition is still true (expected to be false)

We can get the definitive answer using `dbxClient.sharing().listFolderMembers(folderInfo.getSharingInfo().getSharedFolderId())` but this causes an additional request which can be decremental to performance if user has a lot of folders, so this doesn't really seem as an option.

We're using dropbox-core-sdk v. 5.0.0. 
I've tried with more recent versions as well and wasn't able to find any solution either.
Any suggestions on how I can calculate the flag properly?

**Comment by greg-db** [comment]
Thanks for writing this up. You can check if a folder is a shared folder by checking if it has a shared folder ID in its sharing information. 

However, note that removing a member (or all members) from a shared folder does not make it no longer a shared folder. 

To make it no longer a shared folder, you would need to "unshare" it. You can do so via the Dropbox product (see [the help center article here](https://help.dropbox.com/share/unshare-folder) under "Unshare a folder") or via the API, using [`unshareFolder` in the Java SDK](https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.4.3/com/dropbox/core/v2/sharing/DbxUserSharingRequests.html#unshareFolder(java.lang.String,boolean)).
