### ISSUE TITLE
SDK mysteriously depends on Kotlin

### ISSUE THREAD

**Issue by luarvique** [dropbox/dropbox-sdk-java#483]
After using Gradle to build an Android app with the DropBox SDK 5.4.4 and trying to use DropBox, the app crashes as follows:

```
12-07 21:23:49.263 10363 10363 D AndroidRuntime: Shutting down VM
12-07 21:23:49.264 10363 10363 E AndroidRuntime: FATAL EXCEPTION: main
12-07 21:23:49.264 10363 10363 E AndroidRuntime: Process: com.fms.mg, PID: 10363
12-07 21:23:49.264 10363 10363 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
12-07 21:23:49.264 10363 10363 E AndroidRuntime: 	at com.dropbox.core.android.c$a.a(Unknown Source:2)
12-07 21:23:49.264 10363 10363 E AndroidRuntime: 	at com.dropbox.core.android.c.a(Unknown Source:2)
...
```
Please, help!

**Comment by greg-db** [comment]
You can find information on this here:

https://github.com/dropbox/dropbox-sdk-java#usage-on-android

Please follow that and let us know if you're still seeing any issues. Thanks!

**Comment by greg-db** [comment]
That should be [v5.3.0](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v5.3.0). You should be able to set that [like in this old copy of the readme](https://github.com/dropbox/dropbox-sdk-java/tree/6752bb288b619e71ee81860e5803bafa8fa98c09#java-version) (setting the version number accordingly).
