### ISSUE TITLE
DeletedMetadata.getPathDisplay() - lower case

### ISSUE THREAD

**Issue by jtrunick** [dropbox/dropbox-sdk-java#49]
This method seems to incorrectly returning .getPathLower() value. If the path display is not available, possibly DeletedMetadata should not support the method (no method or throw exception... maybe null?).

**Comment by greg-db** [comment]
Thanks! We'll take a look.

**Comment by greg-db** [comment]
In certain cases, this is expected from the API itself, per [the documentation](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.0.x/com/dropbox/core/v2/files/Metadata.html#getPathDisplay--):

> The cased path to be used for display purposes only. In rare instances the casing will not correctly match the user's filesystem, but this behavior will match the path provided in the Core API v1. Changes to the casing of paths won't be returned by DbxUserFilesRequests.listFolderContinue(String)

You can get get the expected casing by checking the name via [`getName`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.0.x/com/dropbox/core/v2/files/Metadata.html#getName--) for each path component though.
