### ISSUE TITLE
Jakarta (Servlet API)

### ISSUE THREAD

**Issue by cleemansen** [dropbox/dropbox-sdk-java#495]
Any plans to migrate the SDK to `jakarta`?

Without migrating from `javax.servlet` to `jakarta.servlet` the sdk is not usable by eg. [Spring Boot v3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee).

**Comment by greg-db** [comment]
The Dropbox Java SDK now uses jakarta as of [v6.0.0](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v6.0.0).
