### ISSUE TITLE
upload-file example error

### ISSUE THREAD

**Issue by AlicJ** [dropbox/dropbox-sdk-java#50]
[Relevent file](https://raw.githubusercontent.com/dropbox/dropbox-sdk-java/master/examples/upload-file/src/main/java/com/dropbox/core/examples/upload_file/Main.java)

On line 123, method `uploadSessionAppendV2` is undefined for type `DbxUserFilesRequests`. The possible fix, `uploadSessionAppend`, does not take argument of type `UploadSessionCursor`.

I encountered this error when importing this file into a Maven project I created in Eclipse.

**Comment by greg-db** [comment]
What version of the library do you have installed? The `uploadSessionAppendV2` method was only added in 2.0.2.

**Comment by AlicJ** [comment]
That's why. Thanks!
