### ISSUE TITLE
SDK not compatible with springboot 3

### ISSUE THREAD

**Issue by dgathibandhe** [dropbox/dropbox-sdk-java#513]
The class DbxStandardSessionStore imports HttpSession from javax which results into compatibility issue with projects that use springboot 3 as follows. The source code on the github does show import from jakarta but downloaded jars still contain javax. Could you please look into this?

![Screenshot 2023-10-05 093450](https://github.com/dropbox/dropbox-sdk-java/assets/79105611/ce1dda0c-94dc-494e-bd50-c2806835c31f)

**Comment by greg-db** [comment]
Thanks for the report. For reference, can you share which version number of the SDK you downloaded, and where you downloaded it from?

**Comment by dgathibandhe** [comment]
Thanks for the prompt reply! I am using the latest 5.4.6 and included the dependency in build.gradle of my project. I also tried downloading the source code zip file from github -> https://github.com/dropbox/dropbox-sdk-java/releases/tag/v5.4.6

**Comment by greg-db** [comment]
Thanks! I'll ask the team to look into it and I'll follow up here once I have any updates for you.

**Comment by dgathibandhe** [comment]
Appreciate it!

**Comment by devPalacio** [comment]
Hey @dgathibandhe, we haven't had the opportunity to fully release 6.0. The 6.0.0-SNAPSHOT uses the Jakarta namespace. You can find the snapshots here: https://s01.oss.sonatype.org/content/repositories/snapshots/com/dropbox/core/

**Comment by dgathibandhe** [comment]
Thanks! I guess, I will have to wait for the release to be able to add the dependency in the project.
