### ISSUE TITLE
Not able to fetch all files and folder.

### ISSUE THREAD

**Issue by pramodkr123** [dropbox/dropbox-sdk-java#520]
I am using this code to fetch folder and files. I have 40 files and folder in root folder, but I am getting only 25 from them.
I am using my app in 3 - 4 devices. Is any limitation from dropbox to access the all files and folder.

    DbxClientV2 mDbxClient = new DbxClientV2(DbxRequestConfigFactory.getRequestConfig(), accessToken);
                        try {
                            ListFolderResult listFolderResult= mDbxClient.files().listFolder("");

                            for (Metadata metadata : listFolderResult.getEntries()) {
                                String fileName = metadata.getName();
                                Log.i("Fetch File", "file: " + fileName);
                            }
                        } catch (DbxException e) {
                            e.printStackTrace();
                        }

**Comment by greg-db** [comment]
[Cross-linking for reference: [https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Not-able-to-fetch-all-files-and-folder/td-p/738518](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Not-able-to-fetch-all-files-and-folder/td-p/738518) ]

I see you also posted in the forum, so I'll follow up with you there.
