### ISSUE TITLE
How to use the same DbxPKCEWebAuth via session in PkceAuthorize?

### ISSUE THREAD

**Issue by li-exgen** [dropbox/dropbox-sdk-java#524]
Is there any solution to the lack of serialization support for storing DbxPKCEWebAuth as a spring session in redis.

**Comment by greg-db** [comment]
To clarify, are you building a server-side web app? PKCE is meant for client-side apps. If you have a server-side web app you should use `DbxWebAuth` instead; there's [an example of that here](https://github.com/dropbox/dropbox-sdk-java/blob/9d3744ce1817556e1859041cd7f4e99cd2024f9f/examples/examples/src/main/java/com/dropbox/core/examples/web_file_browser/DropboxAuth.java).

**Comment by li-exgen** [comment]
In order to achieve user provisioning from a SaaS web application to Dropbox, I am performing OAuth authorization on Dropbox's Development App.
The following error occurred.
java.lang.IllegalStateException: For native apps, please use DbxPKCEWebAuth

**Comment by greg-db** [comment]
If your app is a server-side web app, you should use [`DbxWebAuth`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.4.3/com/dropbox/core/DbxWebAuth.html), but that error can occur if you don't supply the app secret. Make sure you're supplying both the app key and secret when using that. You would do so using [`DbxAppInfo`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v5.4.3/com/dropbox/core/DbxAppInfo.html), like [here in that example](https://github.com/dropbox/dropbox-sdk-java/blob/9d3744ce1817556e1859041cd7f4e99cd2024f9f/examples/examples/src/main/java/com/dropbox/core/examples/web_file_browser/DropboxAuth.java#L136).

**Comment by li-exgen** [comment]
Provide App key and App secret in DbxWebAuth. Thank you.
