### ISSUE TITLE
No way to set force_reapprove for DbxWebAuth

### ISSUE THREAD

**Issue by anowell** [dropbox/dropbox-sdk-java#55]
I don't see a way to set `force_reapprove` in the java sdk when going through web auth. 

(maybe it's possible by injecting a ` HttpRequestor` into `DbxRequestConfig`, but I didn't particularly want to start down that road)

**Comment by krieb** [comment]
@anowell Which class are you using to handle your auth flow? `DbxWebAuth/DbxWebAuthNoRedirect` or the android `Auth` and `AuthActivity` helpers?

It certainly appears we can expose some more query options on the web auth classes.

**Comment by krieb** [comment]
Also, what is your intended use case? Is this primarily for testing?

**Comment by anowell** [comment]
I'm using `DbxWebAuth`. The use case is for a feature to be able to ingest Dropbox data into algorithm-based services, and/or save the results back to Dropbox. Currently we allow a user to add multiple dropbox connectors, either from the same dropbox account or different accounts because we have additional ways to restrict how each one is used within our service.

Anectodally, `force_reapprove` feels less magical when configuring a 2nd or 3rd dropbox connector, and helps in the case where you didn't realize you were signed into the wrong dropbox account when you started the workflow to connect to Dropbox. That said, I have yet to verify the behavior of "denying" reapproval, and if that would essentially revoke access from previously granted tokens, then that whole approach a non-starter as it could result in unintended consequences of breaking existing integrations. But for lack of a way to set `force_reapprove` with `DbxWebAuth`, I didn't have an easy way to experiment here, so for now I'm planning to just document that connecting additional Dropbox accounts may require explicitly signing out of Dropbox first.

**Comment by krieb** [comment]
Version **2.0.5** now supports the additional authorize query parameters, like `force_reapprove`. Use [DbxWebAuth.newRequestBuilder()](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.0.x/com/dropbox/core/DbxWebAuth.html#newRequestBuilder--) to build an authorize request with the optional parameters:
```
DbxWebAuth.Request request = DbxWebAuth.newRequestBuilder()
    .withRedirectUri(redirectUri, csrfTokenStore)
    .withForceReapprove()
    .build();
DbxWebAuth auth = new DbxWebAuth(requestConfig, appInfo);
String authUrl = auth.authorize(request);
// ...
DbxAuthFinish finish = auth.finishFromRedirect(redirectUri, csrfTokenStore, queryParams);
```
