### ISSUE TITLE
OAUTH2 login redirection gets stuck

### ISSUE THREAD

**Issue by activesince93** [dropbox/dropbox-sdk-java#552]
After noticing the auth redirection getting stuck on our app, I tried the same with the sample app. The behaviour is the same. Would you please help us fix this? Thank you!

Here's the recording,

https://github.com/user-attachments/assets/3f4e9784-b1f6-41c4-ad45-dbefb10506fb

**Comment by reumng120** [comment]
I have this issue too, can anyone else solve it?

**Comment by greg-db** [comment]
Thanks for the report! We're looking into it, and we'll follow up here once we have an update on this.

**Comment by greg-db** [comment]
This should be working again now. Thanks again for the report.
