### ISSUE TITLE
JSON parser alternatives

### ISSUE THREAD

**Issue by ened** [dropbox/dropbox-sdk-java#60]
Is it possible to exchange the JSON parser which the Dropbox SDK uses?

Right now it has a hard dependency on Jackson, however my project is already using gson and it would be beneficial to re-use the same dependency.

This would save another 2000 methods (from Jackson) or 1000 from gson. (dex method count).

**Comment by fgoinai** [comment]
[Fastjson](https://github.com/alibaba/fastjson)
I am using this. This only contains 968 methods.
[Ref](http://www.methodscount.com/?lib=com.alibaba%3Afastjson%3A1.1.52.android)

**Comment by krieb** [comment]
We have considered creating a basic JSON parsing interface, and then allow you to switch which implementation you want. We would likely make the Android built-in org.json the default implementation, and make jackson optional. This would help Android developers completely remove the JSON parser cost, while providing jackson for more performance-sensitive applications.

There is no timeline set for this. Currently we encourage developers to use ProGuard to strip unused SDK methods from their APKs, and multi-dex for large apps. Considering the majority of methods come from our bundled business endpoints, switching out the JSON parser is lower priority. Using ProGuard on the android debug example will cut Jackson method count to **706**. On the release example, it is even lower (**510**).
