### ISSUE TITLE
Open Authentication page in Browser 

### ISSUE THREAD

**Issue by ashishparmar** [dropbox/dropbox-sdk-java#63]
Hello,

 I am using drop box SDK and it is working fine but the problem only that when I launch authentication activity it is pass to the browser and open in full screen If it is possible to open in web view than I can control the UI part. 

Thanks in advance

**Comment by greg-db** [comment]
Hi @ashishparmar , I'm not sure I understand your post. Can you elaborate? For example, what platform are you using? Can you share the relevant code? Thanks in advance!

**Comment by ashishparmar** [comment]
Hello Greg K . Let take a scenario I am using a button for launch Authentication with DropBox . When I click on the button the authentication link redirects to the browser that I want to prevent it for user nice interface. And replacement of redirection  I want to use android web browser so I can handle its height and width and also handle event call .

**Comment by greg-db** [comment]
I see, so you want to open the app authorization page inside an in-app browser, inside your app, as opposed to opening it in the Android default system browser, so that you can control the surrounding UI. That's not currently available in the SDK, but we'll consider it a feature request.

**Comment by ashishparmar** [comment]
Hello Greg K
 I trying to do this for prevent open authenticate in default browser. And 60% success . When I complete this demo than i will tell you about the changes I hope this will help you. And you can changes in current SDK soon.

**Comment by ashishparmar** [comment]
Hello Greg K 
 I have achieved open authentication page in customizing dialog box . If need to change this in SDK than paste you email address I will send you updated file.

Thnks

**Comment by nahba** [comment]
@ashishparmar, Hi would you **please send me on agonchu@gmail.com**. I am implementing DropBox and facing the same issue. It opens in external browser and after authentication, the opened browser application stays there. So when I press back button on device, my screen gets closed and the opened browser application comes up.

It would be helpful to me if you send those changed files and help me to integrate.

Thanks.
Krunal

**Comment by greg-db** [comment]
@nahba This is an old issue where they were trying to implement the app authorization flow in an in-app browser/web view. This is no longer officially supported by [the Dropbox OAuth app authorization page](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize), so I don't recommend doing so.

If you're having trouble with the OAuth app authorization flow built in to the Java SDK, please [open a new issue](https://github.com/dropbox/dropbox-sdk-java/issues/new) with the details, e.g., the steps to reproduce the issue, etc., so we can look into it.

**Comment by nahba** [comment]
Hi @greg-db Thanks for the information. I am using 'com.dropbox.core:dropbox-core-sdk:3.0.8' with Android. It opens login page in separate web browser application. After providing login details, it asks to Allow or Cancel. After pressing Allow, it redirects to our application but when we press back button it shows the page where user has press Allow - the browser application. It breaks user experience. Kindly let me know how can I tackle with this issue.

**Comment by greg-db** [comment]
@nahba I see, thanks for clarifying. This is the expected behavior. When the user taps the back button after processing the app authorization flow, they are sent back to the previous app, which is the browser which contained the app authorization page in this case. I understand that this leftover page is non-ideal, but it shouldn't break the functionality of your app, and I unfortunately don't have a way to offer to close it automatically.
