### ISSUE TITLE
Sharing Files SDK v2

### ISSUE THREAD

**Issue by juliocesarboll** [dropbox/dropbox-sdk-java#64]
I'm using the SDK v2 and trying to share the folders. I've the "Full Dropbox" in the App's settings.
I tried the houssemzaier's cod but I needed to do some fixes...
`ListFoldersResult shr_result = client.sharing().listFolders();`
`ArrayList shr_list = shr_result.getEntries();`
In the second line I'm not able to get the `result.getEntries()` to the `ArrayList`.
Thanks in advance.

**Comment by greg-db** [comment]
What do you mean exactly when you say you're "not able to get the `result.getEntries()` to the `ArrayList`"? Are you getting an error?

**Comment by juliocesarboll** [comment]
I'm trying to give share permission to files but I don't know the way to do it, I fixed this cod above but it just list the files with permission. Do you have an example to guarantee permission ?

**Comment by greg-db** [comment]
You can use [`shareFolder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/sharing/DbxUserSharingRequests.html#shareFolder-java.lang.String-) to share a folder, and then [`addFolderMember`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/sharing/DbxUserSharingRequests.html#addFolderMember-java.lang.String-java.util.List-) to invite members to it.

(Or, for getting shared links to individual files, you can use [`createSharedLinkWithSettings`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/sharing/DbxUserSharingRequests.html#createSharedLinkWithSettings-java.lang.String-com.dropbox.core.v2.sharing.SharedLinkSettings-).)

**Comment by juliocesarboll** [comment]
Do you have an example for the method  `createSharedLinkWithSettings` ? 
Thanks in advance.

**Comment by greg-db** [comment]
I have a sample here:

https://stackoverflow.com/documentation/dropbox-api/414/getting-a-shared-link-for-a-file-or-folder/2414/creating-a-shared-link-for-a-file-using-the-dropbox-java-library#t=20160810170543135853

Hope this helps!

**Comment by greg-db** [comment]
If you want to revoke an existing shared link entirely, you can use [`revokeSharedLink`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/sharing/DbxUserSharingRequests.html#revokeSharedLink-java.lang.String-).

If you want to just change the visibility on an existing shared link, you can use [`modifySharedLinkSettings`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/sharing/DbxUserSharingRequests.html#modifySharedLinkSettings-java.lang.String-com.dropbox.core.v2.sharing.SharedLinkSettings-).
