### ISSUE TITLE
Error when using DbxRequestConfig

### ISSUE THREAD

**Issue by navintestapi** [dropbox/dropbox-sdk-java#65]
When using public DbxRequestConfig(String clientIdentifier) , I get the following error at run time:

_Exception in thread "Thread-1" java.lang.NoSuchMethodError: com.dropbox.core.DbxRequestConfig.<init>(Ljava/lang/String;)V_

However, using the deprecated version works fine:
public DbxRequestConfig(String clientIdentifier, /_@Nullable_/ String userLocale)

`DbxRequestConfig requestConfig = new DbxRequestConfig("MyApp/1.0");` does not work
`DbxRequestConfig requestConfig = new DbxRequestConfig("MyApp/1.0", "en-US");`works

**Comment by greg-db** [comment]
[Cross-linking for reference: https://stackoverflow.com/questions/39270059/error-when-using-dbxrequestconfig-in-sdk-2-1-1 ]

Thanks for the report. We'll look into it. You can build it this way instead though:

```
DbxRequestConfig requestConfig = DbxRequestConfig.newBuilder("MyApp/1.0").build();
```
Let me know if that doesn't work for you either.

**Comment by navintestapi** [comment]
Thanks. 
`DbxRequestConfig requestConfig = DbxRequestConfig.newBuilder("MyApp/1.0").build(); `
This works.
