### ISSUE TITLE
Android:  Auth.getOAuth2Token() always returns null

### ISSUE THREAD

**Issue by phileo** [dropbox/dropbox-sdk-java#71]
every time I call  Auth.getOAuth2Token(), it returns back null.
Any ideas as to what is going on there?

**Comment by phileo** [comment]
I think the reason getOAuth2Token() is returning null is because there is no Dropbox app installed on the device in question.
How would I implement browser auth for Android?  I took a look at this:
https://github.com/dropbox/dropbox-sdk-java/blob/7ecc15cf0f51d6ae2ba5cdb334aac2c2f3474b87/examples/web-file-browser/src/main/java/com/dropbox/core/examples/web_file_browser/DropboxAuth.java

However, Android does not have any "javax.servlet.XXXX" libs

**Comment by phileo** [comment]
AuthActivity.startWebAuth() is not complying with:
https://www.dropbox.com/developers/reference/oauth-guide

startWebAuth() needs to startActivityWithResult() instead of startActivity(), but I'm a bit confused as to how AuthActivity will receive the bearer Token from /oauth2/token   .....?

**Comment by greg-db** [comment]
Hi @phileo , the file you linked to in your second comment is for the web file browser example, which is intended for server-side apps, not Android apps. 

There's an example for Android apps here: https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android

That example shows how to use `startOAuth2Authentication` to kick off the app authorization flow on Android. That will automatically use the browser if the official app isn't installed:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/UserActivity.java#L33

**Comment by Harin-Kaklotar** [comment]
@greg-db but what if I want go with OAuth2 flow using app key and app secret, how can I get access token?

**Comment by bazimogmbh** [comment]
@Harin-Kaklotar 
Use this to start the Oauth2flow , note only key is needed.
  ` Auth.startOAuth2Authentication(activity, DROPBOX_KEY);  `

and in your activity onResume method

```
@Override
   protected void onResume() {
    super.onResume();
   String accessToken  = Auth.getOAuth2Token();
}

```

This will provide you the access token after successful oAuth flow, and you should save it e.g in sharedpreferences.

**Comment by Harin-Kaklotar** [comment]
@bazimogmbh thanks buddy 👍  you are right

**Comment by g-martins** [comment]
Hey @Harin-Kaklotar or @phileo did you get this to work? I'm going through the same issue, although, if I have the app installed on the device it works perfectly whereas from the browser it always return null. 

Any thoughts anyone?


Thanks

**Comment by greg-db** [comment]
For the reference of anyone finding this, @g-martins resolved this here: https://github.com/dropbox/dropbox-sdk-java/issues/161
