### ISSUE TITLE
DbxUploader#uploadAndFinish() does not throw IOException

### ISSUE THREAD

**Issue by ksatoudeveloper** [dropbox/dropbox-sdk-java#75]
DbxUploader#uploadAndFinish()'s Javadoc say 

> throws IOException if an error occurs reading the input stream.

But if InputStream throw IOException, DbxUploader#uploadAndFinish() throw NetworkIOException.

**Comment by greg-db** [comment]
Thanks for the report!

**Comment by ksatoudeveloper** [comment]
Is this a bug in the documentation?
Is this a bug in the code?

**Comment by zjiuyang** [comment]
It a bug in the code. Which http requestor do you use? I can try to write a fix for standard one. But it's hard to fix for OkHttp because we have no control to the underline sink. (So we can't tell the difference between IOExceptions from reading or writing)

**Comment by zjiuyang** [comment]
Fix pushed to master. Should apply in next release.

**Comment by ksatoudeveloper** [comment]
Thank you for fixing.
I'm using StandardHttpRequestor.

Would you write DbxUploader#uploadAndFinish()'s Javadoc about HttpRequestor?

**Comment by greg-db** [comment]
@ksatoudeveloper Can you elaborate on what you're looking for? The [`uploadAndFinish`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/DbxUploadStyleBuilder.html) documentation/example isn't specific to a particular HTTP requestor.

**Comment by greg-db** [comment]
This should be fixed now in [v3.0.0](https://github.com/dropbox/dropbox-sdk-java/releases/tag/3.0.0):

> Fix the bug that when InputStream throws IOException, DbxUploader#uploadAndFinish() throws NetworkIOException
