### ISSUE TITLE
No way to get_metadata via fileId or folderId

### ISSUE THREAD

**Issue by lesongjia** [dropbox/dropbox-sdk-java#76]
Is there any way to get_metadata using fileId or folderId? In my case, we need to lookup metadata via a consistent id. File path can be changed. 

Or, is there any way that I can lookup file path using fileId?

Thanks,
Lesong

**Comment by greg-db** [comment]
Yes, you can use [`getMetadata`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#getMetadata-java.lang.String-) to look up a file or folder by ID by supplying the ID string as the `path` parameter, which would look like, "id:i8PhgWY5-aAAAAAAAAAAAQ".

**Comment by lesongjia** [comment]
Cool, thanks!
