### ISSUE TITLE
NPE when initialize AddFolderMemberError

### ISSUE THREAD

**Issue by lesongjia** [dropbox/dropbox-sdk-java#77]
On com.dropbox.core.v2.sharing.AddFolderMemberError.java

line 137 and 138, define tooManyMembersValue and tooManyPendingInvitesValue as as primitive long.

Then, on the constructor, unboxing Long to primitive long. This will cause NullPointerException when (Long) null is passed. 

And actually when init all error instance in the same class, (Long) null is passed to constructor. This is actually causing NPE. 

When I tried the failure case in API Explorer v2 for https://api.dropboxapi.com/2/sharing/add_folder_member, 500 is returned.

**Comment by greg-db** [comment]
Thanks for the report @lesongjia ! Can you share a screenshot showing the parameters you're using to get a 500 from /2/sharing/add_folder_member in the API Explorer so we can make sure we reproduce exactly what you're seeing? (Just make sure to hide your access token.) Thanks in advance!

**Comment by lesongjia** [comment]
@greg-db I tried just right now with the same case I did yesterday. It worked in the API Explorer now. Wonder anything is released maybe. But I still have the same problem in my app with dropbox-core-sdk:2.1.2. 

The case I am testing is basically pass the folderId (not share folder id) with a valid member. Then, NPE is thrown when initialize AddFolderMemberError. 

Let me know if you need more detail. I can share a sample project if you want to.

**Comment by greg-db** [comment]
Thanks, in that case, the code you're using to reproduce this would be helpful. Thanks in advance!

**Comment by lesongjia** [comment]
@greg-db I made a simple app, just to provide any access token there. You will see the NPE. 
[error-sample.zip](https://github.com/dropbox/dropbox-sdk-java/files/554484/error-sample.zip)

Let me know if this helps.

**Comment by greg-db** [comment]
Thanks, that's helpful! We'll look into it.

**Comment by lesongjia** [comment]
Hey @greg-db Is there any ETA for this? Thanks

**Comment by greg-db** [comment]
I don't have an ETA for a fix for this unfortunately.

**Comment by handstandsam** [comment]
Cleaning up our issue tracker and this hasn't had activity in 6 years.  Please re-open if it's still an issue.
