### ISSUE TITLE
500 when trying to add folder member as viewer_no_comment accessLevel

### ISSUE THREAD

**Issue by lesongjia** [dropbox/dropbox-sdk-java#79]
When I try to add a member as viewer_no_comment to a shared folder as the owner, I got a 500 error in the API Explorer. 

My testing account is a dropbox business account, FYI. 

![2016-10-26_1701](https://cloud.githubusercontent.com/assets/1310843/19746425/74cddf60-9ba4-11e6-8f16-ba0148769f22.png)

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by greg-db** [comment]
This should be fixed now. Performing this call should now return a proper 409 error indicating that this functionality is not yet available.
