### ISSUE TITLE
how to set socks5 proxy in http request

### ISSUE THREAD

**Issue by marksnoopy** [dropbox/dropbox-sdk-java#83]
i can not find  how to set socks5 proxy in http request , it supports or  not ?

**Comment by marksnoopy** [comment]
i find some ways to reslove it  like this .
```
Config config = Config.builder().withProxy(<PROXY>).build();
StandardHttpRequestor requ = new StandardHttpRequestor(config);

DbxRequestConfig dbxRequestConfig = DbxRequestConfig.newBuilder("test").withHttpRequestor(requ).build();
DbxClientV2 client = new DbxClientV2(dbxRequestConfig, <ACCESS_TOKEN>);
```
`<PROXY>` is a socks proxy and it is available.
`<ACCESS_TOKEN>` is access token.

run and report timeout , what wrong ?

in addition , i can not understand what is the param `clientIdentifier` in class `DbxRequestConfig` .

**Comment by greg-db** [comment]
The `clientIdentifier` should be a string that identifies your app and version. We'll update the documentation to clarify this.

For reference, the client identifier is usually of the form "SoftwareName/SoftwareVersion". For example, if you have a project named "PhotoEdit", your might set the client identifier to "PhotoEditServer/1.3" in your server software and to "PhotoEditAndroid/1.8" in your Android app. This value is prepended to the ["User-Agent" HTTP header](https://tools.ietf.org/html/rfc7231#section-5.5.3) on all requests made to the Dropbox API.  This has no effect on the behavior of the Dropbox API, but it may help identify your application when debugging things later.

I'm not sure offhand what the issue with the proxy may be, but we'll take a look.

**Comment by marksnoopy** [comment]
@greg-db thanks, and i had solved the problme ,it looks fine

**Comment by marksnoopy** [comment]
i means i set the proxy  , but it seems no effets .

**Comment by marksnoopy** [comment]
i use the proxy in google api client sdk and it looks fine

**Comment by zjiuyang** [comment]
Hey @marksnoopy I just used my local dante server as my proxy, and it worked fine. Can you share more information with us? Do you still see any exception?

**Comment by handstandsam** [comment]
To setup a proxy, I would recommend using the OkHttp3Requestor https://github.com/dropbox/dropbox-sdk-java/blob/8b7d6b902a2394f0ef27ac53187ba388e6baf280/dropbox-sdk-java/src/main/java/com/dropbox/core/http/OkHttp3Requestor.java.  You can pass it a configured OkHttp instance which is set up to use a proxy.  The "requestor" is a abstraction layer to allow for multiple Http implementations.
