### ISSUE TITLE
How to cancel a upload

### ISSUE THREAD

**Issue by wangbourne** [dropbox/dropbox-sdk-java#87]
In V1 API, we can use "mUploadRequest.abort();" to cancel a uploading request.
Is there a similar way in V2? Below is my codes for uploading function. 

```
InputStream inputStream = new FileInputStream(mFile);
DbxClientV2    dbxClient = DropboxAuthHelper.getClient();
return dbxClient.files().uploadBuilder(mFilePathInDropbox)
                    .withMode(WriteMode.OVERWRITE)
                    .uploadAndFinish(inputStream);
```

**Comment by greg-db** [comment]
If you get an [`UploadUploader`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/files/UploadUploader.html), e.g., as returned by [`UploadBuilder.start`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/files/UploadBuilder.html#start--), you can call [`DbxUploader.abort`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/DbxUploader.html#abort--).
