### ISSUE TITLE
how to sign out

### ISSUE THREAD

**Issue by wangbourne** [dropbox/dropbox-sdk-java#89]
I got to know from this issue([https://github.com/dropbox/dropbox-sdk-java/issues/54](url)) that i can use following code to sign out

```
try {
                        sDbxClient.auth().tokenRevoke();
                    } catch (DbxException e) {
                        e.printStackTrace();
                    }
```

my question is: once revoked, how i can confirm whether it's truely revoked or not. From my understanding, Auth.getOAuth2Token() should return null. However, the truth is it still return a token seems correct.

I know in v1 Dropbox APIs, we have "**mApi.getSession().isLinked();**" to get status. Is there any similar in v2?

**Comment by greg-db** [comment]
The [`tokenRevoke`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/auth/DbxUserAuthRequests.html#tokenRevoke--) method revokes the token on the server. If you want to verify that the revoke operation worked, you can then attempt another call, e.g., [`getCurrentAccount`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/users/DbxUserUsersRequests.html#getCurrentAccount--) using the same client.

(The `getOAuth2Token` method is just for getting the returned token from the authorization activity, and doesn't check it against the server. That's similar to how the old `isLinked` method only checked for the existence of a token, and not whether or not it was revoked.)

**Comment by wangbourne** [comment]
got it.
However, I have to say, compared with v1 API,  it's not that convenient to get status. In V1, we can simply do:
1. log out: mApi.getSession().unlink();
2. check whether logged out or not: mApi.getSession().isLinked()
