### ISSUE TITLE
How to logout user with v2 API?

### ISSUE THREAD

**Issue by kkontus** [dropbox/dropbox-sdk-java#92]
Is it possible to logout current user so new user can login through v2 API?

**Comment by cakoose** [comment]
What do you mean by "log out"?  Are you writing a mobile/web app and you want to connect to a different Dropbox account?  Or are you talking about logging someone out of the Dropbox website?

**Comment by kkontus** [comment]
I'm writing an Android app from which user can upload some photos and stuff. So user log in through Java Dropbox APIv2 and everything works great. But let's say he wants to login with another Dropbox account, how can he log out/sign out (whatever you prefer) so he can use another user account. For now I just removing AccessToken from the SharedPrefs and run  Auth.startOAuth2Authentication(..., ...) again, but I'm not sure if that is a correct way because that doesn't really log out user from the server. So how can I get the same behavior that I have when I click Sign out from browser on www.dropbox.com?

**Comment by cakoose** [comment]
What you are doing is correct.

If you also want the Dropbox API server to delete its copy of the access token, call [`/disable_access_token`](https://www.dropbox.com/developers-v1/core/docs#disable-token).  In the Java SDK, this is [`DbxUserAuthRequest.tokenRevoke()`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/auth/DbxUserAuthRequests.html#tokenRevoke--).

**Comment by kkontus** [comment]
Works like a charm, thanks a mill. I'm closing this since it's solved now.

**Comment by kkontus** [comment]
@cakoose there is one more thing that has to be done in order for user to be Sign out on Android. We need to set `DbxClientV2 sDbxClient = null;` and set `AuthActivity.result = null; `otherwise old client will be reused and calling `accessToken = Auth.getOAuth2Token();` in `onResume()` will return old token. So here is what I did, maybe it can help someone:

Called:
1)  `DbxUserAuthRequests.tokenRevoke();` - to revoke token on the server
2)  cleared SharedPrefs locally (the ones that are checked in hasToken() method)
3) set DropboxFactory client to null since ` new GetCurrentAccountTask(DropboxClientFactory.getClient(), new GetCurrentAccountTask.Callback() { ... }` would reuse old client that is initialized with a token that is now revoked, and `onError()` callback method would be called. 
since `DbxClientV2 sDbxClient` is private I created a new method inside `DropboxClientFactory` as
```
public static void clearClient() {
    sDbxClient = null;
}
```
4)  `AuthActivity.result = null;` which prevents restoring accessToken from DropboxApi internal SharedPrefs using `accessToken = Auth.getOAuth2Token();` in `onResume()`

I hope it helps someone.
Cheers

**Comment by mr-cpp** [comment]
@kkontus 
`DbxUserAuthRequests.tokenRevoke();` is not a static method today. So the only way is something like this:
`new DbxUserAuthRequests(/* here is needed a DbxRawClientV2 client */).tokenRevoke();`
So on android i cannot find the way to receive an instance of DbxRawClientV2 class  
Can you help?

**Comment by greg-db** [comment]
@mr-cpp You should be able to call that with a `DbxClientV2`, like this, where `client` is a `DbxClientV2`:

```
client.auth().tokenRevoke();
```

If that's not working for you though, feel free to [open a new issue](https://github.com/dropbox/dropbox-sdk-java/issues/new) with details so we can help.

**Comment by mr-cpp** [comment]
@greg-db
Thank you
It works. But it requires async execution, so i wrote a simple class `RevokeToken`  for execution Dropbox API
https://gist.github.com/mr-cpp/3a5d39430f1f1506abe0257f352e70b7

**Comment by panovvitalik** [comment]
@greg-db
I called client.auth().tokenRevoke(); - It's not working: current user is not logged out
Version: com.dropbox.core:dropbox-core-sdk:3.1.5

How I can resolve this issue?

**Comment by greg-db** [comment]
@panovvitalik I see you also opened a new issue for this, so I'll follow up with you the: https://github.com/dropbox/dropbox-sdk-java/issues/290
