### ISSUE TITLE
check and Create folder

### ISSUE THREAD

**Issue by nzala** [dropbox/dropbox-sdk-java#94]
check if folder exists in android

**Comment by greg-db** [comment]
To check if anything already exists at a particular path, you can use [`getMetadata`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#getMetadata-java.lang.String-). It will return the metadata of any existing item, or raise an exception if nothing is found.

If you know you want to try to make a folder though, you can just use [`createFolder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#createFolder-java.lang.String-). It will create the folder and return the resulting metadata if it's successful, or raise an exception if something already exists there.
