### ISSUE TITLE
check if user manually revoke token

### ISSUE THREAD

**Issue by nzala** [dropbox/dropbox-sdk-java#95]

**Comment by greg-db** [comment]
You can attempt an API call to see if the access token is still working. If it's been revoked, the call will raise an [`InvalidAccessTokenException`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/InvalidAccessTokenException.html), like this:

```
try {
    FullAccount account = client.users().getCurrentAccount();
    System.out.println(account.getName().getDisplayName());
} catch (InvalidAccessTokenException e) {
    System.out.print("Invalid access token exception: " + e);
}
```
