### ISSUE TITLE
BadTokenException

### ISSUE THREAD

**Issue by gattacus** [dropbox/dropbox-sdk-java#96]
Android 6.0.1
dropbox-core-sdk:2.1.1
02-19 17:27:47.309 E/AndroidRuntime(24865): android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
02-19 17:27:47.309 E/AndroidRuntime(24865):     at android.view.ViewRootImpl.setView(ViewRootImpl.java:853)
02-19 17:27:47.309 E/AndroidRuntime(24865):     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:337)
02-19 17:27:47.309 E/AndroidRuntime(24865):     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
02-19 17:27:47.309 E/AndroidRuntime(24865):     at android.app.Dialog.show(Dialog.java:350)
02-19 17:27:47.309 E/AndroidRuntime(24865):     at android.app.AlertDialog$Builder.show(AlertDialog.java:1113)
02-19 17:27:47.309 E/AndroidRuntime(24865):     at com.dropbox.core.android.AuthActivity.checkAppBeforeAuth(AuthActivity.java:256)
02-19 17:27:47.309 E/AndroidRuntime(24865):     at com.dropbox.core.android.Auth.startOAuth2Authentication(Auth.java:14)

**Comment by greg-db** [comment]
@gattacus Can you share the relevant code and steps to reproduce this issue? Thanks in advance!

**Comment by gattacus** [comment]
Hi
I used the same app key in your android demo app and in my app. It was then triggered by calling
`Auth.startOAuth2Authentication(context, context.getString(R.string.dropbox_app_key));`

**Comment by greg-db** [comment]
Do you mean you put in your own app key? The Android example app included in the Java SDK doesn't come with an app key, and has you [enter your own](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/res/values/strings.xml#L4).

In any case, based on the stack trace the error has to do with the Android view system, so the Dropbox API app key likely doesn't itself matter

What exactly is your `context` variable though? Your code looks different than the [example code](https://github.com/dropbox/dropbox-sdk-java/blob/7ecc15cf0f51d6ae2ba5cdb334aac2c2f3474b87/examples/android/src/main/java/com/dropbox/core/examples/android/UserActivity.java#L33), which has:

`Auth.startOAuth2Authentication(UserActivity.this, getString(R.string.app_key));`

Try using it like that instead.
