### ISSUE TITLE
Update API spec to include Paper

### ISSUE THREAD

**Issue by posita** [dropbox/dropbox-sdk-java#97]
There's a new API spec (dropbox/dropbox-api-spec@4483042b0016788742a1c4233a56e163e65b3121) that contains the paper endpoints. Consider updating this SDK.

**Comment by koliyo** [comment]
Why was this closed?

**Comment by greg-db** [comment]
@koliyo The Java SDK now supports the Paper endpoints:

https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/paper/DbxUserPaperRequests.html
