### ISSUE TITLE
Need ability to 'finishFromCode' and pass redirect URI and state parameters

### ISSUE THREAD

**Issue by stacysimpson** [dropbox/dropbox-sdk-java#99]
When utilizing the response_type=code path, we need the ability to pass this information when acquiring an access token. Today the SDK doesn't expose the necessary API. The underlying method 'finish' is private.

**Comment by cakoose** [comment]
Is your use-case similar to the [authorize example](https://github.com/dropbox/dropbox-sdk-java/blob/43efdce18cd84ee1d35dad0b1a5d9fa75934db35/examples/authorize/src/main/java/com/dropbox/core/examples/authorize/Main.java#L64)?

**Comment by stacysimpson** [comment]
No, the authorization code is generated using a browser / Javascript client SDK including both redirectUri and state parameters. If I attempt to use the existing "withNoRedirect" methods within the java SDK, I'm unable to receive a valid access token. It fails because I didn't pass the 'redirectUri' and 'state' information.

**Comment by cakoose** [comment]
Can you describe your use case in more detail, just so I can understand what's going on?

Is it something like?
1. Javascript app initiates code flow, redirects to Dropbox website.
2. User clicks "Allow", Dropbox redirects back to Javascript app.
3. ???
4. Java app gets code/state somehow?

**Comment by stacysimpson** [comment]
Yes, we are using the 'Authorization Code Grants' flow in a hybrid server-side flow, where the user authorizes our app on the client side and the server uses the code to retrieve access / refresh tokens. Using this technique, the access token is never exposed to the browser, extensions, etc. for optimal security.

Basic process:
1. Javascript app initiates authorization code flow, redirects to Dropbox website
2. User clicks "Allow", Dropbox redirects back to Javascript app
3. App retrieves code (from url params) and passes the authorization code and state to our server
4. Our (Java-based) server uses the authorization code to retrieve an access token from Dropbox

As stated above, we are unable to use the Java client library's "withNoRedirect" options, as the Dropbox server returns an error. I don't remember the specific error, but it said something about the redirectUri not available and/or not matching. (BTW, other vendor's OAuth capabilities work the same way...we need to pass the same redirect uri that was used to generate the one-time authorization code.)

We could call the endpoints directly; however, it seems unnecessary. The PR I created resolves the problem; another approach is to make the 'finish' method public. Let me know if you have any more questions.

**Comment by cakoose** [comment]
I think making `finish` public might be better than adding a new method.  It's @jiuyangzhao's call.

Sort of a tangent, but I'm still curious about your design.  After step 4, what happens?  Does the server return the access token to the Javascript app?
- If so, is it not possible for extensions to see that network request?
- If not, could you just have step 2 redirect to the server app?

**Comment by stacysimpson** [comment]
Re: making 'finish' public. That's cool with me.

Yeah, step #5 is the server returning an authorization success / failure message to the client app. Here is a link with more details about the approach: [hybrid server side auth](https://developers.google.com/identity/sign-in/web/server-side-flow)

We choose this path because access tokens are only used by our server and the Javascript app is used to facilitate authorization.

**Comment by jiuyangzhao** [comment]
Hey @stacysimpson I just added a [public function](https://github.com/dropbox/dropbox-sdk-java/commit/c409404858d48a986e3d0f417ebb15344bb42240)
`public DbxAuthFinish finishFromCode(String code, String redirectUri)`

It worth mentioning that `state` is not sent to server even in the private finish so we don't need this parameter here.

This change will go with next SDK release in 3.0.1.

**Comment by stacysimpson** [comment]
Great, thanks!

**Comment by greg-db** [comment]
Release [3.0.1](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v3.0.1) is now available.

**Comment by stacysimpson** [comment]
Confirmed to work...thanks again!
